// ==========================================================
// Project: WpfHexEditor.ProjectSystem
// File: SolutionUserDto.cs
// Author: Derek Tremblay (derektremblay666@gmail.com)
// Contributors: Claude Sonnet 4.6
// Created: 2026-03-07
// Description:
//     DTOs for the .whsln.user sidecar file.
//     This file stores per-user, per-machine UI state that should NOT be
//     committed to source control: dock layout, tree expand state, etc.
//
// Architecture Notes:
//     Companion to SolutionDto (.whsln). Never merged into .whsln to keep
//     the solution file clean and VCS-friendly.
//     Read/written by SolutionUserSerializer.
//
// ==========================================================

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WpfHexEditor.Core.ProjectSystem.Dto;

/// <summary>
/// Root DTO for the <c>.whsln.user</c> sidecar file.
/// Stores per-user UI state (dock layout, tree expand state) alongside a solution.
/// </summary>
internal sealed class SolutionUserDto
{
    /// <summary>Format version — increment when adding breaking changes.</summary>
    [JsonPropertyName("version")]
    public int Version { get; set; } = 1;

    /// <summary>Solution Explorer tree expand/collapse state.</summary>
    [JsonPropertyName("treeState")]
    public SolutionTreeStateDto? TreeState { get; set; }

    /// <summary>
    /// Serialised dock-layout JSON (reserved for future use — moved from v1 .whsln).
    /// Not written yet; field kept for forward compatibility.
    /// </summary>
    [JsonPropertyName("dockLayout")]
    public string? DockLayout { get; set; }

    /// <summary>
    /// Relative path (from the solution file) of the project the user last
    /// designated as the startup project. Used for VS <c>.sln</c> solutions
    /// where the startup project cannot be stored in the shared solution file.
    /// <see langword="null"/> when the user has not explicitly set one.
    /// </summary>
    [JsonPropertyName("startupProjectPath")]
    public string? StartupProjectPath { get; set; }
}

/// <summary>
/// Stores which tree nodes are expanded in the Solution Explorer.
/// Only the <em>expanded</em> keys are stored; all others are treated as collapsed.
/// Keys are generated by <c>SolutionExplorerViewModel.StableKeyFor()</c>.
/// </summary>
internal sealed class SolutionTreeStateDto
{
    /// <summary>
    /// Stable identifiers of all currently-expanded nodes.
    /// Format: <c>"sol:{name}"</c>, <c>"proj:{id}"</c>, <c>"sfolder:{id}"</c>,
    /// <c>"vfolder:{id}"</c>, <c>"phys:{path}"</c>.
    /// </summary>
    [JsonPropertyName("expandedKeys")]
    public List<string> ExpandedKeys { get; set; } = [];
}
