// ==========================================================
// Project: WpfHexEditor.Plugins.ScreenRecorder
// File: Properties/ScreenRecorderResources.Designer.cs
// Description: Auto-generated resource accessor for ScreenRecorderResources.resx.
// Architecture Notes: Generated pattern — do not edit manually.
// ==========================================================

// <auto-generated />
namespace WpfHexEditor.Plugins.ScreenRecorder.Properties;

using System.Globalization;
using System.Resources;

internal static class ScreenRecorderResources
{
    private static readonly ResourceManager _rm =
        new("WpfHexEditor.Plugins.ScreenRecorder.Properties.ScreenRecorderResources",
            typeof(ScreenRecorderResources).Assembly);

    internal static ResourceManager ResourceManager => _rm;

    private static string Get(string key) =>
        _rm.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    // Plugin metadata
    public static string ScreenRecorder_PluginName       => Get(nameof(ScreenRecorder_PluginName));
    public static string ScreenRecorder_MenuItem         => Get(nameof(ScreenRecorder_MenuItem));
    public static string ScreenRecorder_DocumentTitle    => Get(nameof(ScreenRecorder_DocumentTitle));
    public static string ScreenRecorder_UntitledSession  => Get(nameof(ScreenRecorder_UntitledSession));

    // Toolbar actions
    public static string ScreenRecorder_Start            => Get(nameof(ScreenRecorder_Start));
    public static string ScreenRecorder_Stop             => Get(nameof(ScreenRecorder_Stop));
    public static string ScreenRecorder_Pause            => Get(nameof(ScreenRecorder_Pause));
    public static string ScreenRecorder_Resume           => Get(nameof(ScreenRecorder_Resume));
    public static string ScreenRecorder_Play             => Get(nameof(ScreenRecorder_Play));
    public static string ScreenRecorder_StopPlayback     => Get(nameof(ScreenRecorder_StopPlayback));
    public static string ScreenRecorder_ImportImages     => Get(nameof(ScreenRecorder_ImportImages));
    public static string ScreenRecorder_CaptureFrame     => Get(nameof(ScreenRecorder_CaptureFrame));
    public static string ScreenRecorder_SelectRegion     => Get(nameof(ScreenRecorder_SelectRegion));
    public static string ScreenRecorder_SaveSession      => Get(nameof(ScreenRecorder_SaveSession));
    public static string ScreenRecorder_OpenSession      => Get(nameof(ScreenRecorder_OpenSession));
    public static string ScreenRecorder_ExportGif        => Get(nameof(ScreenRecorder_ExportGif));
    public static string ScreenRecorder_ExportPng        => Get(nameof(ScreenRecorder_ExportPng));
    public static string ScreenRecorder_ExportMp4        => Get(nameof(ScreenRecorder_ExportMp4));

    // Capture modes
    public static string ScreenRecorder_ModeScreenshot   => Get(nameof(ScreenRecorder_ModeScreenshot));
    public static string ScreenRecorder_ModeTimed        => Get(nameof(ScreenRecorder_ModeTimed));
    public static string ScreenRecorder_ModeBoth         => Get(nameof(ScreenRecorder_ModeBoth));

    // Status bar
    public static string ScreenRecorder_StatusRecording  => Get(nameof(ScreenRecorder_StatusRecording));
    public static string ScreenRecorder_StatusPaused     => Get(nameof(ScreenRecorder_StatusPaused));
    public static string ScreenRecorder_StatusFrames     => Get(nameof(ScreenRecorder_StatusFrames));
    public static string ScreenRecorder_StatusHotkeys    => Get(nameof(ScreenRecorder_StatusHotkeys));

    // HUD overlay
    public static string ScreenRecorder_HudRecording     => Get(nameof(ScreenRecorder_HudRecording));
    public static string ScreenRecorder_HudPaused        => Get(nameof(ScreenRecorder_HudPaused));
    public static string ScreenRecorder_HudFrameCount    => Get(nameof(ScreenRecorder_HudFrameCount));
    public static string ScreenRecorder_HudEscCancel     => Get(nameof(ScreenRecorder_HudEscCancel));

    // Timeline
    public static string ScreenRecorder_DeleteSelected   => Get(nameof(ScreenRecorder_DeleteSelected));
    public static string ScreenRecorder_InsertBlank      => Get(nameof(ScreenRecorder_InsertBlank));
    public static string ScreenRecorder_DuplicateFrame   => Get(nameof(ScreenRecorder_DuplicateFrame));
    public static string ScreenRecorder_SetDelay         => Get(nameof(ScreenRecorder_SetDelay));
    public static string ScreenRecorder_GlobalDelay      => Get(nameof(ScreenRecorder_GlobalDelay));
    public static string ScreenRecorder_FrameLabel       => Get(nameof(ScreenRecorder_FrameLabel));

    // Preview
    public static string ScreenRecorder_ZoomIn           => Get(nameof(ScreenRecorder_ZoomIn));
    public static string ScreenRecorder_ZoomOut          => Get(nameof(ScreenRecorder_ZoomOut));
    public static string ScreenRecorder_Zoom1To1         => Get(nameof(ScreenRecorder_Zoom1To1));
    public static string ScreenRecorder_ZoomFit          => Get(nameof(ScreenRecorder_ZoomFit));
    public static string ScreenRecorder_Zoom100          => Get(nameof(ScreenRecorder_Zoom100));
    public static string ScreenRecorder_NoFrameSelected  => Get(nameof(ScreenRecorder_NoFrameSelected));
    public static string ScreenRecorder_EmptyTimeline    => Get(nameof(ScreenRecorder_EmptyTimeline));

    // Properties panel
    public static string ScreenRecorder_Properties       => Get(nameof(ScreenRecorder_Properties));
    public static string ScreenRecorder_CaptureRegion    => Get(nameof(ScreenRecorder_CaptureRegion));
    public static string ScreenRecorder_FullScreen       => Get(nameof(ScreenRecorder_FullScreen));
    public static string ScreenRecorder_OutputScale      => Get(nameof(ScreenRecorder_OutputScale));
    public static string ScreenRecorder_LoopCount        => Get(nameof(ScreenRecorder_LoopCount));
    public static string ScreenRecorder_RepeatLastFrame  => Get(nameof(ScreenRecorder_RepeatLastFrame));
    public static string ScreenRecorder_Interval         => Get(nameof(ScreenRecorder_Interval));
    public static string ScreenRecorder_RegionSummary    => Get(nameof(ScreenRecorder_RegionSummary));

    // Options page
    public static string ScreenRecorder_Options                    => Get(nameof(ScreenRecorder_Options));
    public static string ScreenRecorder_Options_Capture            => Get(nameof(ScreenRecorder_Options_Capture));
    public static string ScreenRecorder_Options_Overlay            => Get(nameof(ScreenRecorder_Options_Overlay));
    public static string ScreenRecorder_Options_Export             => Get(nameof(ScreenRecorder_Options_Export));
    public static string ScreenRecorder_Options_Session            => Get(nameof(ScreenRecorder_Options_Session));
    public static string ScreenRecorder_Options_Ffmpeg             => Get(nameof(ScreenRecorder_Options_Ffmpeg));
    public static string ScreenRecorder_Options_HotkeyCapture      => Get(nameof(ScreenRecorder_Options_HotkeyCapture));
    public static string ScreenRecorder_Options_HotkeyStop         => Get(nameof(ScreenRecorder_Options_HotkeyStop));
    public static string ScreenRecorder_Options_DefaultMode        => Get(nameof(ScreenRecorder_Options_DefaultMode));
    public static string ScreenRecorder_Options_TimerInterval      => Get(nameof(ScreenRecorder_Options_TimerInterval));
    public static string ScreenRecorder_Options_OverlayColor       => Get(nameof(ScreenRecorder_Options_OverlayColor));
    public static string ScreenRecorder_Options_OverlayOpacity     => Get(nameof(ScreenRecorder_Options_OverlayOpacity));
    public static string ScreenRecorder_Options_ShowHud            => Get(nameof(ScreenRecorder_Options_ShowHud));
    public static string ScreenRecorder_Options_DefaultOutputPath  => Get(nameof(ScreenRecorder_Options_DefaultOutputPath));
    public static string ScreenRecorder_Options_DefaultScale       => Get(nameof(ScreenRecorder_Options_DefaultScale));
    public static string ScreenRecorder_Options_DefaultLoopCount   => Get(nameof(ScreenRecorder_Options_DefaultLoopCount));
    public static string ScreenRecorder_Options_RepeatLastFrameDelay => Get(nameof(ScreenRecorder_Options_RepeatLastFrameDelay));
    public static string ScreenRecorder_Options_SaveFolder         => Get(nameof(ScreenRecorder_Options_SaveFolder));
    public static string ScreenRecorder_Options_ConfirmDiscard     => Get(nameof(ScreenRecorder_Options_ConfirmDiscard));
    public static string ScreenRecorder_Options_MaxFrames          => Get(nameof(ScreenRecorder_Options_MaxFrames));
    public static string ScreenRecorder_Options_FfmpegPath         => Get(nameof(ScreenRecorder_Options_FfmpegPath));
    public static string ScreenRecorder_Options_FfmpegBrowse       => Get(nameof(ScreenRecorder_Options_FfmpegBrowse));
    public static string ScreenRecorder_Options_FfmpegNotFound     => Get(nameof(ScreenRecorder_Options_FfmpegNotFound));

    // Dialogs
    public static string ScreenRecorder_SaveFilter           => Get(nameof(ScreenRecorder_SaveFilter));
    public static string ScreenRecorder_OpenFilter           => Get(nameof(ScreenRecorder_OpenFilter));
    public static string ScreenRecorder_GifFilter            => Get(nameof(ScreenRecorder_GifFilter));
    public static string ScreenRecorder_Mp4Filter            => Get(nameof(ScreenRecorder_Mp4Filter));
    public static string ScreenRecorder_ConfirmCancelTitle   => Get(nameof(ScreenRecorder_ConfirmCancelTitle));
    public static string ScreenRecorder_ConfirmCancelMsg     => Get(nameof(ScreenRecorder_ConfirmCancelMsg));
    public static string ScreenRecorder_ExportProgress       => Get(nameof(ScreenRecorder_ExportProgress));
    public static string ScreenRecorder_FileAssocAdvisory    => Get(nameof(ScreenRecorder_FileAssocAdvisory));
}
