//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.Editor.DocumentEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocumentEditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentEditorResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.Editor.DocumentEditor.Properties.DocumentEditorResources", typeof(DocumentEditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Align center.
        /// </summary>
        internal static string DocEditorHost_AlignCenterToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_AlignCenterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Align left.
        /// </summary>
        internal static string DocEditorHost_AlignLeftToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_AlignLeftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Align right.
        /// </summary>
        internal static string DocEditorHost_AlignRightToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_AlignRightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bold (Ctrl+B).
        /// </summary>
        internal static string DocEditorHost_BoldToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_BoldToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document.
        /// </summary>
        internal static string DocEditorHost_DocumentTitle {
            get {
                return ResourceManager.GetString("DocEditorHost_DocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Draft view — continuous scroll, compact margins.
        /// </summary>
        internal static string DocEditorHost_DraftViewToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_DraftViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Document.
        /// </summary>
        internal static string DocEditorHost_ExportDialogTitle {
            get {
                return ResourceManager.GetString("DocEditorHost_ExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exported — {0}.
        /// </summary>
        internal static string DocEditorHost_ExportedStatus {
            get {
                return ResourceManager.GetString("DocEditorHost_ExportedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export failed: {0}.
        /// </summary>
        internal static string DocEditorHost_ExportFailedStatus {
            get {
                return ResourceManager.GetString("DocEditorHost_ExportFailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export document.
        /// </summary>
        internal static string DocEditorHost_ExportToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_ExportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Focus.
        /// </summary>
        internal static string DocEditorHost_FocusModeLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_FocusModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Focus mode — zen writing (Ctrl+Shift+F).
        /// </summary>
        internal static string DocEditorHost_FocusModeToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_FocusModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forensic.
        /// </summary>
        internal static string DocEditorHost_ForensicModeLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_ForensicModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forensic analysis mode.
        /// </summary>
        internal static string DocEditorHost_ForensicModeToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_ForensicModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full.
        /// </summary>
        internal static string DocEditorHost_FullModeLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_FullModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full view (text + structure + hex).
        /// </summary>
        internal static string DocEditorHost_FullViewToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_FullViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex.
        /// </summary>
        internal static string DocEditorHost_HexModeLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_HexModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex view.
        /// </summary>
        internal static string DocEditorHost_HexViewToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_HexViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italic (Ctrl+I).
        /// </summary>
        internal static string DocEditorHost_ItalicToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_ItalicToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to open document: {0}.
        /// </summary>
        internal static string DocEditorHost_LoadErrorMessage {
            get {
                return ResourceManager.GetString("DocEditorHost_LoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading document….
        /// </summary>
        internal static string DocEditorHost_LoadingMessage {
            get {
                return ResourceManager.GetString("DocEditorHost_LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        internal static string DocEditorHost_MetaAuthorLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_MetaAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Created.
        /// </summary>
        internal static string DocEditorHost_MetaCreatedLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_MetaCreatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document metadata.
        /// </summary>
        internal static string DocEditorHost_MetadataToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_MetadataToolTip", resourceCulture);
            }
        }

        internal static string DocEditorHost_AnonymizeBtn {
            get {
                return ResourceManager.GetString("DocEditorHost_AnonymizeBtn", resourceCulture);
            }
        }

        internal static string DocEditorHost_EmbeddedToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_EmbeddedToolTip", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_Title {
            get {
                return ResourceManager.GetString("EmbeddedDlg_Title", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_ColKind {
            get {
                return ResourceManager.GetString("EmbeddedDlg_ColKind", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_ColName {
            get {
                return ResourceManager.GetString("EmbeddedDlg_ColName", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_ColSize {
            get {
                return ResourceManager.GetString("EmbeddedDlg_ColSize", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_ColSource {
            get {
                return ResourceManager.GetString("EmbeddedDlg_ColSource", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_Extract {
            get {
                return ResourceManager.GetString("EmbeddedDlg_Extract", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_ExtractToolTip {
            get {
                return ResourceManager.GetString("EmbeddedDlg_ExtractToolTip", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_OpenHex {
            get {
                return ResourceManager.GetString("EmbeddedDlg_OpenHex", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_OpenHexToolTip {
            get {
                return ResourceManager.GetString("EmbeddedDlg_OpenHexToolTip", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_Close {
            get {
                return ResourceManager.GetString("EmbeddedDlg_Close", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_CountFmt {
            get {
                return ResourceManager.GetString("EmbeddedDlg_CountFmt", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_EntryNotFoundFmt {
            get {
                return ResourceManager.GetString("EmbeddedDlg_EntryNotFoundFmt", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_NoSource {
            get {
                return ResourceManager.GetString("EmbeddedDlg_NoSource", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_SourceSha {
            get {
                return ResourceManager.GetString("EmbeddedDlg_SourceSha", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_ShaComputing {
            get {
                return ResourceManager.GetString("EmbeddedDlg_ShaComputing", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_CopySha {
            get {
                return ResourceManager.GetString("EmbeddedDlg_CopySha", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_HashAll {
            get {
                return ResourceManager.GetString("EmbeddedDlg_HashAll", resourceCulture);
            }
        }

        internal static string EmbeddedDlg_HashAllToolTip {
            get {
                return ResourceManager.GetString("EmbeddedDlg_HashAllToolTip", resourceCulture);
            }
        }

        internal static string DocEditorHost_PrintToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_PrintToolTip", resourceCulture);
            }
        }

        internal static string DocEditorHost_DiffToolTip {
            get { return ResourceManager.GetString("DocEditorHost_DiffToolTip", resourceCulture); }
        }
        internal static string DocDiffDlg_Title {
            get { return ResourceManager.GetString("DocDiffDlg_Title", resourceCulture); }
        }
        internal static string DocDiffDlg_LabelLeft {
            get { return ResourceManager.GetString("DocDiffDlg_LabelLeft", resourceCulture); }
        }
        internal static string DocDiffDlg_LabelRight {
            get { return ResourceManager.GetString("DocDiffDlg_LabelRight", resourceCulture); }
        }
        internal static string DocDiffDlg_PickRight {
            get { return ResourceManager.GetString("DocDiffDlg_PickRight", resourceCulture); }
        }
        internal static string DocDiffDlg_PickHint {
            get { return ResourceManager.GetString("DocDiffDlg_PickHint", resourceCulture); }
        }
        internal static string DocDiffDlg_ColKind {
            get { return ResourceManager.GetString("DocDiffDlg_ColKind", resourceCulture); }
        }
        internal static string DocDiffDlg_ColChange {
            get { return ResourceManager.GetString("DocDiffDlg_ColChange", resourceCulture); }
        }
        internal static string DocDiffDlg_ColText {
            get { return ResourceManager.GetString("DocDiffDlg_ColText", resourceCulture); }
        }
        internal static string DocDiffDlg_SummaryFmt {
            get { return ResourceManager.GetString("DocDiffDlg_SummaryFmt", resourceCulture); }
        }
        internal static string DocDiffDlg_NoLoaders {
            get { return ResourceManager.GetString("DocDiffDlg_NoLoaders", resourceCulture); }
        }
        internal static string DocDiffDlg_NoLoaderForFmt {
            get { return ResourceManager.GetString("DocDiffDlg_NoLoaderForFmt", resourceCulture); }
        }
        internal static string DocDiffDlg_Close {
            get { return ResourceManager.GetString("DocDiffDlg_Close", resourceCulture); }
        }

        internal static string DocEditorHost_AnonymizeToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_AnonymizeToolTip", resourceCulture);
            }
        }

        internal static string DocEditorHost_AnonymizeTitle {
            get {
                return ResourceManager.GetString("DocEditorHost_AnonymizeTitle", resourceCulture);
            }
        }

        internal static string DocEditorHost_AnonymizeConfirm {
            get {
                return ResourceManager.GetString("DocEditorHost_AnonymizeConfirm", resourceCulture);
            }
        }

        internal static string DocEditorHost_AnonymizeDoneFmt {
            get {
                return ResourceManager.GetString("DocEditorHost_AnonymizeDoneFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à —.
        /// </summary>
        internal static string DocEditorHost_MetaEmptyValue {
            get {
                return ResourceManager.GetString("DocEditorHost_MetaEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format.
        /// </summary>
        internal static string DocEditorHost_MetaFormatLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_MetaFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Macros.
        /// </summary>
        internal static string DocEditorHost_MetaMacrosLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_MetaMacrosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MIME.
        /// </summary>
        internal static string DocEditorHost_MetaMimeLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_MetaMimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modified.
        /// </summary>
        internal static string DocEditorHost_MetaModifiedLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_MetaModifiedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string DocEditorHost_MetaNoValue {
            get {
                return ResourceManager.GetString("DocEditorHost_MetaNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title.
        /// </summary>
        internal static string DocEditorHost_MetaTitleLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_MetaTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string DocEditorHost_MetaYesValue {
            get {
                return ResourceManager.GetString("DocEditorHost_MetaYesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No saver registered for &apos;{0}&apos;..
        /// </summary>
        internal static string DocEditorHost_NoSaverForExport {
            get {
                return ResourceManager.GetString("DocEditorHost_NoSaverForExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No saver registered for this file type..
        /// </summary>
        internal static string DocEditorHost_NoSaverStatus {
            get {
                return ResourceManager.GetString("DocEditorHost_NoSaverStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outline view — structure tree centred.
        /// </summary>
        internal static string DocEditorHost_OutlineViewToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_OutlineViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page setup (paper size, margins, columns…).
        /// </summary>
        internal static string DocEditorHost_PageSetupToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_PageSetupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page view — paginated A4/Letter cards.
        /// </summary>
        internal static string DocEditorHost_PageViewToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_PageViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  | Read Only.
        /// </summary>
        internal static string DocEditorHost_ReadOnlySuffix {
            get {
                return ResourceManager.GetString("DocEditorHost_ReadOnlySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Read Only.
        /// </summary>
        internal static string DocEditorHost_ReadOnlyToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_ReadOnlyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saved — {0}.
        /// </summary>
        internal static string DocEditorHost_SavedStatus {
            get {
                return ResourceManager.GetString("DocEditorHost_SavedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save failed: {0}.
        /// </summary>
        internal static string DocEditorHost_SaveFailedStatus {
            get {
                return ResourceManager.GetString("DocEditorHost_SaveFailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string DocEditorHost_SaveToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Split.
        /// </summary>
        internal static string DocEditorHost_SplitModeLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_SplitModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Split view (text + hex).
        /// </summary>
        internal static string DocEditorHost_SplitViewToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_SplitViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Strikethrough.
        /// </summary>
        internal static string DocEditorHost_StrikethroughToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_StrikethroughToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Structure.
        /// </summary>
        internal static string DocEditorHost_StructureModeLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_StructureModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Structure tree view.
        /// </summary>
        internal static string DocEditorHost_StructureViewToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_StructureViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        internal static string DocEditorHost_StyleCode {
            get {
                return ResourceManager.GetString("DocEditorHost_StyleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paragraph style.
        /// </summary>
        internal static string DocEditorHost_StyleDropdownToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_StyleDropdownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à H1.
        /// </summary>
        internal static string DocEditorHost_StyleH1 {
            get {
                return ResourceManager.GetString("DocEditorHost_StyleH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à H2.
        /// </summary>
        internal static string DocEditorHost_StyleH2 {
            get {
                return ResourceManager.GetString("DocEditorHost_StyleH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à H3.
        /// </summary>
        internal static string DocEditorHost_StyleH3 {
            get {
                return ResourceManager.GetString("DocEditorHost_StyleH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à H4.
        /// </summary>
        internal static string DocEditorHost_StyleH4 {
            get {
                return ResourceManager.GetString("DocEditorHost_StyleH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à H5.
        /// </summary>
        internal static string DocEditorHost_StyleH5 {
            get {
                return ResourceManager.GetString("DocEditorHost_StyleH5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à H6.
        /// </summary>
        internal static string DocEditorHost_StyleH6 {
            get {
                return ResourceManager.GetString("DocEditorHost_StyleH6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normal.
        /// </summary>
        internal static string DocEditorHost_StyleNormal {
            get {
                return ResourceManager.GetString("DocEditorHost_StyleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quote.
        /// </summary>
        internal static string DocEditorHost_StyleQuote {
            get {
                return ResourceManager.GetString("DocEditorHost_StyleQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paragraph styles (Ctrl+Alt+S).
        /// </summary>
        internal static string DocEditorHost_StylesPanelToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_StylesPanelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text.
        /// </summary>
        internal static string DocEditorHost_TextModeLabel {
            get {
                return ResourceManager.GetString("DocEditorHost_TextModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text view.
        /// </summary>
        internal static string DocEditorHost_TextViewToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_TextViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Underline (Ctrl+U).
        /// </summary>
        internal static string DocEditorHost_UnderlineToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_UnderlineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Focus.
        /// </summary>
        internal static string DocEditorHost_ViewModeFocus {
            get {
                return ResourceManager.GetString("DocEditorHost_ViewModeFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full.
        /// </summary>
        internal static string DocEditorHost_ViewModeFull {
            get {
                return ResourceManager.GetString("DocEditorHost_ViewModeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex.
        /// </summary>
        internal static string DocEditorHost_ViewModeHex {
            get {
                return ResourceManager.GetString("DocEditorHost_ViewModeHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Split.
        /// </summary>
        internal static string DocEditorHost_ViewModeSplit {
            get {
                return ResourceManager.GetString("DocEditorHost_ViewModeSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Structure.
        /// </summary>
        internal static string DocEditorHost_ViewModeStructure {
            get {
                return ResourceManager.GetString("DocEditorHost_ViewModeStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text.
        /// </summary>
        internal static string DocEditorHost_ViewModeText {
            get {
                return ResourceManager.GetString("DocEditorHost_ViewModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waiting for IDE to initialize….
        /// </summary>
        internal static string DocEditorHost_WaitingForIDE {
            get {
                return ResourceManager.GetString("DocEditorHost_WaitingForIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 100%.
        /// </summary>
        internal static string DocEditorHost_ZoomDefault {
            get {
                return ResourceManager.GetString("DocEditorHost_ZoomDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom in.
        /// </summary>
        internal static string DocEditorHost_ZoomInToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_ZoomInToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom out.
        /// </summary>
        internal static string DocEditorHost_ZoomOutToolTip {
            get {
                return ResourceManager.GetString("DocEditorHost_ZoomOutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string DocFindReplace_Close {
            get {
                return ResourceManager.GetString("DocFindReplace_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find All.
        /// </summary>
        internal static string DocFindReplace_FindAll {
            get {
                return ResourceManager.GetString("DocFindReplace_FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find:.
        /// </summary>
        internal static string DocFindReplace_FindLabel {
            get {
                return ResourceManager.GetString("DocFindReplace_FindLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find Next.
        /// </summary>
        internal static string DocFindReplace_FindNext {
            get {
                return ResourceManager.GetString("DocFindReplace_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find Prev.
        /// </summary>
        internal static string DocFindReplace_FindPrev {
            get {
                return ResourceManager.GetString("DocFindReplace_FindPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Match case.
        /// </summary>
        internal static string DocFindReplace_MatchCase {
            get {
                return ResourceManager.GetString("DocFindReplace_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regex.
        /// </summary>
        internal static string DocFindReplace_Regex {
            get {
                return ResourceManager.GetString("DocFindReplace_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace.
        /// </summary>
        internal static string DocFindReplace_Replace {
            get {
                return ResourceManager.GetString("DocFindReplace_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace All.
        /// </summary>
        internal static string DocFindReplace_ReplaceAll {
            get {
                return ResourceManager.GetString("DocFindReplace_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace:.
        /// </summary>
        internal static string DocFindReplace_ReplaceLabel {
            get {
                return ResourceManager.GetString("DocFindReplace_ReplaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find &amp; Replace.
        /// </summary>
        internal static string DocFindReplace_Title {
            get {
                return ResourceManager.GetString("DocFindReplace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Whole word.
        /// </summary>
        internal static string DocFindReplace_WholeWord {
            get {
                return ResourceManager.GetString("DocFindReplace_WholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex.
        /// </summary>
        internal static string DocHexPane_HexLabel {
            get {
                return ResourceManager.GetString("DocHexPane_HexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex  |  0x{0:X8}.
        /// </summary>
        internal static string DocHexPane_OffsetPattern {
            get {
                return ResourceManager.GetString("DocHexPane_OffsetPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A3  (29.7 × 42 cm).
        /// </summary>
        internal static string DocPageSettings_A3Option {
            get {
                return ResourceManager.GetString("DocPageSettings_A3Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A4  (21 × 29.7 cm).
        /// </summary>
        internal static string DocPageSettings_A4Option {
            get {
                return ResourceManager.GetString("DocPageSettings_A4Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A5  (14.8 × 21 cm).
        /// </summary>
        internal static string DocPageSettings_A5Option {
            get {
                return ResourceManager.GetString("DocPageSettings_A5Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply.
        /// </summary>
        internal static string DocPageSettings_ApplyButton {
            get {
                return ResourceManager.GetString("DocPageSettings_ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Box.
        /// </summary>
        internal static string DocPageSettings_BorderBox {
            get {
                return ResourceManager.GetString("DocPageSettings_BorderBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string DocPageSettings_BorderNone {
            get {
                return ResourceManager.GetString("DocPageSettings_BorderNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shadow.
        /// </summary>
        internal static string DocPageSettings_BorderShadow {
            get {
                return ResourceManager.GetString("DocPageSettings_BorderShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Border.
        /// </summary>
        internal static string DocPageSettings_BorderTab {
            get {
                return ResourceManager.GetString("DocPageSettings_BorderTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string DocPageSettings_CancelButton {
            get {
                return ResourceManager.GetString("DocPageSettings_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Columns.
        /// </summary>
        internal static string DocPageSettings_ColumnsTab {
            get {
                return ResourceManager.GetString("DocPageSettings_ColumnsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom.
        /// </summary>
        internal static string DocPageSettings_CustomOption {
            get {
                return ResourceManager.GetString("DocPageSettings_CustomOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Different content on first page.
        /// </summary>
        internal static string DocPageSettings_DifferentFirstPage {
            get {
                return ResourceManager.GetString("DocPageSettings_DifferentFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable footer.
        /// </summary>
        internal static string DocPageSettings_EnableFooter {
            get {
                return ResourceManager.GetString("DocPageSettings_EnableFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable header.
        /// </summary>
        internal static string DocPageSettings_EnableHeader {
            get {
                return ResourceManager.GetString("DocPageSettings_EnableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Equal column widths.
        /// </summary>
        internal static string DocPageSettings_EqualWidths {
            get {
                return ResourceManager.GetString("DocPageSettings_EqualWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Footer.
        /// </summary>
        internal static string DocPageSettings_FooterGroup {
            get {
                return ResourceManager.GetString("DocPageSettings_FooterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format:.
        /// </summary>
        internal static string DocPageSettings_FormatLabel {
            get {
                return ResourceManager.GetString("DocPageSettings_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Header/Footer.
        /// </summary>
        internal static string DocPageSettings_HeaderFooterTab {
            get {
                return ResourceManager.GetString("DocPageSettings_HeaderFooterTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Header.
        /// </summary>
        internal static string DocPageSettings_HeaderGroup {
            get {
                return ResourceManager.GetString("DocPageSettings_HeaderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inside:.
        /// </summary>
        internal static string DocPageSettings_InsideMargin {
            get {
                return ResourceManager.GetString("DocPageSettings_InsideMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Landscape.
        /// </summary>
        internal static string DocPageSettings_Landscape {
            get {
                return ResourceManager.GetString("DocPageSettings_Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left:.
        /// </summary>
        internal static string DocPageSettings_LeftMargin {
            get {
                return ResourceManager.GetString("DocPageSettings_LeftMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Legal  (8.5 × 14 in).
        /// </summary>
        internal static string DocPageSettings_LegalOption {
            get {
                return ResourceManager.GetString("DocPageSettings_LegalOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Letter (8.5 × 11 in).
        /// </summary>
        internal static string DocPageSettings_LetterOption {
            get {
                return ResourceManager.GetString("DocPageSettings_LetterOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Orientation:.
        /// </summary>
        internal static string DocPageSettings_OrientationLabel {
            get {
                return ResourceManager.GetString("DocPageSettings_OrientationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outside:.
        /// </summary>
        internal static string DocPageSettings_OutsideMargin {
            get {
                return ResourceManager.GetString("DocPageSettings_OutsideMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page.
        /// </summary>
        internal static string DocPageSettings_PageTab {
            get {
                return ResourceManager.GetString("DocPageSettings_PageTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Portrait.
        /// </summary>
        internal static string DocPageSettings_Portrait {
            get {
                return ResourceManager.GetString("DocPageSettings_Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right:.
        /// </summary>
        internal static string DocPageSettings_RightMargin {
            get {
                return ResourceManager.GetString("DocPageSettings_RightMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Same header on left/right pages.
        /// </summary>
        internal static string DocPageSettings_SameHeaderLR {
            get {
                return ResourceManager.GetString("DocPageSettings_SameHeaderLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show separator line between columns.
        /// </summary>
        internal static string DocPageSettings_ShowSeparator {
            get {
                return ResourceManager.GetString("DocPageSettings_ShowSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bold (Ctrl+B).
        /// </summary>
        internal static string DocPopToolbar_BoldToolTip {
            get {
                return ResourceManager.GetString("DocPopToolbar_BoldToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy as hex bytes.
        /// </summary>
        internal static string DocPopToolbar_CopyHexToolTip {
            get {
                return ResourceManager.GetString("DocPopToolbar_CopyHexToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy selected text.
        /// </summary>
        internal static string DocPopToolbar_CopyTextToolTip {
            get {
                return ResourceManager.GetString("DocPopToolbar_CopyTextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inspect block in Structure pane.
        /// </summary>
        internal static string DocPopToolbar_InspectToolTip {
            get {
                return ResourceManager.GetString("DocPopToolbar_InspectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italic (Ctrl+I).
        /// </summary>
        internal static string DocPopToolbar_ItalicToolTip {
            get {
                return ResourceManager.GetString("DocPopToolbar_ItalicToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jump to offset in Hex pane.
        /// </summary>
        internal static string DocPopToolbar_JumpHexToolTip {
            get {
                return ResourceManager.GetString("DocPopToolbar_JumpHexToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Underline (Ctrl+U).
        /// </summary>
        internal static string DocPopToolbar_UnderlineToolTip {
            get {
                return ResourceManager.GetString("DocPopToolbar_UnderlineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alerts.
        /// </summary>
        internal static string DocSb_AlertsLabel {
            get {
                return ResourceManager.GetString("DocSb_AlertsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blocks.
        /// </summary>
        internal static string DocSb_BlocksLabel {
            get {
                return ResourceManager.GetString("DocSb_BlocksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format.
        /// </summary>
        internal static string DocSb_FormatLabel {
            get {
                return ResourceManager.GetString("DocSb_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selection.
        /// </summary>
        internal static string DocSb_SelectionLabel {
            get {
                return ResourceManager.GetString("DocSb_SelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        internal static string DocSb_VersionLabel {
            get {
                return ResourceManager.GetString("DocSb_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View.
        /// </summary>
        internal static string DocSb_ViewLabel {
            get {
                return ResourceManager.GetString("DocSb_ViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page 1.
        /// </summary>
        internal static string DocStatusBar_DefaultPage {
            get {
                return ResourceManager.GetString("DocStatusBar_DefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Split.
        /// </summary>
        internal static string DocStatusBar_DefaultViewMode {
            get {
                return ResourceManager.GetString("DocStatusBar_DefaultViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0 words.
        /// </summary>
        internal static string DocStatusBar_DefaultWordCount {
            get {
                return ResourceManager.GetString("DocStatusBar_DefaultWordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 100%.
        /// </summary>
        internal static string DocStatusBar_DefaultZoom {
            get {
                return ResourceManager.GetString("DocStatusBar_DefaultZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to open forensic panel.
        /// </summary>
        internal static string DocStatusBar_ForensicBadgeToolTip {
            get {
                return ResourceManager.GetString("DocStatusBar_ForensicBadgeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format: {0} ({1}).
        /// </summary>
        internal static string DocStatusBar_FormatPattern {
            get {
                return ResourceManager.GetString("DocStatusBar_FormatPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page count.
        /// </summary>
        internal static string DocStatusBar_PageCountToolTip {
            get {
                return ResourceManager.GetString("DocStatusBar_PageCountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page 1 / {0}.
        /// </summary>
        internal static string DocStatusBar_PagePattern {
            get {
                return ResourceManager.GetString("DocStatusBar_PagePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:N0} words.
        /// </summary>
        internal static string DocStatusBar_WordCountPattern {
            get {
                return ResourceManager.GetString("DocStatusBar_WordCountPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Word count.
        /// </summary>
        internal static string DocStatusBar_WordCountToolTip {
            get {
                return ResourceManager.GetString("DocStatusBar_WordCountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:0}%.
        /// </summary>
        internal static string DocStatusBar_ZoomPattern {
            get {
                return ResourceManager.GetString("DocStatusBar_ZoomPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom level.
        /// </summary>
        internal static string DocStatusBar_ZoomToolTip {
            get {
                return ResourceManager.GetString("DocStatusBar_ZoomToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear filter.
        /// </summary>
        internal static string DocStructure_ClearFilterToolTip {
            get {
                return ResourceManager.GetString("DocStructure_ClearFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse all.
        /// </summary>
        internal static string DocStructure_CollapseAllToolTip {
            get {
                return ResourceManager.GetString("DocStructure_CollapseAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy offset.
        /// </summary>
        internal static string DocStructure_CopyOffsetMenuHeader {
            get {
                return ResourceManager.GetString("DocStructure_CopyOffsetMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy block text.
        /// </summary>
        internal static string DocStructure_CopyTextMenuHeader {
            get {
                return ResourceManager.GetString("DocStructure_CopyTextMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expand all.
        /// </summary>
        internal static string DocStructure_ExpandAllToolTip {
            get {
                return ResourceManager.GetString("DocStructure_ExpandAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter blocks….
        /// </summary>
        internal static string DocStructure_FilterPlaceholder {
            get {
                return ResourceManager.GetString("DocStructure_FilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Structure.
        /// </summary>
        internal static string DocStructure_Header {
            get {
                return ResourceManager.GetString("DocStructure_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jump to hex offset.
        /// </summary>
        internal static string DocStructure_JumpHexMenuHeader {
            get {
                return ResourceManager.GetString("DocStructure_JumpHexMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Navigate to text.
        /// </summary>
        internal static string DocStructure_NavigateMenuHeader {
            get {
                return ResourceManager.GetString("DocStructure_NavigateMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Caption.
        /// </summary>
        internal static string DocStyles_Caption {
            get {
                return ResourceManager.GetString("DocStyles_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        internal static string DocStyles_Code {
            get {
                return ResourceManager.GetString("DocStyles_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heading 1.
        /// </summary>
        internal static string DocStyles_Heading1 {
            get {
                return ResourceManager.GetString("DocStyles_Heading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heading 2.
        /// </summary>
        internal static string DocStyles_Heading2 {
            get {
                return ResourceManager.GetString("DocStyles_Heading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heading 3.
        /// </summary>
        internal static string DocStyles_Heading3 {
            get {
                return ResourceManager.GetString("DocStyles_Heading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heading 4.
        /// </summary>
        internal static string DocStyles_Heading4 {
            get {
                return ResourceManager.GetString("DocStyles_Heading4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heading 5.
        /// </summary>
        internal static string DocStyles_Heading5 {
            get {
                return ResourceManager.GetString("DocStyles_Heading5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heading 6.
        /// </summary>
        internal static string DocStyles_Heading6 {
            get {
                return ResourceManager.GetString("DocStyles_Heading6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intense Quote.
        /// </summary>
        internal static string DocStyles_IntenseQuote {
            get {
                return ResourceManager.GetString("DocStyles_IntenseQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List Paragraph.
        /// </summary>
        internal static string DocStyles_ListParagraph {
            get {
                return ResourceManager.GetString("DocStyles_ListParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normal.
        /// </summary>
        internal static string DocStyles_Normal {
            get {
                return ResourceManager.GetString("DocStyles_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quote.
        /// </summary>
        internal static string DocStyles_Quote {
            get {
                return ResourceManager.GetString("DocStyles_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forensic mode.
        /// </summary>
        internal static string DocTb_ForensicMode {
            get {
                return ResourceManager.GetString("DocTb_ForensicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex view.
        /// </summary>
        internal static string DocTb_HexView {
            get {
                return ResourceManager.GetString("DocTb_HexView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string DocTb_Save {
            get {
                return ResourceManager.GetString("DocTb_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Split view.
        /// </summary>
        internal static string DocTb_SplitView {
            get {
                return ResourceManager.GetString("DocTb_SplitView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Structure view.
        /// </summary>
        internal static string DocTb_StructureView {
            get {
                return ResourceManager.GetString("DocTb_StructureView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text view.
        /// </summary>
        internal static string DocTb_TextView {
            get {
                return ResourceManager.GetString("DocTb_TextView", resourceCulture);
            }
        }

        internal static string DocMiniMap_MenuTitle {
            get { return ResourceManager.GetString("DocMiniMap_MenuTitle", resourceCulture); }
        }
        internal static string DocMiniMap_ShowMiniMap {
            get { return ResourceManager.GetString("DocMiniMap_ShowMiniMap", resourceCulture); }
        }
        internal static string DocMiniMap_RenderBlocks {
            get { return ResourceManager.GetString("DocMiniMap_RenderBlocks", resourceCulture); }
        }
        internal static string DocMiniMap_SliderAlways {
            get { return ResourceManager.GetString("DocMiniMap_SliderAlways", resourceCulture); }
        }
        internal static string DocMiniMap_SliderMouseOver {
            get { return ResourceManager.GetString("DocMiniMap_SliderMouseOver", resourceCulture); }
        }
        internal static string DocStats_Title {
            get { return ResourceManager.GetString("DocStats_Title", resourceCulture); }
        }
        internal static string DocStats_WordCount {
            get { return ResourceManager.GetString("DocStats_WordCount", resourceCulture); }
        }
        internal static string DocStats_CharCount {
            get { return ResourceManager.GetString("DocStats_CharCount", resourceCulture); }
        }
        internal static string DocStats_CharNoSpaceCount {
            get { return ResourceManager.GetString("DocStats_CharNoSpaceCount", resourceCulture); }
        }
        internal static string DocStats_BlockCount {
            get { return ResourceManager.GetString("DocStats_BlockCount", resourceCulture); }
        }
        internal static string DocStats_LineCount {
            get { return ResourceManager.GetString("DocStats_LineCount", resourceCulture); }
        }
        internal static string DocStats_Close {
            get { return ResourceManager.GetString("DocStats_Close", resourceCulture); }
        }
    }
}
