// ==========================================================
// Project: WpfHexEditor.PluginSandbox
// File: Program.cs
// Author: Derek Tremblay (derektremblay666@gmail.com)
// Contributors: Claude Sonnet 4.6
// Created: 2026-03-15
// Description:
//     Entry point for the sandbox child process.
//     Connects to the IDE host via Named Pipe, then runs a message loop
//     dispatching all incoming IPC envelopes to SandboxedPluginRunner.
//
// Usage:
//     WpfHexEditor.PluginSandbox.exe <pipeName>
//
// Architecture Notes:
//     - The IDE is the pipe SERVER; this process is the pipe CLIENT.
//     - pipeName is generated by SandboxProcessManager with a per-plugin Guid suffix.
//     - All unhandled exceptions are caught and pushed as CrashNotification.
//     - Exit codes: 0=clean, 1=bad args, 2=fatal exception.
// ==========================================================

using System.IO.Pipes;
using System.Windows;
using System.Windows.Threading;
using WpfHexEditor.PluginSandbox;
using WpfHexEditor.SDK.Sandbox;

internal static class Program
{
    // [STAThread] must be on a non-async entry point.
    // async Task Main ignores [STAThread] — the compiler wraps it in an MTA state machine.
    // Instead, we start Dispatcher.Run() here to pump the STA message loop, and
    // post the async work via InvokeAsync so plugins can safely create WPF UI elements.
    [STAThread]
    private static int Main(string[] args)
    {
        if (args.Length < 1)
        {
            Console.Error.WriteLine("Usage: WpfHexEditor.PluginSandbox <pipeName>");
            return 1;
        }

        var dispatcher = Dispatcher.CurrentDispatcher;
        int exitCode = 0;

        // Create a WPF Application on the STA thread so that:
        //   1. Application.Current is non-null → ThemeBootstrapper.Apply() can merge
        //      the host's theme ResourceDictionary into Application.Current.Resources.
        //   2. {StaticResource} lookups in plugin XAML succeed (resources are resolved
        //      through Application.Resources.MergedDictionaries, not just local dicts).
        // We do NOT call app.Run() — Dispatcher.Run() below drives the same STA pump.
        _ = new Application { ShutdownMode = ShutdownMode.OnExplicitShutdown };

        dispatcher.InvokeAsync(async () =>
        {
            exitCode = await RunAsync(args[0]).ConfigureAwait(true);
            dispatcher.BeginInvokeShutdown(DispatcherPriority.Normal);
        });

        Dispatcher.Run(); // STA message pump — keeps thread alive for WPF UI creation
        return exitCode;
    }

    private static async Task<int> RunAsync(string pipeName)
    {
        // Capture STA dispatcher before the first await — after ConfigureAwait(false)
        // the continuation runs on a thread-pool MTA thread where CurrentDispatcher
        // would create a new non-STA dispatcher.
        var dispatcher = Dispatcher.CurrentDispatcher;

        using var cts = new CancellationTokenSource();
        Console.CancelKeyPress += (_, e) => { e.Cancel = true; cts.Cancel(); };

        IpcChannel? channel = null;
        SandboxedPluginRunner? runner = null;

        try
        {
            // 1. Connect to IDE pipe server
            var pipe = new NamedPipeClientStream(
                ".", pipeName, PipeDirection.InOut, PipeOptions.Asynchronous);
            await pipe.ConnectAsync(cts.Token).ConfigureAwait(false);

            channel = new IpcChannel(pipe);
            var relay = new SandboxMetricsRelay(channel);
            runner = new SandboxedPluginRunner(channel, relay, cts.Token, Console.Error.WriteLine);

            // 2. Message loop
            // I/O receive stays on thread pool; plugin handling is dispatched back to
            // the STA thread so plugins can safely create WPF UI elements.
            while (!cts.IsCancellationRequested)
            {
                var envelope = await channel.ReceiveAsync<SandboxEnvelope>(cts.Token)
                    .ConfigureAwait(false); // thread pool OK for I/O

                if (envelope is null) break; // Pipe closed by host

                var continueLoop = await dispatcher
                    .InvokeAsync(async () => await runner!.HandleAsync(envelope))
                    .Task.Unwrap()
                    .ConfigureAwait(false); // result back to thread pool for next receive
                if (!continueLoop) break;
            }

            return 0;
        }
        catch (OperationCanceledException) { return 0; }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[Sandbox] Fatal: {ex.Message}");

            if (channel is not null && runner is not null)
                await runner.PushCrash("unknown", ex, "Startup").ConfigureAwait(false);

            return 2;
        }
        finally
        {
            if (runner is not null) await runner.DisposeAsync().ConfigureAwait(false);
            if (channel is not null) await channel.DisposeAsync().ConfigureAwait(false);
        }
    }
}
