// ==========================================================
// Project: WpfHexEditor.Editor.ResxEditor
// File: Services/ResxDesignerGenerator.cs
// Description:
//     Generates a strongly-typed Designer.cs accessor class
//     that mirrors what Visual Studio's ResXFileCodeGenerator
//     produces.  Output can be previewed in the split panel
//     or written to disk.
// ==========================================================

using System.Text;
using System.IO;
using WpfHexEditor.Editor.ResxEditor.Models;

namespace WpfHexEditor.Editor.ResxEditor.Services;

/// <summary>Options for the Designer.cs generator.</summary>
public sealed record ResxDesignerOptions(
    string Namespace,
    string ClassName,
    bool   IsPublic = false);

/// <summary>Generates a strongly-typed <c>*.Designer.cs</c> resource accessor class.</summary>
public static class ResxDesignerGenerator
{
    /// <summary>
    /// Generates the Designer.cs content for <paramref name="entries"/>
    /// and writes it to <paramref name="outputPath"/>.
    /// </summary>
    public static async Task<string> GenerateAndSaveAsync(
        IReadOnlyList<ResxEntry> entries,
        ResxDesignerOptions      options,
        string                   outputPath,
        CancellationToken        ct = default)
    {
        var code = Generate(entries, options);
        await File.WriteAllTextAsync(outputPath, code,
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: true), ct);
        return code;
    }

    /// <summary>Generates the Designer.cs content as a string (for preview).</summary>
    public static string Generate(IReadOnlyList<ResxEntry> entries, ResxDesignerOptions options)
    {
        var modifier  = options.IsPublic ? "public" : "internal";
        var ns        = options.Namespace;
        var cls       = options.ClassName;
        var sb        = new StringBuilder();

        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by WpfHexEditor ResxEditor.");
        sb.AppendLine($"//     Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using System.Resources;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>Strongly-typed resource accessor for the {cls} resource set.</summary>");
        sb.AppendLine($"{modifier} static class {cls}");
        sb.AppendLine("{");
        sb.AppendLine("    private static ResourceManager? _resourceManager;");
        sb.AppendLine("    private static CultureInfo?     _resourceCulture;");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Returns the cached ResourceManager for {cls}.</summary>");
        sb.AppendLine($"    {modifier} static ResourceManager ResourceManager");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        sb.AppendLine($"            _resourceManager ??= new ResourceManager(\"{(string.IsNullOrEmpty(ns) ? cls : $"{ns}.{cls}")}\", typeof({cls}).Assembly);");
        sb.AppendLine("            return _resourceManager;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Overrides the current thread CultureInfo for lookups.</summary>");
        sb.AppendLine($"    {modifier} static CultureInfo? Culture");
        sb.AppendLine("    {");
        sb.AppendLine("        get => _resourceCulture;");
        sb.AppendLine("        set => _resourceCulture = value;");
        sb.AppendLine("    }");

        // One property per String entry
        foreach (var entry in entries.Where(e => e.EntryType == ResxEntryType.String))
        {
            var safeName = ToSafeIdentifier(entry.Name);
            var xmlDoc   = string.IsNullOrEmpty(entry.Comment)
                ? $"/// <summary>Looks up the localized string '{EscapeXml(entry.Name)}'.</summary>"
                : $"/// <summary>{EscapeXml(entry.Comment)}</summary>";

            sb.AppendLine();
            sb.AppendLine($"    {xmlDoc}");
            sb.AppendLine($"    {modifier} static string? {safeName}");
            sb.AppendLine($"        => ResourceManager.GetString(\"{entry.Name}\", _resourceCulture);");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ------------------------------------------------------------------

    private static string ToSafeIdentifier(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');

        if (sb.Length > 0 && char.IsDigit(sb[0]))
            sb.Insert(0, '_');

        return sb.Length == 0 ? "_resource" : sb.ToString();
    }

    private static string EscapeXml(string s)
        => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
