//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.Editor.CodeEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeEditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeEditorResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.Editor.CodeEditor.Properties.CodeEditorResources", typeof(CodeEditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find All References.
        /// </summary>
        internal static string CodeCtx_FindAllReferences {
            get {
                return ResourceManager.GetString("CodeCtx_FindAllReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh Highlights.
        /// </summary>
        internal static string CodeCtx_RefreshHighlights {
            get {
                return ResourceManager.GetString("CodeCtx_RefreshHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse all.
        /// </summary>
        internal static string CodeEd_FindRef_CollapseAll {
            get {
                return ResourceManager.GetString("CodeEd_FindRef_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Minimap.
        /// </summary>
        internal static string CodeEd_Minimap_MenuTitle {
            get {
                return ResourceManager.GetString("CodeEd_Minimap_MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Render _Characters.
        /// </summary>
        internal static string CodeEd_Minimap_RenderChars {
            get {
                return ResourceManager.GetString("CodeEd_Minimap_RenderChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si_de.
        /// </summary>
        internal static string CodeEd_Minimap_Side {
            get {
                return ResourceManager.GetString("CodeEd_Minimap_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left.
        /// </summary>
        internal static string CodeEd_Minimap_SideLeft {
            get {
                return ResourceManager.GetString("CodeEd_Minimap_SideLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right.
        /// </summary>
        internal static string CodeEd_Minimap_SideRight {
            get {
                return ResourceManager.GetString("CodeEd_Minimap_SideRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fill.
        /// </summary>
        internal static string CodeEd_Minimap_SizeFill {
            get {
                return ResourceManager.GetString("CodeEd_Minimap_SizeFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fit.
        /// </summary>
        internal static string CodeEd_Minimap_SizeFit {
            get {
                return ResourceManager.GetString("CodeEd_Minimap_SizeFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proportional.
        /// </summary>
        internal static string CodeEd_Minimap_SizeProportional {
            get {
                return ResourceManager.GetString("CodeEd_Minimap_SizeProportional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S_lider.
        /// </summary>
        internal static string CodeEd_Minimap_Slider {
            get {
                return ResourceManager.GetString("CodeEd_Minimap_Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Always.
        /// </summary>
        internal static string CodeEd_Minimap_SliderAlways {
            get {
                return ResourceManager.GetString("CodeEd_Minimap_SliderAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mouse Over.
        /// </summary>
        internal static string CodeEd_Minimap_SliderMouseOver {
            get {
                return ResourceManager.GetString("CodeEd_Minimap_SliderMouseOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Vertical size.
        /// </summary>
        internal static string CodeEd_Minimap_VerticalSize {
            get {
                return ResourceManager.GetString("CodeEd_Minimap_VerticalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse all.
        /// </summary>
        internal static string CodeEd_Refs_CollapseAll {
            get {
                return ResourceManager.GetString("CodeEd_Refs_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expand all.
        /// </summary>
        internal static string CodeEd_Refs_ExpandAll {
            get {
                return ResourceManager.GetString("CodeEd_Refs_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        internal static string CodeEd_Refs_Refresh {
            get {
                return ResourceManager.GetString("CodeEd_Refs_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Condition:.
        /// </summary>
        internal static string CodeEditor_BreakpointConditionLabel {
            get {
                return ResourceManager.GetString("CodeEditor_BreakpointConditionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string CodeEditor_BreakpointDelete {
            get {
                return ResourceManager.GetString("CodeEditor_BreakpointDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Breakpoint.
        /// </summary>
        internal static string CodeEditor_BreakpointDeleteBreakpoint {
            get {
                return ResourceManager.GetString("CodeEditor_BreakpointDeleteBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable.
        /// </summary>
        internal static string CodeEditor_BreakpointDisable {
            get {
                return ResourceManager.GetString("CodeEditor_BreakpointDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit Condition.
        /// </summary>
        internal static string CodeEditor_BreakpointEditCondition {
            get {
                return ResourceManager.GetString("CodeEditor_BreakpointEditCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable.
        /// </summary>
        internal static string CodeEditor_BreakpointEnable {
            get {
                return ResourceManager.GetString("CodeEditor_BreakpointEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot place breakpoint on this line.
        /// </summary>
        internal static string CodeEditor_BreakpointInvalidToolTip {
            get {
                return ResourceManager.GetString("CodeEditor_BreakpointInvalidToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string CodeEditor_BreakpointSave {
            get {
                return ResourceManager.GetString("CodeEditor_BreakpointSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings….
        /// </summary>
        internal static string CodeEditor_BreakpointSettings {
            get {
                return ResourceManager.GetString("CodeEditor_BreakpointSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to toggle breakpoint.
        /// </summary>
        internal static string CodeEditor_BreakpointToggleToolTip {
            get {
                return ResourceManager.GetString("CodeEditor_BreakpointToggleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Breakpoint.
        /// </summary>
        internal static string CodeEditor_BreakpointTypeBreakpoint {
            get {
                return ResourceManager.GetString("CodeEditor_BreakpointTypeBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conditional.
        /// </summary>
        internal static string CodeEditor_BreakpointTypeConditional {
            get {
                return ResourceManager.GetString("CodeEditor_BreakpointTypeConditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled.
        /// </summary>
        internal static string CodeEditor_BreakpointTypeDisabled {
            get {
                return ResourceManager.GetString("CodeEditor_BreakpointTypeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse to Definitions.
        /// </summary>
        internal static string CodeEditor_ContextMenuCollapseToDefs {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuCollapseToDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Column Rulers.
        /// </summary>
        internal static string CodeEditor_ContextMenuColumnRulers {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuColumnRulers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string CodeEditor_ContextMenuDelete {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find....
        /// </summary>
        internal static string CodeEditor_ContextMenuFind {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find All References.
        /// </summary>
        internal static string CodeEditor_ContextMenuFindAllRefs {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuFindAllRefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format Document.
        /// </summary>
        internal static string CodeEditor_ContextMenuFormatDocument {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuFormatDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format JSON.
        /// </summary>
        internal static string CodeEditor_ContextMenuFormatJson {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuFormatJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format Selection.
        /// </summary>
        internal static string CodeEditor_ContextMenuFormatSelection {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuFormatSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formatting.
        /// </summary>
        internal static string CodeEditor_ContextMenuFormatting {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options....
        /// </summary>
        internal static string CodeEditor_ContextMenuFormattingOptions {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuFormattingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Definition.
        /// </summary>
        internal static string CodeEditor_ContextMenuGoToDefinition {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuGoToDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Implementation.
        /// </summary>
        internal static string CodeEditor_ContextMenuGoToImplementation {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuGoToImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outlining.
        /// </summary>
        internal static string CodeEditor_ContextMenuOutlining {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuOutlining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Peek Definition.
        /// </summary>
        internal static string CodeEditor_ContextMenuPeekDefinition {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuPeekDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quick Fix….
        /// </summary>
        internal static string CodeEditor_ContextMenuQuickFix {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuQuickFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Re-analyze Folding.
        /// </summary>
        internal static string CodeEditor_ContextMenuReanalyzeFolding {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuReanalyzeFolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh Highlights.
        /// </summary>
        internal static string CodeEditor_ContextMenuRefreshHighlights {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuRefreshHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename Symbol.
        /// </summary>
        internal static string CodeEditor_ContextMenuRenameSymbol {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuRenameSymbol", resourceCulture);
            }
        }

        internal static string CodeEditor_ContextMenuRefactor      { get { return ResourceManager.GetString("CodeEditor_ContextMenuRefactor",      resourceCulture); } }
        internal static string CodeEditor_RefactorRename           { get { return ResourceManager.GetString("CodeEditor_RefactorRename",           resourceCulture); } }
        internal static string CodeEditor_RefactorExtractMethod    { get { return ResourceManager.GetString("CodeEditor_RefactorExtractMethod",    resourceCulture); } }
        internal static string CodeEditor_RefactorExtractClass     { get { return ResourceManager.GetString("CodeEditor_RefactorExtractClass",     resourceCulture); } }
        internal static string CodeEditor_RefactorIntroduceVariable{ get { return ResourceManager.GetString("CodeEditor_RefactorIntroduceVariable",resourceCulture); } }
        internal static string CodeEditor_RefactorInlineMethod     { get { return ResourceManager.GetString("CodeEditor_RefactorInlineMethod",     resourceCulture); } }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace....
        /// </summary>
        internal static string CodeEditor_ContextMenuReplace {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select All.
        /// </summary>
        internal static string CodeEditor_ContextMenuSelectAll {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Call Hierarchy.
        /// </summary>
        internal static string CodeEditor_ContextMenuShowCallHierarchy {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuShowCallHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Type Hierarchy.
        /// </summary>
        internal static string CodeEditor_ContextMenuShowTypeHierarchy {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuShowTypeHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Whitespace.
        /// </summary>
        internal static string CodeEditor_ContextMenuShowWhitespace {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuShowWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop Hiding Current.
        /// </summary>
        internal static string CodeEditor_ContextMenuStopHidingCurrent {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuStopHidingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop Outlining.
        /// </summary>
        internal static string CodeEditor_ContextMenuStopOutlining {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuStopOutlining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle All Outlining.
        /// </summary>
        internal static string CodeEditor_ContextMenuToggleAllOutlining {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuToggleAllOutlining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Outlining.
        /// </summary>
        internal static string CodeEditor_ContextMenuToggleOutlining {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuToggleOutlining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate JSON.
        /// </summary>
        internal static string CodeEditor_ContextMenuValidateJson {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuValidateJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Always.
        /// </summary>
        internal static string CodeEditor_ContextMenuWhitespaceAlways {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuWhitespaceAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string CodeEditor_ContextMenuWhitespaceNone {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuWhitespaceNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selection Only.
        /// </summary>
        internal static string CodeEditor_ContextMenuWhitespaceSelection {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuWhitespaceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Word Highlight.
        /// </summary>
        internal static string CodeEditor_ContextMenuWordHighlight {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuWordHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Word Wrap.
        /// </summary>
        internal static string CodeEditor_ContextMenuWordWrap {
            get {
                return ResourceManager.GetString("CodeEditor_ContextMenuWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code Editor.
        /// </summary>
        internal static string CodeEditor_DisplayName {
            get {
                return ResourceManager.GetString("CodeEditor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format Document.
        /// </summary>
        internal static string CodeEditor_FormatDocumentTransaction {
            get {
                return ResourceManager.GetString("CodeEditor_FormatDocumentTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot format — invalid JSON:\n{0}.
        /// </summary>
        internal static string CodeEditor_FormatJsonError {
            get {
                return ResourceManager.GetString("CodeEditor_FormatJsonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format Error.
        /// </summary>
        internal static string CodeEditor_FormatJsonErrorTitle {
            get {
                return ResourceManager.GetString("CodeEditor_FormatJsonErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format Selection.
        /// </summary>
        internal static string CodeEditor_FormatSelectionTransaction {
            get {
                return ResourceManager.GetString("CodeEditor_FormatSelectionTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Line.
        /// </summary>
        internal static string CodeEditor_GoToLine {
            get {
                return ResourceManager.GetString("CodeEditor_GoToLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string CodeEditor_GoToLineButton {
            get {
                return ResourceManager.GetString("CodeEditor_GoToLineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Line number (1 - {0}):.
        /// </summary>
        internal static string CodeEditor_GoToLineLabel {
            get {
                return ResourceManager.GetString("CodeEditor_GoToLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Line.
        /// </summary>
        internal static string CodeEditor_GoToLineTitle {
            get {
                return ResourceManager.GetString("CodeEditor_GoToLineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse all.
        /// </summary>
        internal static string CodeEditor_ReferencesCollapseAll {
            get {
                return ResourceManager.GetString("CodeEditor_ReferencesCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} reference(s).
        /// </summary>
        internal static string CodeEditor_ReferencesCounter {
            get {
                return ResourceManager.GetString("CodeEditor_ReferencesCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expand all.
        /// </summary>
        internal static string CodeEditor_ReferencesExpandAll {
            get {
                return ResourceManager.GetString("CodeEditor_ReferencesExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pin to Find References panel.
        /// </summary>
        internal static string CodeEditor_ReferencesPinTooltip {
            get {
                return ResourceManager.GetString("CodeEditor_ReferencesPinTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        internal static string CodeEditor_ReferencesRefresh {
            get {
                return ResourceManager.GetString("CodeEditor_ReferencesRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à References — {0}.
        /// </summary>
        internal static string CodeEditor_ReferencesTitle {
            get {
                return ResourceManager.GetString("CodeEditor_ReferencesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ctrl+Click to send email.
        /// </summary>
        internal static string CodeEditor_UrlTooltipEmail {
            get {
                return ResourceManager.GetString("CodeEditor_UrlTooltipEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ctrl+Click to open.
        /// </summary>
        internal static string CodeEditor_UrlTooltipLink {
            get {
                return ResourceManager.GetString("CodeEditor_UrlTooltipLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid JSON: {0}.
        /// </summary>
        internal static string CodeEditor_ValidateJsonError {
            get {
                return ResourceManager.GetString("CodeEditor_ValidateJsonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation Error.
        /// </summary>
        internal static string CodeEditor_ValidateJsonErrorTitle {
            get {
                return ResourceManager.GetString("CodeEditor_ValidateJsonErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSON is valid..
        /// </summary>
        internal static string CodeEditor_ValidateJsonSuccess {
            get {
                return ResourceManager.GetString("CodeEditor_ValidateJsonSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation.
        /// </summary>
        internal static string CodeEditor_ValidateJsonTitle {
            get {
                return ResourceManager.GetString("CodeEditor_ValidateJsonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto-indent:.
        /// </summary>
        internal static string CodeEditorOptions_AutoIndentLabel {
            get {
                return ResourceManager.GetString("CodeEditorOptions_AutoIndentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bracket pair colorization.
        /// </summary>
        internal static string CodeEditorOptions_BracketColorizeContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_BracketColorizeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Colors brackets with CE_Bracket_1/2/3/4 based on nesting depth (requires bracketPairs in the language&apos;s whfmt).
        /// </summary>
        internal static string CodeEditorOptions_BracketColorizeToolTip {
            get {
                return ResourceManager.GetString("CodeEditorOptions_BracketColorizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable code folding.
        /// </summary>
        internal static string CodeEditorOptions_CodeFoldingContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_CodeFoldingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à These settings override the language .whfmt defaults. Leave unchecked checkboxes at their default (indeterminate) state to inherit the language rules..
        /// </summary>
        internal static string CodeEditorOptions_CodeFormattingInfo {
            get {
                return ResourceManager.GetString("CodeEditorOptions_CodeFormattingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code Formatting.
        /// </summary>
        internal static string CodeEditorOptions_CodeFormattingSection {
            get {
                return ResourceManager.GetString("CodeEditorOptions_CodeFormattingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Code Lens (inline reference counts).
        /// </summary>
        internal static string CodeEditorOptions_CodeLensContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_CodeLensContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shows reference count above each declaration. Click the hint to open the References popup..
        /// </summary>
        internal static string CodeEditorOptions_CodeLensToolTip {
            get {
                return ResourceManager.GetString("CodeEditorOptions_CodeLensToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pick.
        /// </summary>
        internal static string CodeEditorOptions_ColorPickButton {
            get {
                return ResourceManager.GetString("CodeEditorOptions_ColorPickButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color swatch preview.
        /// </summary>
        internal static string CodeEditorOptions_ColorSwatchContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_ColorSwatchContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shows a 12×12 color swatch next to color literals (e.g. #FF5733) in CSS, XAML, C# files.
        /// </summary>
        internal static string CodeEditorOptions_ColorSwatchToolTip {
            get {
                return ResourceManager.GetString("CodeEditorOptions_ColorSwatchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convert tabs to spaces.
        /// </summary>
        internal static string CodeEditorOptions_ConvertTabsContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_ConvertTabsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display.
        /// </summary>
        internal static string CodeEditorOptions_DisplaySection {
            get {
                return ResourceManager.GetString("CodeEditorOptions_DisplaySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Features.
        /// </summary>
        internal static string CodeEditorOptions_FeaturesSection {
            get {
                return ResourceManager.GetString("CodeEditorOptions_FeaturesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable Find All References (Shift+F12).
        /// </summary>
        internal static string CodeEditorOptions_FindAllRefsContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_FindAllRefsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requires an active Language Server (LSP) for the current file type.
        /// </summary>
        internal static string CodeEditorOptions_FindAllRefsToolTip {
            get {
                return ResourceManager.GetString("CodeEditorOptions_FindAllRefsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle fold regions on double-click.
        /// </summary>
        internal static string CodeEditorOptions_FoldToggleContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_FoldToggleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Font family:.
        /// </summary>
        internal static string CodeEditorOptions_FontFamilyLabel {
            get {
                return ResourceManager.GetString("CodeEditorOptions_FontFamilyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Font.
        /// </summary>
        internal static string CodeEditorOptions_FontSection {
            get {
                return ResourceManager.GetString("CodeEditorOptions_FontSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size:.
        /// </summary>
        internal static string CodeEditorOptions_FontSizeLabel {
            get {
                return ResourceManager.GetString("CodeEditorOptions_FontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format on Save (Ctrl+S).
        /// </summary>
        internal static string CodeEditorOptions_FormatOnSaveContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_FormatOnSaveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatically formats the document when saving. Uses LSP formatting if available, otherwise applies whfmt indentation rules..
        /// </summary>
        internal static string CodeEditorOptions_FormatOnSaveToolTip {
            get {
                return ResourceManager.GetString("CodeEditorOptions_FormatOnSaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indentation.
        /// </summary>
        internal static string CodeEditorOptions_IndentationSection {
            get {
                return ResourceManager.GetString("CodeEditorOptions_IndentationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indent case/when labels.
        /// </summary>
        internal static string CodeEditorOptions_IndentCaseLabelsContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_IndentCaseLabelsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add one indent level to case/when labels inside switch. Indeterminate = .whfmt default..
        /// </summary>
        internal static string CodeEditorOptions_IndentCaseLabelsToolTip {
            get {
                return ResourceManager.GetString("CodeEditorOptions_IndentCaseLabelsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert final newline.
        /// </summary>
        internal static string CodeEditorOptions_InsertFinalNewlineContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_InsertFinalNewlineContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ensure the file ends with exactly one newline. Indeterminate = use .whfmt language default..
        /// </summary>
        internal static string CodeEditorOptions_InsertFinalNewlineToolTip {
            get {
                return ResourceManager.GetString("CodeEditorOptions_InsertFinalNewlineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable multi-caret editing (Alt+Click).
        /// </summary>
        internal static string CodeEditorOptions_MultiCaretContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_MultiCaretContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Organize imports on format.
        /// </summary>
        internal static string CodeEditorOptions_OrganizeImportsContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_OrganizeImportsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort using/import directives alphabetically when formatting. Indeterminate = .whfmt default..
        /// </summary>
        internal static string CodeEditorOptions_OrganizeImportsToolTip {
            get {
                return ResourceManager.GetString("CodeEditorOptions_OrganizeImportsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset to theme.
        /// </summary>
        internal static string CodeEditorOptions_ResetColorsButton {
            get {
                return ResourceManager.GetString("CodeEditorOptions_ResetColorsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show scope guides.
        /// </summary>
        internal static string CodeEditorOptions_ScopeGuidesContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_ScopeGuidesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show line numbers.
        /// </summary>
        internal static string CodeEditorOptions_ShowLineNumbersContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_ShowLineNumbersContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show whitespace:.
        /// </summary>
        internal static string CodeEditorOptions_ShowWhitespaceLabel {
            get {
                return ResourceManager.GetString("CodeEditorOptions_ShowWhitespaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable SmartComplete.
        /// </summary>
        internal static string CodeEditorOptions_SmartCompleteContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_SmartCompleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable snippets.
        /// </summary>
        internal static string CodeEditorOptions_SnippetsContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_SnippetsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Space after commas.
        /// </summary>
        internal static string CodeEditorOptions_SpaceAfterCommaContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_SpaceAfterCommaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert a space after commas in argument/parameter lists. Indeterminate = .whfmt default..
        /// </summary>
        internal static string CodeEditorOptions_SpaceAfterCommaToolTip {
            get {
                return ResourceManager.GetString("CodeEditorOptions_SpaceAfterCommaToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Space after keywords (if, for, while).
        /// </summary>
        internal static string CodeEditorOptions_SpaceAfterKeywordsContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_SpaceAfterKeywordsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert a space between control keywords and opening paren: if (...) vs if(...). Indeterminate = .whfmt default..
        /// </summary>
        internal static string CodeEditorOptions_SpaceAfterKeywordsToolTip {
            get {
                return ResourceManager.GetString("CodeEditorOptions_SpaceAfterKeywordsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Space around binary operators.
        /// </summary>
        internal static string CodeEditorOptions_SpaceAroundOpsContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_SpaceAroundOpsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert spaces around +, -, *, /, ==, etc. Indeterminate = .whfmt default..
        /// </summary>
        internal static string CodeEditorOptions_SpaceAroundOpsToolTip {
            get {
                return ResourceManager.GetString("CodeEditorOptions_SpaceAroundOpsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Syntax Colors.
        /// </summary>
        internal static string CodeEditorOptions_SyntaxColorsSection {
            get {
                return ResourceManager.GetString("CodeEditorOptions_SyntaxColorsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tab size:.
        /// </summary>
        internal static string CodeEditorOptions_TabSizeLabel {
            get {
                return ResourceManager.GetString("CodeEditorOptions_TabSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trim trailing whitespace.
        /// </summary>
        internal static string CodeEditorOptions_TrimTrailingContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_TrimTrailingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove trailing spaces/tabs on each line. Indeterminate = use .whfmt language default..
        /// </summary>
        internal static string CodeEditorOptions_TrimTrailingToolTip {
            get {
                return ResourceManager.GetString("CodeEditorOptions_TrimTrailingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Highlight word under caret.
        /// </summary>
        internal static string CodeEditorOptions_WordHighlightContent {
            get {
                return ResourceManager.GetString("CodeEditorOptions_WordHighlightContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Highlights all occurrences of the word under the cursor and shows tick marks on the scroll bar.
        /// </summary>
        internal static string CodeEditorOptions_WordHighlightToolTip {
            get {
                return ResourceManager.GetString("CodeEditorOptions_WordHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Settings.
        /// </summary>
        internal static string CodeEditorSettings_ExportButtonContent {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ExportButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export settings to JSON file.
        /// </summary>
        internal static string CodeEditorSettings_ExportButtonToolTip {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ExportButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Settings.
        /// </summary>
        internal static string CodeEditorSettings_ExportDialogTitle {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to export settings:\n{0}.
        /// </summary>
        internal static string CodeEditorSettings_ExportFailedMessage {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ExportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Failed.
        /// </summary>
        internal static string CodeEditorSettings_ExportFailedTitle {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ExportFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings exported successfully to:\n{0}.
        /// </summary>
        internal static string CodeEditorSettings_ExportSuccessMessage {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ExportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Successful.
        /// </summary>
        internal static string CodeEditorSettings_ExportSuccessTitle {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ExportSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Settings.
        /// </summary>
        internal static string CodeEditorSettings_ImportButtonContent {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ImportButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import settings from JSON file.
        /// </summary>
        internal static string CodeEditorSettings_ImportButtonToolTip {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ImportButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Settings.
        /// </summary>
        internal static string CodeEditorSettings_ImportDialogTitle {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ImportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to import settings:\n{0}.
        /// </summary>
        internal static string CodeEditorSettings_ImportFailedMessage {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ImportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Failed.
        /// </summary>
        internal static string CodeEditorSettings_ImportFailedTitle {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ImportFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings imported successfully from:\n{0}.
        /// </summary>
        internal static string CodeEditorSettings_ImportSuccessMessage {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ImportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Successful.
        /// </summary>
        internal static string CodeEditorSettings_ImportSuccessTitle {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ImportSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No CodeEditor control is connected..
        /// </summary>
        internal static string CodeEditorSettings_NoEditorMessage {
            get {
                return ResourceManager.GetString("CodeEditorSettings_NoEditorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string CodeEditorSettings_NoEditorTitle {
            get {
                return ResourceManager.GetString("CodeEditorSettings_NoEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Live Preview.
        /// </summary>
        internal static string CodeEditorSettings_PreviewHeader {
            get {
                return ResourceManager.GetString("CodeEditorSettings_PreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preview will appear here when a CodeEditor is connected.
        /// </summary>
        internal static string CodeEditorSettings_PreviewPlaceholder {
            get {
                return ResourceManager.GetString("CodeEditorSettings_PreviewPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset to Defaults.
        /// </summary>
        internal static string CodeEditorSettings_ResetButtonContent {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ResetButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset all settings to default values.
        /// </summary>
        internal static string CodeEditorSettings_ResetButtonToolTip {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ResetButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All settings have been reset to their default values..
        /// </summary>
        internal static string CodeEditorSettings_ResetCompleteMessage {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ResetCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset Complete.
        /// </summary>
        internal static string CodeEditorSettings_ResetCompleteTitle {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ResetCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to reset all settings to their default values?.
        /// </summary>
        internal static string CodeEditorSettings_ResetConfirmMessage {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ResetConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm Reset.
        /// </summary>
        internal static string CodeEditorSettings_ResetConfirmTitle {
            get {
                return ResourceManager.GetString("CodeEditorSettings_ResetConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        internal static string CodeSb_RefreshLabel {
            get {
                return ResourceManager.GetString("CodeSb_RefreshLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Render frame time in milliseconds.
        /// </summary>
        internal static string CodeSb_RefreshTooltip {
            get {
                return ResourceManager.GetString("CodeSb_RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Untitled.json.
        /// </summary>
        internal static string FormatScriptEditor_DefaultFileName {
            get {
                return ResourceManager.GetString("FormatScriptEditor_DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editor.
        /// </summary>
        internal static string FormatScriptEditor_EditorTabHeader {
            get {
                return ResourceManager.GetString("FormatScriptEditor_EditorTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Embedded Formats.
        /// </summary>
        internal static string FormatScriptEditor_EmbeddedFormatsHeader {
            get {
                return ResourceManager.GetString("FormatScriptEditor_EmbeddedFormatsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0 Errors.
        /// </summary>
        internal static string FormatScriptEditor_ErrorCountStatus {
            get {
                return ResourceManager.GetString("FormatScriptEditor_ErrorCountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSON.
        /// </summary>
        internal static string FormatScriptEditor_FileTypeStatus {
            get {
                return ResourceManager.GetString("FormatScriptEditor_FileTypeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to format JSON: {0}.
        /// </summary>
        internal static string FormatScriptEditor_FormatJsonError {
            get {
                return ResourceManager.GetString("FormatScriptEditor_FormatJsonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format Error.
        /// </summary>
        internal static string FormatScriptEditor_FormatJsonErrorTitle {
            get {
                return ResourceManager.GetString("FormatScriptEditor_FormatJsonErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format.
        /// </summary>
        internal static string FormatScriptEditor_FormatText {
            get {
                return ResourceManager.GetString("FormatScriptEditor_FormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format JSON (Ctrl+Shift+F).
        /// </summary>
        internal static string FormatScriptEditor_FormatToolTip {
            get {
                return ResourceManager.GetString("FormatScriptEditor_FormatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ln 1, Col 1.
        /// </summary>
        internal static string FormatScriptEditor_LineColStatus {
            get {
                return ResourceManager.GetString("FormatScriptEditor_LineColStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to load embedded format: {0}.
        /// </summary>
        internal static string FormatScriptEditor_LoadEmbeddedError {
            get {
                return ResourceManager.GetString("FormatScriptEditor_LoadEmbeddedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string FormatScriptEditor_LoadEmbeddedErrorTitle {
            get {
                return ResourceManager.GetString("FormatScriptEditor_LoadEmbeddedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to load file: {0}.
        /// </summary>
        internal static string FormatScriptEditor_LoadFileError {
            get {
                return ResourceManager.GetString("FormatScriptEditor_LoadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string FormatScriptEditor_LoadFileErrorTitle {
            get {
                return ResourceManager.GetString("FormatScriptEditor_LoadFileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to load embedded formats: {0}.
        /// </summary>
        internal static string FormatScriptEditor_LoadFormatsError {
            get {
                return ResourceManager.GetString("FormatScriptEditor_LoadFormatsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string FormatScriptEditor_LoadFormatsErrorTitle {
            get {
                return ResourceManager.GetString("FormatScriptEditor_LoadFormatsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New.
        /// </summary>
        internal static string FormatScriptEditor_NewText {
            get {
                return ResourceManager.GetString("FormatScriptEditor_NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Format Definition.
        /// </summary>
        internal static string FormatScriptEditor_NewToolTip {
            get {
                return ResourceManager.GetString("FormatScriptEditor_NewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No file loaded.
        /// </summary>
        internal static string FormatScriptEditor_NoFileLoaded {
            get {
                return ResourceManager.GetString("FormatScriptEditor_NoFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Format Definition.
        /// </summary>
        internal static string FormatScriptEditor_OpenDialogTitle {
            get {
                return ResourceManager.GetString("FormatScriptEditor_OpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        internal static string FormatScriptEditor_OpenText {
            get {
                return ResourceManager.GetString("FormatScriptEditor_OpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Format Definition.
        /// </summary>
        internal static string FormatScriptEditor_OpenToolTip {
            get {
                return ResourceManager.GetString("FormatScriptEditor_OpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load a format definition to see preview....
        /// </summary>
        internal static string FormatScriptEditor_PreviewPlaceholder {
            get {
                return ResourceManager.GetString("FormatScriptEditor_PreviewPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preview.
        /// </summary>
        internal static string FormatScriptEditor_PreviewTabHeader {
            get {
                return ResourceManager.GetString("FormatScriptEditor_PreviewTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Redo.
        /// </summary>
        internal static string FormatScriptEditor_RedoText {
            get {
                return ResourceManager.GetString("FormatScriptEditor_RedoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Redo (Ctrl+Y).
        /// </summary>
        internal static string FormatScriptEditor_RedoToolTip {
            get {
                return ResourceManager.GetString("FormatScriptEditor_RedoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run Test.
        /// </summary>
        internal static string FormatScriptEditor_RunTestButton {
            get {
                return ResourceManager.GetString("FormatScriptEditor_RunTestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to save changes to the current file?.
        /// </summary>
        internal static string FormatScriptEditor_SaveChangesMessage {
            get {
                return ResourceManager.GetString("FormatScriptEditor_SaveChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Changes.
        /// </summary>
        internal static string FormatScriptEditor_SaveChangesTitle {
            get {
                return ResourceManager.GetString("FormatScriptEditor_SaveChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Format Definition.
        /// </summary>
        internal static string FormatScriptEditor_SaveDialogTitle {
            get {
                return ResourceManager.GetString("FormatScriptEditor_SaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to save file: {0}.
        /// </summary>
        internal static string FormatScriptEditor_SaveFailedMessage {
            get {
                return ResourceManager.GetString("FormatScriptEditor_SaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string FormatScriptEditor_SaveFailedTitle {
            get {
                return ResourceManager.GetString("FormatScriptEditor_SaveFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File saved successfully!.
        /// </summary>
        internal static string FormatScriptEditor_SaveSuccessMessage {
            get {
                return ResourceManager.GetString("FormatScriptEditor_SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        internal static string FormatScriptEditor_SaveSuccessTitle {
            get {
                return ResourceManager.GetString("FormatScriptEditor_SaveSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string FormatScriptEditor_SaveText {
            get {
                return ResourceManager.GetString("FormatScriptEditor_SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Current File.
        /// </summary>
        internal static string FormatScriptEditor_SaveToolTip {
            get {
                return ResourceManager.GetString("FormatScriptEditor_SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Test File....
        /// </summary>
        internal static string FormatScriptEditor_SelectTestFileButton {
            get {
                return ResourceManager.GetString("FormatScriptEditor_SelectTestFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Errors.
        /// </summary>
        internal static string FormatScriptEditor_StatusErrors {
            get {
                return ResourceManager.GetString("FormatScriptEditor_StatusErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ln {0}, Col {1}.
        /// </summary>
        internal static string FormatScriptEditor_StatusLineCol {
            get {
                return ResourceManager.GetString("FormatScriptEditor_StatusLineCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Warnings.
        /// </summary>
        internal static string FormatScriptEditor_StatusWarnings {
            get {
                return ResourceManager.GetString("FormatScriptEditor_StatusWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test your format definition against sample files here.\n\nSelect a file and click &apos;Run Test&apos; to see parsing results..
        /// </summary>
        internal static string FormatScriptEditor_TestInstructions {
            get {
                return ResourceManager.GetString("FormatScriptEditor_TestInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test.
        /// </summary>
        internal static string FormatScriptEditor_TestTabHeader {
            get {
                return ResourceManager.GetString("FormatScriptEditor_TestTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Undo.
        /// </summary>
        internal static string FormatScriptEditor_UndoText {
            get {
                return ResourceManager.GetString("FormatScriptEditor_UndoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Undo (Ctrl+Z).
        /// </summary>
        internal static string FormatScriptEditor_UndoToolTip {
            get {
                return ResourceManager.GetString("FormatScriptEditor_UndoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        internal static string FormatScriptEditor_ValidateText {
            get {
                return ResourceManager.GetString("FormatScriptEditor_ValidateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate Format Definition.
        /// </summary>
        internal static string FormatScriptEditor_ValidateToolTip {
            get {
                return ResourceManager.GetString("FormatScriptEditor_ValidateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation Results.
        /// </summary>
        internal static string FormatScriptEditor_ValidationResultsHeader {
            get {
                return ResourceManager.GetString("FormatScriptEditor_ValidationResultsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation.
        /// </summary>
        internal static string FormatScriptEditor_ValidationTabHeader {
            get {
                return ResourceManager.GetString("FormatScriptEditor_ValidationTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0 Warnings.
        /// </summary>
        internal static string FormatScriptEditor_WarningCountStatus {
            get {
                return ResourceManager.GetString("FormatScriptEditor_WarningCountStatus", resourceCulture);
            }
        }
    }
}
