// ==========================================================
// Project: whfmt.CodeGen
// File: Generator/FSharpGenerator.cs
// Description: F# record + DU parser generator from .whfmt definitions.
// Architecture: Emits F# record with typed fields, DU for valueMaps, BinaryReader-based parse function.
// ==========================================================

using System.Text;

namespace WhfmtCodeGen.Generator;

internal static class FSharpGenerator
{
    public static string Generate(
        string formatName, string category, string version, string desc,
        string namespaceName, string className,
        List<ParserGenerator.BlockDef> blocks,
        List<ParserGenerator.ChecksumDef> checksums)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"// Generated by whfmt-codegen from '{formatName}' v{version} [F# mode]");
        if (!string.IsNullOrEmpty(desc)) sb.AppendLine($"// {desc}");
        sb.AppendLine("// Do not edit — regenerate with: whfmt-codegen generate --lang fsharp");
        sb.AppendLine();
        sb.AppendLine($"module {namespaceName}.{className}");
        sb.AppendLine();
        sb.AppendLine("open System");
        sb.AppendLine("open System.IO");
        sb.AppendLine();

        // Emit discriminated unions for valueMap fields
        foreach (var b in blocks)
        {
            if (b.ValueMap.Count < 2) continue;
            string duName = b.PropertyName + "Kind";
            sb.AppendLine($"type {duName} =");
            foreach (var kv in b.ValueMap)
            {
                string caseName = ToFSharpCase(kv.Value);
                sb.AppendLine($"    | {caseName}");
            }
            sb.AppendLine($"    | Unknown of {MapFSharpType(b.CsTypeSimple)}");
            sb.AppendLine();
        }

        // Emit the record type
        sb.AppendLine($"type {className} = {{");
        foreach (var b in blocks)
        {
            if (string.IsNullOrEmpty(b.PropertyName)) continue;
            string fsType = b.ValueMap.Count >= 2 ? b.PropertyName + "Kind" : MapFSharpType(b.CsTypeSimple);
            sb.AppendLine($"    {b.PropertyName}: {fsType}");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // Emit parse function
        sb.AppendLine($"let parse (stream: Stream) : {className} =");
        sb.AppendLine("    let br = new BinaryReader(stream, Text.Encoding.Latin1, leaveOpen = true)");
        sb.AppendLine("    let seek offset = stream.Seek(int64 offset, SeekOrigin.Begin) |> ignore");
        sb.AppendLine("    {");

        foreach (var b in blocks)
        {
            if (string.IsNullOrEmpty(b.PropertyName)) continue;
            sb.AppendLine($"        // {b.Name} @ offset {b.Offset}");
            string readCall = ReadFSharp(b);
            if (b.ValueMap.Count >= 2)
            {
                string duName = b.PropertyName + "Kind";
                sb.AppendLine($"        {b.PropertyName} =");
                sb.AppendLine($"            seek {b.Offset}");
                sb.AppendLine($"            let raw = {readCall}");
                sb.AppendLine($"            match raw with");
                foreach (var kv in b.ValueMap)
                {
                    string caseName = ToFSharpCase(kv.Value);
                    sb.AppendLine($"            | {kv.Key} -> {duName}.{caseName}");
                }
                sb.AppendLine($"            | _ -> {duName}.Unknown raw");
            }
            else
            {
                sb.AppendLine($"        {b.PropertyName} = (seek {b.Offset}; {readCall})");
            }
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"let parseFile path = File.OpenRead(path) |> parse");

        return sb.ToString();
    }

    private static string MapFSharpType(string csType) => csType switch
    {
        "byte"   => "byte",
        "sbyte"  => "sbyte",
        "ushort" => "uint16",
        "short"  => "int16",
        "uint"   => "uint32",
        "int"    => "int32",
        "ulong"  => "uint64",
        "long"   => "int64",
        "float"  => "single",
        "double" => "float",
        "string" => "string",
        _        => "byte[]",
    };

    private static string ReadFSharp(ParserGenerator.BlockDef b) => b.CsTypeSimple switch
    {
        "byte"   => "br.ReadByte()",
        "sbyte"  => "br.ReadSByte()",
        "ushort" => b.Endian == "big" ? "bswap16 (br.ReadUInt16())" : "br.ReadUInt16()",
        "short"  => "br.ReadInt16()",
        "uint"   => b.Endian == "big" ? "bswap32 (br.ReadUInt32())" : "br.ReadUInt32()",
        "int"    => "br.ReadInt32()",
        "ulong"  => "br.ReadUInt64()",
        "long"   => "br.ReadInt64()",
        "float"  => "br.ReadSingle()",
        "double" => "br.ReadDouble()",
        "string" => $"System.String(br.ReadChars({b.Length})).TrimEnd(char 0)",
        _        => $"br.ReadBytes({b.Length})",
    };

    private static string ToFSharpCase(string label)
    {
        if (string.IsNullOrEmpty(label)) return "Unknown";
        var sb = new StringBuilder();
        bool upper = true;
        foreach (char c in label)
        {
            if (!char.IsLetterOrDigit(c)) { upper = true; continue; }
            sb.Append(upper ? char.ToUpper(c) : c);
            upper = false;
        }
        var r = sb.ToString();
        return r.Length > 0 && char.IsDigit(r[0]) ? "V" + r : r;
    }
}
