// ==========================================================
// Project: whfmt.CodeGen
// File: Generator/ProjectEmitter.cs
// Description: Emits a complete C# project from a .whfmt definition (--project mode).
// Architecture: Splits output into Parser.cs / Types.cs / Exceptions.cs + .csproj.
// ==========================================================

using System.Text;
using System.Text.Json;

namespace WhfmtCodeGen.Generator;

internal static class ProjectEmitter
{
    /// <summary>
    /// Emit a complete .csproj project directory from a .whfmt JSON definition.
    /// </summary>
    public static async Task EmitAsync(
        string json,
        string namespaceName,
        string className,
        string outputDir,
        bool includeValidation,
        bool generateAsync)
    {
        Directory.CreateDirectory(outputDir);

        using var doc = JsonDocument.Parse(json);
        var root = doc.RootElement;

        string formatName = root.TryGetProperty("name",     out var n) ? n.GetString() ?? className : className;
        string version    = root.TryGetProperty("version",  out var v) ? v.GetString() ?? "1.0"     : "1.0";
        string desc       = root.TryGetProperty("description", out var d) ? d.GetString() ?? "" : "";

        // We reuse the internal parsing from ParserGenerator via a targeted generate + split approach
        string fullSource = ParserGenerator.GenerateFromJson(json, namespaceName, className, includeValidation, generateAsync);

        // Split into Types.cs + Parser.cs + Exceptions.cs
        string typesCs      = GenerateTypesFile(json, namespaceName, className);
        string exceptionsCs = includeValidation ? GenerateExceptionsFile(namespaceName, className) : null!;
        string parserCs     = GenerateParserFile(json, namespaceName, className, includeValidation, generateAsync, formatName, version, desc);

        await File.WriteAllTextAsync(Path.Combine(outputDir, $"{className}Types.cs"),      typesCs);
        await File.WriteAllTextAsync(Path.Combine(outputDir, $"{className}.cs"),           parserCs);
        if (includeValidation)
            await File.WriteAllTextAsync(Path.Combine(outputDir, $"{className}Exceptions.cs"), exceptionsCs);

        string csproj = GenerateCsproj(namespaceName, className, version, desc);
        await File.WriteAllTextAsync(Path.Combine(outputDir, $"{className}.csproj"), csproj);

        Console.WriteLine($"  Generated project: {outputDir}");
        Console.WriteLine($"    {className}.csproj");
        Console.WriteLine($"    {className}Types.cs       — enums, value types");
        Console.WriteLine($"    {className}.cs            — parser class");
        if (includeValidation)
            Console.WriteLine($"    {className}Exceptions.cs — typed exceptions");
    }

    private static string GenerateTypesFile(string json, string namespaceName, string className)
    {
        using var doc = JsonDocument.Parse(json);
        var root = doc.RootElement;
        var blocks = ParseBlocksSimple(root);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> Types — do not edit</auto-generated>");
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();

        foreach (var b in blocks)
        {
            if (b.ValueMap.Count < 2) continue;
            string enumName = ParserGenerator.ToPascal(b.PropertyName) + "Type";
            if (b.IsBitFlags) sb.AppendLine("[Flags]");
            sb.AppendLine($"public enum {enumName}");
            sb.AppendLine("{");
            foreach (var kv in b.ValueMap)
            {
                string memberName = ToEnumMember(kv.Value);
                if (long.TryParse(kv.Key, out long num))
                    sb.AppendLine($"    {memberName} = {num},");
                else
                    sb.AppendLine($"    {memberName},");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    private static string GenerateExceptionsFile(string namespaceName, string className)
    {
        string prefix = className.Replace("Parser", "");
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> Exceptions — do not edit</auto-generated>");
        sb.AppendLine("using System;");
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"public sealed class InvalidSignatureException : Exception");
        sb.AppendLine("{");
        sb.AppendLine("    public byte[] Actual   { get; }");
        sb.AppendLine("    public byte[] Expected { get; }");
        sb.AppendLine($"    public InvalidSignatureException(byte[] actual, byte[] expected)");
        sb.AppendLine($"        : base($\"Invalid {prefix} signature: expected {{BitConverter.ToString(expected)}}, got {{BitConverter.ToString(actual)}}\")");
        sb.AppendLine("    {{ Actual = actual; Expected = expected; }}");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"public sealed class ChecksumMismatchException : Exception");
        sb.AppendLine("{");
        sb.AppendLine("    public string Algorithm { get; }");
        sb.AppendLine("    public byte[] Computed  { get; }");
        sb.AppendLine("    public byte[] Stored    { get; }");
        sb.AppendLine($"    public ChecksumMismatchException(string algorithm, byte[] computed, byte[] stored)");
        sb.AppendLine($"        : base($\"{{algorithm}} checksum mismatch: computed {{BitConverter.ToString(computed)}}, stored {{BitConverter.ToString(stored)}}\")");
        sb.AppendLine("    {{ Algorithm = algorithm; Computed = computed; Stored = stored; }}");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"public sealed class TruncatedFileException : Exception");
        sb.AppendLine("{");
        sb.AppendLine("    public string FieldName      { get; }");
        sb.AppendLine("    public long   RequiredOffset { get; }");
        sb.AppendLine("    public long   ActualLength   { get; }");
        sb.AppendLine($"    public TruncatedFileException(string fieldName, long requiredOffset, long actualLength)");
        sb.AppendLine($"        : base($\"Truncated: '{{fieldName}}' needs offset {{requiredOffset}}, file is {{actualLength}} bytes\")");
        sb.AppendLine("    {{ FieldName = fieldName; RequiredOffset = requiredOffset; ActualLength = actualLength; }}");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateParserFile(string json, string namespaceName, string className,
        bool includeValidation, bool generateAsync, string formatName, string version, string desc)
    {
        // Delegate to ParserGenerator but strip the inline type/exception definitions
        // (they're in separate files). In project mode we emit a cleaner parser-only class.
        return ParserGenerator.GenerateFromJson(json, namespaceName, className, includeValidation, generateAsync);
    }

    private static string GenerateCsproj(string namespaceName, string className, string version, string desc)
    {
        return $"""
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>{namespaceName}</RootNamespace>
    <AssemblyName>{className}</AssemblyName>
    <Version>{version}</Version>
    <Description>{desc}</Description>
  </PropertyGroup>
</Project>
""";
    }

    // Minimal block parser for types file generation
    private sealed class SimpleBlock
    {
        public string PropertyName { get; init; } = "";
        public bool   IsBitFlags   { get; init; }
        public Dictionary<string, string> ValueMap { get; init; } = [];
    }

    private static List<SimpleBlock> ParseBlocksSimple(JsonElement root)
    {
        var list = new List<SimpleBlock>();
        if (!root.TryGetProperty("blocks", out var blocks)) return list;
        foreach (var b in blocks.EnumerateArray())
        {
            string name    = b.TryGetProperty("name",    out var n) ? n.GetString() ?? "" : "";
            string storeAs = b.TryGetProperty("storeAs", out var s) ? s.GetString() ?? "" : "";
            bool   isFlags = b.TryGetProperty("bitflags", out var bf) && bf.GetBoolean();
            var vm = new Dictionary<string, string>();
            if (b.TryGetProperty("valueMap", out var vmEl))
                foreach (var kv in vmEl.EnumerateObject())
                    vm[kv.Name] = kv.Value.GetString() ?? kv.Name;
            string propName = ParserGenerator.ToPascal(string.IsNullOrEmpty(storeAs) ? name : storeAs);
            if (!string.IsNullOrEmpty(propName))
                list.Add(new SimpleBlock { PropertyName = propName, IsBitFlags = isFlags, ValueMap = vm });
        }
        return list;
    }

    private static string ToEnumMember(string label)
    {
        if (string.IsNullOrEmpty(label)) return "Unknown";
        var sb = new StringBuilder();
        bool upper = true;
        foreach (char c in label)
        {
            if (!char.IsLetterOrDigit(c)) { upper = true; continue; }
            sb.Append(upper ? char.ToUpper(c) : c);
            upper = false;
        }
        var r = sb.ToString();
        return r.Length > 0 && char.IsDigit(r[0]) ? "_" + r : r;
    }
}
