// ==========================================================
// Project: whfmt.CodeGen
// File: Generator/RustGenerator.cs
// Description: Rust struct + impl From<&[u8]> parser generator from .whfmt definitions.
// Architecture: Emits Rust struct with typed fields, enum for valueMaps, byte-order-aware deserialization.
// ==========================================================

using System.Text;

namespace WhfmtCodeGen.Generator;

internal static class RustGenerator
{
    public static string Generate(
        string formatName, string category, string version, string desc,
        string className,
        List<ParserGenerator.BlockDef> blocks)
    {
        var sb = new StringBuilder();
        string structName = ToRustName(className.Replace("Parser", ""));

        sb.AppendLine($"// Generated by whfmt-codegen from '{formatName}' v{version} [Rust mode]");
        if (!string.IsNullOrEmpty(desc)) sb.AppendLine($"// {desc}");
        sb.AppendLine("// Do not edit — regenerate with: whfmt-codegen generate --lang rust");
        sb.AppendLine();
        sb.AppendLine("use std::convert::TryFrom;");
        sb.AppendLine();

        // Enums for valueMaps
        foreach (var b in blocks)
        {
            if (b.ValueMap.Count < 2) continue;
            string enumName = ToRustName(b.PropertyName) + "Kind";
            sb.AppendLine("#[derive(Debug, Clone, Copy, PartialEq, Eq)]");
            sb.AppendLine($"pub enum {enumName} {{");
            foreach (var kv in b.ValueMap)
                sb.AppendLine($"    {ToRustEnumVariant(kv.Value)},");
            string unknownInner = b.CsTypeSimple == "byte[]" ? "u8" : MapRustType(b.CsTypeSimple);
            sb.AppendLine($"    Unknown({unknownInner}),");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Main struct
        sb.AppendLine("#[derive(Debug, Clone)]");
        sb.AppendLine($"pub struct {structName} {{");
        foreach (var b in blocks)
        {
            if (string.IsNullOrEmpty(b.PropertyName)) continue;
            string fieldName = ToSnakeCase(b.PropertyName);
            string rustType  = b.ValueMap.Count >= 2
                ? ToRustName(b.PropertyName) + "Kind"
                : MapRustType(b.CsTypeSimple);
            sb.AppendLine($"    pub {fieldName}: {rustType},");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // impl TryFrom<&[u8]>
        sb.AppendLine("#[derive(Debug)]");
        sb.AppendLine("pub struct ParseError(pub String);");
        sb.AppendLine();
        sb.AppendLine($"impl TryFrom<&[u8]> for {structName} {{");
        sb.AppendLine("    type Error = ParseError;");
        sb.AppendLine();
        sb.AppendLine($"    fn try_from(data: &[u8]) -> Result<Self, ParseError> {{");

        long maxRequired = blocks.Where(b => !string.IsNullOrEmpty(b.PropertyName))
                                 .Select(b => b.Offset + b.Length).DefaultIfEmpty(0).Max();
        if (maxRequired > 0)
            sb.AppendLine($"        if data.len() < {maxRequired} {{ return Err(ParseError(format!(\"File too short: need {maxRequired} bytes, got {{}}\", data.len()))); }}");
        sb.AppendLine($"        Ok({structName} {{");

        foreach (var b in blocks)
        {
            if (string.IsNullOrEmpty(b.PropertyName)) continue;
            string fieldName = ToSnakeCase(b.PropertyName);
            string rawRead   = ReadRust(b);

            if (b.ValueMap.Count >= 2)
            {
                string enumName = ToRustName(b.PropertyName) + "Kind";
                sb.AppendLine($"            {fieldName}: match {rawRead} {{");
                foreach (var kv in b.ValueMap)
                {
                    if (long.TryParse(kv.Key, out _))
                        sb.AppendLine($"                {kv.Key} => {enumName}::{ToRustEnumVariant(kv.Value)},");
                }
                sb.AppendLine($"                v => {enumName}::Unknown(v),");
                sb.AppendLine("            },");
            }
            else
            {
                sb.AppendLine($"            {fieldName}: {rawRead},");
            }
        }

        sb.AppendLine("        })");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string MapRustType(string csType) => csType switch
    {
        "byte"   => "u8",
        "sbyte"  => "i8",
        "ushort" => "u16",
        "short"  => "i16",
        "uint"   => "u32",
        "int"    => "i32",
        "ulong"  => "u64",
        "long"   => "i64",
        "float"  => "f32",
        "double" => "f64",
        "string" => "String",
        _        => "Vec<u8>",
    };

    private static string ReadRust(ParserGenerator.BlockDef b)
    {
        long off = b.Offset;
        int  len = b.Length;
        bool big = b.Endian == "big";
        string suffix = big ? "be" : "le";

        return b.CsTypeSimple switch
        {
            "byte"   => $"data[{off}]",
            "sbyte"  => $"data[{off}] as i8",
            "ushort" => $"u16::from_{suffix}_bytes(data[{off}..{off + len}].try_into().unwrap())",
            "short"  => $"i16::from_{suffix}_bytes(data[{off}..{off + len}].try_into().unwrap())",
            "uint"   => $"u32::from_{suffix}_bytes(data[{off}..{off + len}].try_into().unwrap())",
            "int"    => $"i32::from_{suffix}_bytes(data[{off}..{off + len}].try_into().unwrap())",
            "ulong"  => $"u64::from_{suffix}_bytes(data[{off}..{off + len}].try_into().unwrap())",
            "long"   => $"i64::from_{suffix}_bytes(data[{off}..{off + len}].try_into().unwrap())",
            "float"  => $"f32::from_{suffix}_bytes(data[{off}..{off + len}].try_into().unwrap())",
            "double" => $"f64::from_{suffix}_bytes(data[{off}..{off + len}].try_into().unwrap())",
            "string" => $"String::from_utf8_lossy(&data[{off}..{off + len}]).trim_end_matches('\\0').to_string()",
            _        => $"data[{off}..{off + len}].to_vec()",
        };
    }

    private static string ToSnakeCase(string s)
    {
        var sb = new StringBuilder();
        foreach (char c in s)
        {
            if (!char.IsLetterOrDigit(c) && c != '_') { if (sb.Length > 0 && sb[^1] != '_') sb.Append('_'); continue; }
            if (char.IsUpper(c) && sb.Length > 0 && sb[^1] != '_') sb.Append('_');
            sb.Append(char.ToLower(c));
        }
        // Trim trailing underscore
        while (sb.Length > 0 && sb[^1] == '_') sb.Length--;
        var result = sb.ToString();
        // Prefix with r# if it's a Rust keyword
        return result is "type" or "match" or "use" or "mod" or "fn" or "let" or "mut" or "impl" or "struct"
            ? "r#" + result : result;
    }

    private static string ToRustName(string s)
    {
        var sb = new StringBuilder();
        bool upper = true;
        foreach (char c in s)
        {
            if (!char.IsLetterOrDigit(c)) { upper = true; continue; }
            sb.Append(upper ? char.ToUpper(c) : c);
            upper = false;
        }
        return sb.ToString();
    }

    private static string ToRustEnumVariant(string label)
    {
        if (string.IsNullOrEmpty(label)) return "Unknown";
        var sb = new StringBuilder();
        bool upper = true;
        foreach (char c in label)
        {
            if (!char.IsLetterOrDigit(c)) { upper = true; continue; }
            sb.Append(upper ? char.ToUpper(c) : c);
            upper = false;
        }
        var r = sb.ToString();
        return r.Length > 0 && char.IsDigit(r[0]) ? "V" + r : r;
    }
}
