// ==========================================================
// Project: whfmt.CodeGen
// File: Generator/SpanGenerator.cs
// Description: Zero-alloc C# Span<byte> parser generator.
// Architecture: Uses ReadOnlySpan<byte> + MemoryMarshal.Read<T> — no heap allocation in hot path.
// ==========================================================

using System.Text;

namespace WhfmtCodeGen.Generator;

internal static class SpanGenerator
{
    public static string Generate(
        string formatName, string category, string version, string desc,
        string namespaceName, string className,
        List<ParserGenerator.BlockDef> blocks,
        List<ParserGenerator.ChecksumDef> checksums,
        bool includeValidation)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"//   Generated by whfmt-codegen from '{formatName}' v{version} [zero-alloc Span<byte> mode]");
        if (!string.IsNullOrEmpty(category)) sb.AppendLine($"//   Category: {category}");
        if (!string.IsNullOrEmpty(desc))     sb.AppendLine($"//   {desc}");
        sb.AppendLine("//   Do not edit — regenerate with: whfmt-codegen generate --lang csharp-span");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Zero-alloc Span-based reader for {formatName} binary data.</summary>");
        sb.AppendLine($"public ref struct {className}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly ReadOnlySpan<byte> _data;");
        sb.AppendLine();
        sb.AppendLine($"    public {className}(ReadOnlySpan<byte> data) => _data = data;");
        sb.AppendLine();

        foreach (var b in blocks)
        {
            if (string.IsNullOrEmpty(b.PropertyName)) continue;
            if (b.Offset + b.Length > int.MaxValue) continue;

            string csType = b.CsTypeSimple;
            if (!string.IsNullOrEmpty(b.Description))
                sb.AppendLine($"    /// <summary>{b.Description.Replace("&", "&amp;").Replace("<", "&lt;")}</summary>");

            if (csType == "byte[]" || csType == "string")
            {
                sb.AppendLine($"    public ReadOnlySpan<byte> {b.PropertyName} => _data.Length >= {b.Offset + b.Length} ? _data.Slice({b.Offset}, {b.Length}) : ReadOnlySpan<byte>.Empty;");
            }
            else if (csType == "byte")
            {
                sb.AppendLine($"    public byte {b.PropertyName} => _data.Length > {b.Offset} ? _data[{b.Offset}] : default;");
            }
            else
            {
                string marshalType = csType switch
                {
                    "ushort" => "ushort", "short" => "short",
                    "uint"   => "uint",   "int"   => "int",
                    "ulong"  => "ulong",  "long"  => "long",
                    "float"  => "float",  "double"=> "double",
                    _        => "uint",
                };
                bool bigEndian = b.Endian == "big";
                sb.AppendLine($"    public {csType} {b.PropertyName}");
                sb.AppendLine("    {");
                sb.AppendLine("        get");
                sb.AppendLine("        {");
                sb.AppendLine($"            if (_data.Length < {b.Offset + b.Length}) return default;");
                sb.AppendLine($"            var result = MemoryMarshal.Read<{marshalType}>(_data.Slice({b.Offset}, {b.Length}));");
                if (bigEndian)
                {
                    sb.AppendLine($"            return ({csType})ReverseBytes(result);");
                }
                else
                {
                    sb.AppendLine($"            return ({csType})result;");
                }
                sb.AppendLine("        }");
                sb.AppendLine("    }");
            }
            sb.AppendLine();
        }

        // Byte-reversal helpers
        sb.AppendLine("    private static ushort ReverseBytes(ushort v) => (ushort)((v << 8) | (v >> 8));");
        sb.AppendLine("    private static uint   ReverseBytes(uint v)   => (v << 24) | ((v & 0xFF00) << 8) | ((v >> 8) & 0xFF00) | (v >> 24);");
        sb.AppendLine("    private static ulong  ReverseBytes(ulong v)  => ((ulong)ReverseBytes((uint)v) << 32) | ReverseBytes((uint)(v >> 32));");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
