//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.Editor.DiffViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiffViewerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiffViewerResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.Editor.DiffViewer.Properties.DiffViewerResources", typeof(DiffViewerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offset.
        /// </summary>
        internal static string Common_ColOffset {
            get {
                return ResourceManager.GetString("Common_ColOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added.
        /// </summary>
        internal static string DiffViewer_Added {
            get {
                return ResourceManager.GetString("DiffViewer_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added: 0.
        /// </summary>
        internal static string DiffViewer_AddedChip {
            get {
                return ResourceManager.GetString("DiffViewer_AddedChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left bytes.
        /// </summary>
        internal static string DiffViewer_ColLeftBytes {
            get {
                return ResourceManager.GetString("DiffViewer_ColLeftBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Length.
        /// </summary>
        internal static string DiffViewer_ColLength {
            get {
                return ResourceManager.GetString("DiffViewer_ColLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right bytes.
        /// </summary>
        internal static string DiffViewer_ColRightBytes {
            get {
                return ResourceManager.GetString("DiffViewer_ColRightBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string DiffViewer_ColType {
            get {
                return ResourceManager.GetString("DiffViewer_ColType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparing….
        /// </summary>
        internal static string DiffViewer_Comparing {
            get {
                return ResourceManager.GetString("DiffViewer_Comparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleted.
        /// </summary>
        internal static string DiffViewer_Deleted {
            get {
                return ResourceManager.GetString("DiffViewer_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleted: 0.
        /// </summary>
        internal static string DiffViewer_DeletedChip {
            get {
                return ResourceManager.GetString("DiffViewer_DeletedChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diff List.
        /// </summary>
        internal static string DiffViewer_DiffList {
            get {
                return ResourceManager.GetString("DiffViewer_DiffList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à — (left).
        /// </summary>
        internal static string DiffViewer_LeftLabel {
            get {
                return ResourceManager.GetString("DiffViewer_LeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modified.
        /// </summary>
        internal static string DiffViewer_Modified {
            get {
                return ResourceManager.GetString("DiffViewer_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modified: 0.
        /// </summary>
        internal static string DiffViewer_ModifiedChip {
            get {
                return ResourceManager.GetString("DiffViewer_ModifiedChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next ►.
        /// </summary>
        internal static string DiffViewer_NextButton {
            get {
                return ResourceManager.GetString("DiffViewer_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next difference (F8).
        /// </summary>
        internal static string DiffViewer_NextDiff {
            get {
                return ResourceManager.GetString("DiffViewer_NextDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open two files via View &gt; Compare Files….
        /// </summary>
        internal static string DiffViewer_OpenFilesHint {
            get {
                return ResourceManager.GetString("DiffViewer_OpenFilesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ◄ Prev.
        /// </summary>
        internal static string DiffViewer_PrevButton {
            get {
                return ResourceManager.GetString("DiffViewer_PrevButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous difference (Shift+F8).
        /// </summary>
        internal static string DiffViewer_PrevDiff {
            get {
                return ResourceManager.GetString("DiffViewer_PrevDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à — (right).
        /// </summary>
        internal static string DiffViewer_RightLabel {
            get {
                return ResourceManager.GetString("DiffViewer_RightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show/hide the diff regions list.
        /// </summary>
        internal static string DiffViewer_ShowHideDiffList {
            get {
                return ResourceManager.GetString("DiffViewer_ShowHideDiffList", resourceCulture);
            }
        }

        internal static string DiffViewer_TabHex {
            get { return ResourceManager.GetString("DiffViewer_TabHex", resourceCulture); }
        }

        internal static string DiffViewer_TabText {
            get { return ResourceManager.GetString("DiffViewer_TabText", resourceCulture); }
        }

        internal static string DiffViewer_ExportPatch {
            get { return ResourceManager.GetString("DiffViewer_ExportPatch", resourceCulture); }
        }

        internal static string DiffViewer_ExportPatchTooltip {
            get { return ResourceManager.GetString("DiffViewer_ExportPatchTooltip", resourceCulture); }
        }

        internal static string DiffViewer_TextModeOnly {
            get { return ResourceManager.GetString("DiffViewer_TextModeOnly", resourceCulture); }
        }

        internal static string DiffViewer_ColLine {
            get { return ResourceManager.GetString("DiffViewer_ColLine", resourceCulture); }
        }

        internal static string DiffViewer_LineEqual {
            get { return ResourceManager.GetString("DiffViewer_LineEqual", resourceCulture); }
        }

        internal static string DiffViewer_LineModified {
            get { return ResourceManager.GetString("DiffViewer_LineModified", resourceCulture); }
        }

        internal static string DiffViewer_LineDeleted {
            get { return ResourceManager.GetString("DiffViewer_LineDeleted", resourceCulture); }
        }

        internal static string DiffViewer_LineInserted {
            get { return ResourceManager.GetString("DiffViewer_LineInserted", resourceCulture); }
        }

        internal static string DiffViewer_NotTextFile {
            get { return ResourceManager.GetString("DiffViewer_NotTextFile", resourceCulture); }
        }

        internal static string DiffViewer_PatchSaved {
            get { return ResourceManager.GetString("DiffViewer_PatchSaved", resourceCulture); }
        }

        internal static string DiffViewer_TabMerge {
            get { return ResourceManager.GetString("DiffViewer_TabMerge", resourceCulture); }
        }

        internal static string DiffViewer_MergeConflicts {
            get { return ResourceManager.GetString("DiffViewer_MergeConflicts", resourceCulture); }
        }

        internal static string DiffViewer_MergeNoConflicts {
            get { return ResourceManager.GetString("DiffViewer_MergeNoConflicts", resourceCulture); }
        }

        internal static string DiffViewer_MergeAcceptOurs {
            get { return ResourceManager.GetString("DiffViewer_MergeAcceptOurs", resourceCulture); }
        }

        internal static string DiffViewer_MergeAcceptTheirs {
            get { return ResourceManager.GetString("DiffViewer_MergeAcceptTheirs", resourceCulture); }
        }

        internal static string DiffViewer_MergeAcceptBoth {
            get { return ResourceManager.GetString("DiffViewer_MergeAcceptBoth", resourceCulture); }
        }

        internal static string DiffViewer_MergeNextConflict {
            get { return ResourceManager.GetString("DiffViewer_MergeNextConflict", resourceCulture); }
        }

        internal static string DiffViewer_MergePrevConflict {
            get { return ResourceManager.GetString("DiffViewer_MergePrevConflict", resourceCulture); }
        }

        internal static string DiffViewer_MergeSave {
            get { return ResourceManager.GetString("DiffViewer_MergeSave", resourceCulture); }
        }

        internal static string DiffViewer_MergeSaveTooltip {
            get { return ResourceManager.GetString("DiffViewer_MergeSaveTooltip", resourceCulture); }
        }

        internal static string DiffViewer_MergeSaved {
            get { return ResourceManager.GetString("DiffViewer_MergeSaved", resourceCulture); }
        }

        internal static string DiffViewer_MergeUnresolvedWarning {
            get { return ResourceManager.GetString("DiffViewer_MergeUnresolvedWarning", resourceCulture); }
        }

        internal static string DiffViewer_MergeBaseLabel {
            get { return ResourceManager.GetString("DiffViewer_MergeBaseLabel", resourceCulture); }
        }

        internal static string DiffViewer_MergeOpenBase {
            get { return ResourceManager.GetString("DiffViewer_MergeOpenBase", resourceCulture); }
        }

        internal static string DiffViewer_MergeOpenBaseTooltip {
            get { return ResourceManager.GetString("DiffViewer_MergeOpenBaseTooltip", resourceCulture); }
        }

        internal static string DiffViewer_MergeNotReady {
            get { return ResourceManager.GetString("DiffViewer_MergeNotReady", resourceCulture); }
        }
    }
}
