// ==========================================================
// Project: WpfHexEditor.Editor.ClassDiagram.Core
// File: CodeGen/Languages/VisualBasic/VBGenerator.cs
// Author: Derek Tremblay (derektremblay666@gmail.com)
// Contributors: Claude Opus 4.7
// Created: 2026-05-08
// Description:
//     ILanguageGenerator implementation that emits Visual Basic
//     source via the Roslyn VB SyntaxFactory. NormalizeWhitespace()
//     produces canonical formatting; an optional banner is prepended
//     for callers that want auto-generated headers.
// ==========================================================

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.VisualBasic;
using Microsoft.CodeAnalysis.VisualBasic.Syntax;
using System.Text;
using WpfHexEditor.Editor.ClassDiagram.Core.CodeGen.Abstractions;
using WpfHexEditor.Editor.ClassDiagram.Core.CodeGen.Model;
using WpfHexEditor.Editor.ClassDiagram.Core.CodeGen.Options;

namespace WpfHexEditor.Editor.ClassDiagram.Core.CodeGen.Languages.VisualBasic;

/// <summary>
/// VB.NET generator backed by Roslyn <see cref="SyntaxFactory"/>. Output is
/// guaranteed to be syntactically valid Visual Basic and idiomatically formatted.
/// </summary>
public sealed class VBGenerator : ILanguageGenerator
{
    /// <inheritdoc/>
    public string LanguageId => LanguageIds.VisualBasic;

    /// <inheritdoc/>
    public string DisplayName => "Visual Basic";

    /// <inheritdoc/>
    public string FileExtension => ".vb";

    /// <inheritdoc/>
    public string Generate(CodeModel model, CodeGenOptions options)
    {
        ArgumentNullException.ThrowIfNull(model);
        ArgumentNullException.ThrowIfNull(options);

        var typesByNamespace = model.Types
            .GroupBy(t => string.IsNullOrEmpty(t.Namespace) ? model.RootNamespace : t.Namespace,
                StringComparer.Ordinal)
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .ToList();

        var compilationUnit = SyntaxFactory.CompilationUnit()
            .WithImports(BuildImports(model.Usings))
            .WithMembers(SyntaxFactory.List(BuildNamespaceMembers(typesByNamespace, options)));

        var rendered = compilationUnit
            .NormalizeWhitespace(indentation: ResolveIndent(options), eol: "\n")
            .ToFullString();

        return PrependPreamble(rendered, options);
    }

    private static SyntaxList<ImportsStatementSyntax> BuildImports(IReadOnlyList<CodeUsing> usings) =>
        usings.Count == 0 ? [] : SyntaxFactory.List(usings.Select(BuildOneImport));

    private static ImportsStatementSyntax BuildOneImport(CodeUsing u)
    {
        var clause = SyntaxFactory.SimpleImportsClause(SyntaxFactory.ParseName(u.Namespace));
        if (!string.IsNullOrEmpty(u.Alias))
        {
            clause = clause.WithAlias(SyntaxFactory.ImportAliasClause(SyntaxFactory.Identifier(u.Alias!)));
        }
        return SyntaxFactory.ImportsStatement(SyntaxFactory.SingletonSeparatedList<ImportsClauseSyntax>(clause));
    }

    private static IEnumerable<StatementSyntax> BuildNamespaceMembers(
        IReadOnlyList<IGrouping<string, CodeType>> typesByNamespace, CodeGenOptions options)
    {
        foreach (var group in typesByNamespace)
        {
            var typeStmts = group.Select(t => VBTypeEmitter.Emit(t, options));
            yield return SyntaxFactory.NamespaceBlock(
                SyntaxFactory.NamespaceStatement(SyntaxFactory.ParseName(group.Key)),
                SyntaxFactory.List(typeStmts),
                SyntaxFactory.EndNamespaceStatement());
        }
    }

    private static string ResolveIndent(CodeGenOptions options) =>
        options.IndentStyle == IndentStyle.Tabs
            ? "\t"
            : new string(' ', Math.Max(1, options.IndentSize));

    private static string PrependPreamble(string body, CodeGenOptions options)
    {
        if (!options.EmitHeader)
            return body;

        var preamble = new StringBuilder();
        preamble.Append("' <auto-generated />\n");
        preamble.Append("' Generated by WpfHexEditor ClassDiagram CodeGen.\n");
        preamble.Append('\n');
        return preamble + body;
    }
}
