//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the end of file. Do you want append one byte ? This operation cannot be canceled if you continue..
        /// </summary>
        public static string AppendByteConfirmationString {
            get {
                return ResourceManager.GetString("AppendByteConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string BookmarksString {
            get {
                return ResourceManager.GetString("BookmarksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte action.
        /// </summary>
        public static string ByteActionString {
            get {
                return ResourceManager.GetString("ByteActionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        public static string BytesTagString {
            get {
                return ResourceManager.GetString("BytesTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        public static string ByteString {
            get {
                return ResourceManager.GetString("ByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel long process.
        /// </summary>
        public static string CancelLongProcessString {
            get {
                return ResourceManager.GetString("CancelLongProcessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to cancel long process..
        /// </summary>
        public static string CancelLongProcessToolTipString {
            get {
                return ResourceManager.GetString("CancelLongProcessToolTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear bookmark.
        /// </summary>
        public static string ClearBookMarkString {
            get {
                return ResourceManager.GetString("ClearBookMarkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearString {
            get {
                return ResourceManager.GetString("ClearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to go to at position..
        /// </summary>
        public static string ClickToGoAtPositionString {
            get {
                return ResourceManager.GetString("ClickToGoAtPositionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseString {
            get {
                return ResourceManager.GetString("CloseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t convert this string to long.
        /// </summary>
        public static string ConvertStringToLongErrorString {
            get {
                return ResourceManager.GetString("ConvertStringToLongErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as ASCII.
        /// </summary>
        public static string CopyAsASCIIString {
            get {
                return ResourceManager.GetString("CopyAsASCIIString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as decimal.
        /// </summary>
        public static string CopyAsDecimalString {
            get {
                return ResourceManager.GetString("CopyAsDecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as hexadecimal.
        /// </summary>
        public static string CopyAsHexadecimalString {
            get {
                return ResourceManager.GetString("CopyAsHexadecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBL string (character file loaded).
        /// </summary>
        public static string CopyAsTBLString {
            get {
                return ResourceManager.GetString("CopyAsTBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selection as ....
        /// </summary>
        public static string CopySelectionAsString {
            get {
                return ResourceManager.GetString("CopySelectionAsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of.
        /// </summary>
        public static string CountOfString {
            get {
                return ResourceManager.GetString("CountOfString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default TBL.
        /// </summary>
        public static string DefaultTBLString {
            get {
                return ResourceManager.GetString("DefaultTBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteString {
            get {
                return ResourceManager.GetString("DeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionString {
            get {
                return ResourceManager.GetString("DescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00=&lt;NUL&gt;
        ///01=&lt;SOH&gt;
        ///02=&lt;STX&gt;
        ///03=&lt;ETX&gt;
        ///04=&lt;PF&gt;
        ///05=&lt;HT&gt;
        ///06=&lt;LC&gt;
        ///07=&lt;DEL&gt;
        ///08=&lt;GE&gt;
        ///09=&lt;RLF&gt;
        ///0A=&lt;SMM&gt;
        ///0B=&lt;VT&gt;
        ///0C=&lt;FF&gt;
        ///0D=&lt;CR&gt;
        ///0E=&lt;SO&gt;
        ///0F=&lt;SI&gt;
        ///10=&lt;DLE&gt;
        ///11=&lt;DC1&gt;
        ///12=&lt;DC2&gt;
        ///13=&lt;TM&gt;
        ///14=&lt;RES&gt;
        ///15=&lt;NL&gt;
        ///16=&lt;BS&gt;
        ///17=&lt;IL&gt;
        ///18=&lt;CAN&gt;
        ///19=&lt;EM&gt;
        ///1A=&lt;CC&gt;
        ///1B=&lt;CU1&gt;
        ///1C=&lt;IFS&gt;
        ///1D=&lt;IGS&gt;
        ///1E=&lt;IRS&gt;
        ///1F=&lt;IUS&gt;
        ///20=&lt;DS&gt;
        ///21=&lt;SOS&gt;
        ///22=&lt;FS&gt;
        ///23=.
        ///24=&lt;BYP&gt;
        ///25=&lt;LF&gt;
        ///26=&lt;ETB&gt;
        ///27=&lt;ESC&gt;
        ///28=.
        ///29=.
        ///2A=&lt;SM&gt;
        ///2B=&lt;CU2&gt;
        ///2C=.
        ///2D=&lt;ENQ&gt;
        ///2E=&lt;ACK&gt;
        ///2F=&lt;BEL&gt;
        ///30=.
        ///31=.
        ///32=&lt;SYN&gt;
        ///33=.
        ///34=&lt;PN&gt;
        ///35=&lt;RS&gt;
        ///36=&lt;UC&gt;
        ///37=&lt;EOT&gt;
        ///38 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EBCDIC {
            get {
                return ResourceManager.GetString("EBCDIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00=.
        ///01=.
        ///02=.
        ///03=.
        ///04=.
        ///05=.
        ///06=.
        ///07=.
        ///08=.
        ///09=.
        ///0A=.
        ///0B=.
        ///0C=.
        ///0D=.
        ///0E=.
        ///0F=.
        ///10=.
        ///11=.
        ///12=.
        ///13=.
        ///14=.
        ///15=.
        ///16=.
        ///17=.
        ///18=.
        ///19=.
        ///1A=.
        ///1B=.
        ///1C=.
        ///1D=.
        ///1E=.
        ///1F=.
        ///20=.
        ///21=.
        ///22=.
        ///23=.
        ///24=.
        ///25=.
        ///26=.
        ///27=.
        ///28=.
        ///29=.
        ///2A=.
        ///2B=.
        ///2C=.
        ///2D=.
        ///2E=.
        ///2F=.
        ///30=.
        ///31=.
        ///32=.
        ///33=.
        ///34=.
        ///35=.
        ///36=.
        ///37=.
        ///38=.
        ///39=.
        ///3A=.
        ///3B=.
        ///3C=.
        ///3D=.
        ///3E=.
        ///3F=.
        ///40=.
        ///41=.
        ///42=.
        ///43=.
        ///44=.
        ///45=.
        ///46=.
        ///47=.
        ///48=.
        ///49=.
        ///4A=¢
        ///4B=.
        ///4C=&lt;
        ///4D=(
        ///4E=+
        ///4F=|
        ///50=&amp;
        ///51=.
        ///52=.
        ///53=.
        ///54=.
        ///55 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EBCDICNoSpecialChar {
            get {
                return ResourceManager.GetString("EBCDICNoSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;end&gt;.
        /// </summary>
        public static string EndTagString {
            get {
                return ResourceManager.GetString("EndTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter hexadecimal value ....
        /// </summary>
        public static string EnterHexValueMsgString {
            get {
                return ResourceManager.GetString("EnterHexValueMsgString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want close the current file and open : .
        /// </summary>
        public static string FileDroppingConfirmationString {
            get {
                return ResourceManager.GetString("FileDroppingConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill selection with byte.
        /// </summary>
        public static string FillSelectionAloneString {
            get {
                return ResourceManager.GetString("FillSelectionAloneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill selection with byte....
        /// </summary>
        public static string FillSelectionString {
            get {
                return ResourceManager.GetString("FillSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find All.
        /// </summary>
        public static string FindAllString {
            get {
                return ResourceManager.GetString("FindAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace.
        /// </summary>
        public static string FindAndReplaceString {
            get {
                return ResourceManager.GetString("FindAndReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte to search.
        /// </summary>
        public static string FindByteString {
            get {
                return ResourceManager.GetString("FindByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find First.
        /// </summary>
        public static string FindFirstString {
            get {
                return ResourceManager.GetString("FindFirstString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Last.
        /// </summary>
        public static string FindLastString {
            get {
                return ResourceManager.GetString("FindLastString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string FindNextString {
            get {
                return ResourceManager.GetString("FindNextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find all occurence of selection.
        /// </summary>
        public static string FindSelectionString {
            get {
                return ResourceManager.GetString("FindSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FindString {
            get {
                return ResourceManager.GetString("FindString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find what:.
        /// </summary>
        public static string FindWhatString {
            get {
                return ResourceManager.GetString("FindWhatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First byte.
        /// </summary>
        public static string FirstByteString {
            get {
                return ResourceManager.GetString("FirstByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        public static string HexString {
            get {
                return ResourceManager.GetString("HexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight all data find.
        /// </summary>
        public static string HighLightSettingString {
            get {
                return ResourceManager.GetString("HighLightSettingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kb.
        /// </summary>
        public static string KBTagString {
            get {
                return ResourceManager.GetString("KBTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string LengthString {
            get {
                return ResourceManager.GetString("LengthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln.
        /// </summary>
        public static string LineStatusBarTagString {
            get {
                return ResourceManager.GetString("LineStatusBarTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ln&gt;.
        /// </summary>
        public static string LineTagString {
            get {
                return ResourceManager.GetString("LineTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        public static string LongString {
            get {
                return ResourceManager.GetString("LongString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mb.
        /// </summary>
        public static string MBTagString {
            get {
                return ResourceManager.GetString("MBTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkString {
            get {
                return ResourceManager.GetString("OkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is locked. Do you want to open it in read-only mode?.
        /// </summary>
        public static string OpenAsReadOnlyString {
            get {
                return ResourceManager.GetString("OpenAsReadOnlyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste operation reached the end of file. Do you want extend the file for complete operation ? This operation cannot be canceled if you continue..
        /// </summary>
        public static string PasteExtendByteConfirmationString {
            get {
                return ResourceManager.GetString("PasteExtendByteConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from clipboard.
        /// </summary>
        public static string PasteFromClipboardString {
            get {
                return ResourceManager.GetString("PasteFromClipboardString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste without inserting.
        /// </summary>
        public static string PasteNotInsertString {
            get {
                return ResourceManager.GetString("PasteNotInsertString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PositionString {
            get {
                return ResourceManager.GetString("PositionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string ReplaceAllString {
            get {
                return ResourceManager.GetString("ReplaceAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace by byte.
        /// </summary>
        public static string ReplaceByByteString {
            get {
                return ResourceManager.GetString("ReplaceByByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Next.
        /// </summary>
        public static string ReplaceNextString {
            get {
                return ResourceManager.GetString("ReplaceNextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace byte in selection....
        /// </summary>
        public static string ReplaceSelectionString {
            get {
                return ResourceManager.GetString("ReplaceSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string ReplaceString {
            get {
                return ResourceManager.GetString("ReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim the data on the find length when replace.
        /// </summary>
        public static string ReplaceTrimSettingString {
            get {
                return ResourceManager.GetString("ReplaceTrimSettingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with byte.
        /// </summary>
        public static string ReplaceWithByteString {
            get {
                return ResourceManager.GetString("ReplaceWithByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        public static string ReplaceWithString {
            get {
                return ResourceManager.GetString("ReplaceWithString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAllString {
            get {
                return ResourceManager.GetString("SelectAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set bookmark.
        /// </summary>
        public static string SetBookMarkString {
            get {
                return ResourceManager.GetString("SetBookMarkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBL.
        /// </summary>
        public static string TBLString {
            get {
                return ResourceManager.GetString("TBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This string are not hex.
        /// </summary>
        public static string ThisStringAreNotHexString {
            get {
                return ResourceManager.GetString("ThisStringAreNotHexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UndoString {
            get {
                return ResourceManager.GetString("UndoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ValueString {
            get {
                return ResourceManager.GetString("ValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error is occurs when writing..
        /// </summary>
        public static string WritingErrorExeptionString {
            get {
                return ResourceManager.GetString("WritingErrorExeptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset zoom to 100%.
        /// </summary>
        public static string ZoomResetString {
            get {
                return ResourceManager.GetString("ZoomResetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string ZoomString {
            get {
                return ResourceManager.GetString("ZoomString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy as C# Code.
        /// </summary>
        public static string CopyAsCSharpCodeString {
            get {
                return ResourceManager.GetString("CopyAsCSharpCodeString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy as C Code.
        /// </summary>
        public static string CopyAsCCodeString {
            get {
                return ResourceManager.GetString("CopyAsCCodeString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string PasteString {
            get {
                return ResourceManager.GetString("PasteString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fill with Byte....
        /// </summary>
        public static string FillWithByteString {
            get {
                return ResourceManager.GetString("FillWithByteString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace Byte....
        /// </summary>
        public static string ReplaceByteMenuString {
            get {
                return ResourceManager.GetString("ReplaceByteMenuString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reverse Selection.
        /// </summary>
        public static string ReverseSelectionString {
            get {
                return ResourceManager.GetString("ReverseSelectionString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status Message.
        /// </summary>
        public static string StatusMessageString {
            get {
                return ResourceManager.GetString("StatusMessageString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        public static string FileSizeString {
            get {
                return ResourceManager.GetString("FileSizeString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selection Info.
        /// </summary>
        public static string SelectionInfoString {
            get {
                return ResourceManager.GetString("SelectionInfoString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Mode.
        /// </summary>
        public static string EditModeString {
            get {
                return ResourceManager.GetString("EditModeString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bytes Per Line.
        /// </summary>
        public static string BytesPerLineString {
            get {
                return ResourceManager.GetString("BytesPerLineString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh Time.
        /// </summary>
        public static string RefreshTimeString {
            get {
                return ResourceManager.GetString("RefreshTimeString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string OffsetString {
            get {
                return ResourceManager.GetString("OffsetString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ReadyString {
            get {
                return ResourceManager.GetString("ReadyString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No selection.
        /// </summary>
        public static string NoSelectionString {
            get {
                return ResourceManager.GetString("NoSelectionString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mode: Overwrite.
        /// </summary>
        public static string ModeOverwriteString {
            get {
                return ResourceManager.GetString("ModeOverwriteString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Case sensitive.
        /// </summary>
        public static string CaseSensitiveCheckbox {
            get {
                return ResourceManager.GetString("CaseSensitiveCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseDialogButton {
            get {
                return ResourceManager.GetString("CloseDialogButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close search (Esc).
        /// </summary>
        public static string CloseSearchTooltip {
            get {
                return ResourceManager.GetString("CloseSearchTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy Selection.
        /// </summary>
        public static string CopySelectionString {
            get {
                return ResourceManager.GetString("CopySelectionString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current match.
        /// </summary>
        public static string CurrentMatchLabel {
            get {
                return ResourceManager.GetString("CurrentMatchLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cut Selection.
        /// </summary>
        public static string CutSelectionString {
            get {
                return ResourceManager.GetString("CutSelectionString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Byte.
        /// </summary>
        public static string DeleteByteString {
            get {
                return ResourceManager.GetString("DeleteByteString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Selection.
        /// </summary>
        public static string DeleteSelectionString {
            get {
                return ResourceManager.GetString("DeleteSelectionString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find All.
        /// </summary>
        public static string FindAllButton {
            get {
                return ResourceManager.GetString("FindAllButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find and Replace.
        /// </summary>
        public static string FindAndReplaceDialogTitle {
            get {
                return ResourceManager.GetString("FindAndReplaceDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FindGroupHeader {
            get {
                return ResourceManager.GetString("FindGroupHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string FindNextButton {
            get {
                return ResourceManager.GetString("FindNextButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string FindPreviousButton {
            get {
                return ResourceManager.GetString("FindPreviousButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find:.
        /// </summary>
        public static string FindTextLabel {
            get {
                return ResourceManager.GetString("FindTextLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Go to Offset....
        /// </summary>
        public static string GoToOffsetString {
            get {
                return ResourceManager.GetString("GoToOffsetString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        public static string HexModeLabel {
            get {
                return ResourceManager.GetString("HexModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Highlight all matches.
        /// </summary>
        public static string HighlightAllCheckbox {
            get {
                return ResourceManager.GetString("HighlightAllCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert Byte....
        /// </summary>
        public static string InsertByteString {
            get {
                return ResourceManager.GetString("InsertByteString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        public static string MatchCaseLabel {
            get {
                return ResourceManager.GetString("MatchCaseLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} matches found.
        /// </summary>
        public static string MatchesFoundFormat {
            get {
                return ResourceManager.GetString("MatchesFoundFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next match (F3).
        /// </summary>
        public static string NextMatchTooltip {
            get {
                return ResourceManager.GetString("NextMatchTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous match (Shift+F3).
        /// </summary>
        public static string PreviousMatchTooltip {
            get {
                return ResourceManager.GetString("PreviousMatchTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PropertiesString {
            get {
                return ResourceManager.GetString("PropertiesString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick search (Ctrl+F).
        /// </summary>
        public static string QuickSearchTooltip {
            get {
                return ResourceManager.GetString("QuickSearchTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        public static string RegexModeLabel {
            get {
                return ResourceManager.GetString("RegexModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string ReplaceAllButton {
            get {
                return ResourceManager.GetString("ReplaceAllButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string ReplaceButton {
            get {
                return ResourceManager.GetString("ReplaceButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string ReplaceGroupHeader {
            get {
                return ResourceManager.GetString("ReplaceGroupHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        public static string ReplaceTextLabel {
            get {
                return ResourceManager.GetString("ReplaceTextLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} replaced.
        /// </summary>
        public static string ReplacedFormat {
            get {
                return ResourceManager.GetString("ReplacedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ResultsGroupHeader {
            get {
                return ResourceManager.GetString("ResultsGroupHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find:.
        /// </summary>
        public static string SearchFindLabel {
            get {
                return ResourceManager.GetString("SearchFindLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search in selection only.
        /// </summary>
        public static string SearchInSelectionCheckbox {
            get {
                return ResourceManager.GetString("SearchInSelectionCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter search text....
        /// </summary>
        public static string SearchModePlaceholder {
            get {
                return ResourceManager.GetString("SearchModePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No matches found.
        /// </summary>
        public static string SearchNoMatchesString {
            get {
                return ResourceManager.GetString("SearchNoMatchesString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string SearchOptionsLabel {
            get {
                return ResourceManager.GetString("SearchOptionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search options.
        /// </summary>
        public static string SearchOptionsTooltip {
            get {
                return ResourceManager.GetString("SearchOptionsTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchPanelTitle {
            get {
                return ResourceManager.GetString("SearchPanelTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string SearchResultsLabel {
            get {
                return ResourceManager.GetString("SearchResultsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string StatusCancelling {
            get {
                return ResourceManager.GetString("StatusCancelling", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} matches in {1}ms.
        /// </summary>
        public static string StatusFoundMatchesFormat {
            get {
                return ResourceManager.GetString("StatusFoundMatchesFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} matches in {1}ms ({2:F2} MB/s).
        /// </summary>
        public static string StatusFoundMatchesWithSpeedFormat {
            get {
                return ResourceManager.GetString("StatusFoundMatchesWithSpeedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression.
        /// </summary>
        public static string StatusInvalidRegex {
            get {
                return ResourceManager.GetString("StatusInvalidRegex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid replacement pattern.
        /// </summary>
        public static string StatusInvalidReplacementPattern {
            get {
                return ResourceManager.GetString("StatusInvalidReplacementPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid search pattern.
        /// </summary>
        public static string StatusInvalidSearchPattern {
            get {
                return ResourceManager.GetString("StatusInvalidSearchPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Match found at position 0x{0:X8}.
        /// </summary>
        public static string StatusMatchFoundAtFormat {
            get {
                return ResourceManager.GetString("StatusMatchFoundAtFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Match found at position 0x{0:X8} (wrapped).
        /// </summary>
        public static string StatusMatchFoundAtWrappedFormat {
            get {
                return ResourceManager.GetString("StatusMatchFoundAtWrappedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Match {0} of {1} at position 0x{2:X8}.
        /// </summary>
        public static string StatusMatchOfTotalFormat {
            get {
                return ResourceManager.GetString("StatusMatchOfTotalFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No matches to replace.
        /// </summary>
        public static string StatusNoMatchesToReplace {
            get {
                return ResourceManager.GetString("StatusNoMatchesToReplace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No more bookmarks after current position.
        /// </summary>
        public static string StatusNoMoreBookmarksAfter {
            get {
                return ResourceManager.GetString("StatusNoMoreBookmarksAfter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No more bookmarks before current position.
        /// </summary>
        public static string StatusNoMoreBookmarksBefore {
            get {
                return ResourceManager.GetString("StatusNoMoreBookmarksBefore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No more matches found.
        /// </summary>
        public static string StatusNoMoreMatches {
            get {
                return ResourceManager.GetString("StatusNoMoreMatches", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No previous matches found.
        /// </summary>
        public static string StatusNoPreviousMatches {
            get {
                return ResourceManager.GetString("StatusNoPreviousMatches", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reached end of file.
        /// </summary>
        public static string StatusReachedEndOfFile {
            get {
                return ResourceManager.GetString("StatusReachedEndOfFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reached start of file.
        /// </summary>
        public static string StatusReachedStartOfFile {
            get {
                return ResourceManager.GetString("StatusReachedStartOfFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace all error: {0}.
        /// </summary>
        public static string StatusReplaceAllError {
            get {
                return ResourceManager.GetString("StatusReplaceAllError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace cancelled.
        /// </summary>
        public static string StatusReplaceCancelled {
            get {
                return ResourceManager.GetString("StatusReplaceCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace complete.
        /// </summary>
        public static string StatusReplaceComplete {
            get {
                return ResourceManager.GetString("StatusReplaceComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace error: {0}.
        /// </summary>
        public static string StatusReplaceError {
            get {
                return ResourceManager.GetString("StatusReplaceError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replaced at position 0x{0:X8} (Total: {1}).
        /// </summary>
        public static string StatusReplacedAtFormat {
            get {
                return ResourceManager.GetString("StatusReplacedAtFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replaced {0} occurrences.
        /// </summary>
        public static string StatusReplacedFormat {
            get {
                return ResourceManager.GetString("StatusReplacedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replaced {0} occurrence(s). Total replacements: {1}.
        /// </summary>
        public static string StatusReplacedOccurrencesFormat {
            get {
                return ResourceManager.GetString("StatusReplacedOccurrencesFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replacing....
        /// </summary>
        public static string StatusReplacing {
            get {
                return ResourceManager.GetString("StatusReplacing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search cancelled.
        /// </summary>
        public static string StatusSearchCancelled {
            get {
                return ResourceManager.GetString("StatusSearchCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search complete.
        /// </summary>
        public static string StatusSearchComplete {
            get {
                return ResourceManager.GetString("StatusSearchComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string StatusSearching {
            get {
                return ResourceManager.GetString("StatusSearching", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextModeLabel {
            get {
                return ResourceManager.GetString("TextModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total matches.
        /// </summary>
        public static string TotalMatchesLabel {
            get {
                return ResourceManager.GetString("TotalMatchesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use regular expressions.
        /// </summary>
        public static string UseRegexCheckbox {
            get {
                return ResourceManager.GetString("UseRegexCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Whole word.
        /// </summary>
        public static string WholeWordCheckbox {
            get {
                return ResourceManager.GetString("WholeWordCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Whole word.
        /// </summary>
        public static string WholeWordLabel {
            get {
                return ResourceManager.GetString("WholeWordLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wildcard.
        /// </summary>
        public static string WildcardModeLabel {
            get {
                return ResourceManager.GetString("WildcardModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ProgressButtonCancel {
            get {
                return ResourceManager.GetString("ProgressButtonCancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File opened successfully.
        /// </summary>
        public static string ProgressMessageFileOpenedSuccessfully {
            get {
                return ResourceManager.GetString("ProgressMessageFileOpenedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File saved successfully.
        /// </summary>
        public static string ProgressMessageFileSavedSuccessfully {
            get {
                return ResourceManager.GetString("ProgressMessageFileSavedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Finding matches....
        /// </summary>
        public static string ProgressMessageFindingMatches {
            get {
                return ResourceManager.GetString("ProgressMessageFindingMatches", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} matches.
        /// </summary>
        public static string ProgressMessageFoundMatchesFormat {
            get {
                return ResourceManager.GetString("ProgressMessageFoundMatchesFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading file data....
        /// </summary>
        public static string ProgressMessageLoadingFileData {
            get {
                return ResourceManager.GetString("ProgressMessageLoadingFileData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opening file stream....
        /// </summary>
        public static string ProgressMessageOpeningFileStream {
            get {
                return ResourceManager.GetString("ProgressMessageOpeningFileStream", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preparing to save....
        /// </summary>
        public static string ProgressMessagePreparingToSave {
            get {
                return ResourceManager.GetString("ProgressMessagePreparingToSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replaced {0} occurrences.
        /// </summary>
        public static string ProgressMessageReplacedFormat {
            get {
                return ResourceManager.GetString("ProgressMessageReplacedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} matches. Replacing....
        /// </summary>
        public static string ProgressMessageReplacingFormat {
            get {
                return ResourceManager.GetString("ProgressMessageReplacingFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searching... {0} found.
        /// </summary>
        public static string ProgressMessageSearchingFoundFormat {
            get {
                return ResourceManager.GetString("ProgressMessageSearchingFoundFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting search....
        /// </summary>
        public static string ProgressMessageStartingSearch {
            get {
                return ResourceManager.GetString("ProgressMessageStartingSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opening file.
        /// </summary>
        public static string ProgressTitleOpeningFile {
            get {
                return ResourceManager.GetString("ProgressTitleOpeningFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replacing.
        /// </summary>
        public static string ProgressTitleReplacing {
            get {
                return ResourceManager.GetString("ProgressTitleReplacing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saving file.
        /// </summary>
        public static string ProgressTitleSavingFile {
            get {
                return ResourceManager.GetString("ProgressTitleSavingFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searching.
        /// </summary>
        public static string ProgressTitleSearching {
            get {
                return ResourceManager.GetString("ProgressTitleSearching", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relative Search....
        /// </summary>
        public static string RelativeSearchMenuString {
            get {
                return ResourceManager.GetString("RelativeSearchMenuString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relative Search - Encoding Discovery.
        /// </summary>
        public static string RelativeSearchString {
            get {
                return ResourceManager.GetString("RelativeSearchString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Known Text:.
        /// </summary>
        public static string RelativeSearchKnownTextString {
            get {
                return ResourceManager.GetString("RelativeSearchKnownTextString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string RelativeSearchSearchButtonString {
            get {
                return ResourceManager.GetString("RelativeSearchSearchButtonString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use parallel search.
        /// </summary>
        public static string RelativeSearchUseParallelString {
            get {
                return ResourceManager.GetString("RelativeSearchUseParallelString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Min matches:.
        /// </summary>
        public static string RelativeSearchMinMatchesString {
            get {
                return ResourceManager.GetString("RelativeSearchMinMatchesString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max proposals:.
        /// </summary>
        public static string RelativeSearchMaxProposalsString {
            get {
                return ResourceManager.GetString("RelativeSearchMaxProposalsString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TBL loaded: {0} entries (will be used for validation).
        /// </summary>
        public static string RelativeSearchTblLoadedString {
            get {
                return ResourceManager.GetString("RelativeSearchTblLoadedString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No TBL loaded (proposals scored independently).
        /// </summary>
        public static string RelativeSearchNoTblString {
            get {
                return ResourceManager.GetString("RelativeSearchNoTblString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encoding Proposals.
        /// </summary>
        public static string RelativeSearchProposalsHeaderString {
            get {
                return ResourceManager.GetString("RelativeSearchProposalsHeaderString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string RelativeSearchOffsetColumnString {
            get {
                return ResourceManager.GetString("RelativeSearchOffsetColumnString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string RelativeSearchScoreColumnString {
            get {
                return ResourceManager.GetString("RelativeSearchScoreColumnString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string RelativeSearchMatchesColumnString {
            get {
                return ResourceManager.GetString("RelativeSearchMatchesColumnString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sample Text.
        /// </summary>
        public static string RelativeSearchSampleColumnString {
            get {
                return ResourceManager.GetString("RelativeSearchSampleColumnString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview (Decoded Text).
        /// </summary>
        public static string RelativeSearchPreviewHeaderString {
            get {
                return ResourceManager.GetString("RelativeSearchPreviewHeaderString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export to TBL.
        /// </summary>
        public static string RelativeSearchExportTblString {
            get {
                return ResourceManager.GetString("RelativeSearchExportTblString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Navigate to Match.
        /// </summary>
        public static string RelativeSearchNavigateString {
            get {
                return ResourceManager.GetString("RelativeSearchNavigateString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searching 256 encoding offsets....
        /// </summary>
        public static string RelativeSearchSearchingString {
            get {
                return ResourceManager.GetString("RelativeSearchSearchingString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} proposals in {1}ms.
        /// </summary>
        public static string RelativeSearchFoundProposalsString {
            get {
                return ResourceManager.GetString("RelativeSearchFoundProposalsString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} proposals in {1}ms (top match validated by loaded TBL!).
        /// </summary>
        public static string RelativeSearchFoundWithValidationString {
            get {
                return ResourceManager.GetString("RelativeSearchFoundWithValidationString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searching 256 offsets (validating against {0} TBL entries)....
        /// </summary>
        public static string RelativeSearchSearchingWithTblString {
            get {
                return ResourceManager.GetString("RelativeSearchSearchingWithTblString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search cancelled.
        /// </summary>
        public static string RelativeSearchCancelledString {
            get {
                return ResourceManager.GetString("RelativeSearchCancelledString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No encoding proposals found. Try different search text..
        /// </summary>
        public static string RelativeSearchNoProposalsString {
            get {
                return ResourceManager.GetString("RelativeSearchNoProposalsString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No file is open.
        /// </summary>
        public static string RelativeSearchNoFileOpenString {
            get {
                return ResourceManager.GetString("RelativeSearchNoFileOpenString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter text you know appears in the ROM (e.g., "World", "Start", "Hero").
        /// </summary>
        public static string RelativeSearchKnownTextTooltipString {
            get {
                return ResourceManager.GetString("RelativeSearchKnownTextTooltipString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save the selected encoding proposal as a TBL file.
        /// </summary>
        public static string RelativeSearchExportTooltipString {
            get {
                return ResourceManager.GetString("RelativeSearchExportTooltipString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        public static string BarChart_NoData {
            get {
                return ResourceManager.GetString("BarChart_NoData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string BarChart_Total {
            get {
                return ResourceManager.GetString("BarChart_Total", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string BarChart_Max {
            get {
                return ResourceManager.GetString("BarChart_Max", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entropy.
        /// </summary>
        public static string BarChart_Entropy {
            get {
                return ResourceManager.GetString("BarChart_Entropy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string BarChart_Bytes {
            get {
                return ResourceManager.GetString("BarChart_Bytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to bits/byte.
        /// </summary>
        public static string BarChart_BitsPerByte {
            get {
                return ResourceManager.GetString("BarChart_BitsPerByte", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scroll Markers.
        /// </summary>
        public static string HexSettings_ScrollMarkers_Title {
            get {
                return ResourceManager.GetString("HexSettings_ScrollMarkers_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Bookmark Markers.
        /// </summary>
        public static string HexSettings_ShowBookmarkMarkers {
            get {
                return ResourceManager.GetString("HexSettings_ShowBookmarkMarkers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Modified Byte Markers.
        /// </summary>
        public static string HexSettings_ShowModifiedMarkers {
            get {
                return ResourceManager.GetString("HexSettings_ShowModifiedMarkers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Inserted Byte Markers.
        /// </summary>
        public static string HexSettings_ShowInsertedMarkers {
            get {
                return ResourceManager.GetString("HexSettings_ShowInsertedMarkers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Deleted Byte Markers.
        /// </summary>
        public static string HexSettings_ShowDeletedMarkers {
            get {
                return ResourceManager.GetString("HexSettings_ShowDeletedMarkers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Search Result Markers.
        /// </summary>
        public static string HexSettings_ShowSearchResultMarkers {
            get {
                return ResourceManager.GetString("HexSettings_ShowSearchResultMarkers", resourceCulture);
            }
        }
    }
}
