// ==========================================================
// Project: WpfHexEditor.PluginHost
// File: DevTools/PluginTemplateScaffolder.cs
// Description:
//     Generates the on-disk skeleton of a new WpfHexEditor plugin from
//     a single name. Writes manifest.json, the .csproj, a sample
//     IWpfHexEditorPlugin implementation, and a README.
//     Pragmatic implementation — no T4 templating, just string interpolation
//     so the scaffolder has zero external dependencies.
// ==========================================================

using System.IO;

namespace WpfHexEditor.PluginHost.DevTools;

/// <summary>Result of a scaffold operation.</summary>
public sealed record ScaffoldResult(string PluginDirectory, bool Success, string? Error = null);

/// <summary>Creates a new plugin project on disk.</summary>
public sealed class PluginTemplateScaffolder
{
    public ScaffoldResult Create(string baseDirectory, string pluginName, string? authorName = null)
    {
        if (string.IsNullOrWhiteSpace(pluginName))
            return new ScaffoldResult("", false, "Plugin name is required.");

        var id      = SanitizeId(pluginName);
        var folder  = Path.Combine(baseDirectory, id);
        if (Directory.Exists(folder))
            return new ScaffoldResult(folder, false, $"Folder '{folder}' already exists.");

        try
        {
            Directory.CreateDirectory(folder);
            File.WriteAllText(Path.Combine(folder, "manifest.json"),     BuildManifest(id, pluginName, authorName));
            File.WriteAllText(Path.Combine(folder, $"{id}.csproj"),       BuildCsproj(id));
            File.WriteAllText(Path.Combine(folder, $"{id}Plugin.cs"),     BuildPluginClass(id, pluginName));
            File.WriteAllText(Path.Combine(folder, "README.md"),          BuildReadme(pluginName));
            return new ScaffoldResult(folder, true);
        }
        catch (Exception ex)
        {
            return new ScaffoldResult(folder, false, ex.Message);
        }
    }

    private static string SanitizeId(string raw)
    {
        var sb = new System.Text.StringBuilder(raw.Length);
        foreach (var ch in raw) if (char.IsLetterOrDigit(ch) || ch == '_') sb.Append(ch);
        if (sb.Length == 0 || char.IsDigit(sb[0])) sb.Insert(0, "Plugin");
        return sb.ToString();
    }

    private static string BuildManifest(string id, string name, string? author) => $$"""
    {
      "id":          "WpfHexEditor.Plugins.{{id}}",
      "name":        "{{name}}",
      "version":     "0.1.0",
      "author":      "{{author ?? "Anonymous"}}",
      "description": "Generated by WpfHexEditor plugin scaffolder.",
      "entryAssembly": "{{id}}.dll",
      "entryType":   "WpfHexEditor.Plugins.{{id}}.{{id}}Plugin",
      "dependencies": [],
      "loadPriority": 100,
      "features":     []
    }
    """;

    private static string BuildCsproj(string id) => $$"""
    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <RootNamespace>WpfHexEditor.Plugins.{{id}}</RootNamespace>
        <AssemblyName>{{id}}</AssemblyName>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      </PropertyGroup>
      <ItemGroup>
        <!-- Reference WpfHexEditor.SDK from the IDE installation. -->
        <Reference Include="WpfHexEditor.SDK">
          <HintPath>$(WpfHexEditorSdkPath)\WpfHexEditor.SDK.dll</HintPath>
          <Private>false</Private>
        </Reference>
      </ItemGroup>
    </Project>
    """;

    private static string BuildPluginClass(string id, string name) => $$"""
    using WpfHexEditor.SDK;
    using WpfHexEditor.SDK.Contracts;

    namespace WpfHexEditor.Plugins.{{id}};

    /// <summary>{{name}} — generated plugin entry point.</summary>
    public sealed class {{id}}Plugin : IWpfHexEditorPlugin
    {
        public string Id           => "WpfHexEditor.Plugins.{{id}}";
        public string Name         => "{{name}}";
        public string Version      => "0.1.0";
        public string Description  => "Generated by WpfHexEditor plugin scaffolder.";

        public Task InitializeAsync(IIDEHostContext context, CancellationToken ct = default)
        {
            context.Output.Write("{{id}}", "Hello from {{name}}!");
            return Task.CompletedTask;
        }

        public Task ShutdownAsync(CancellationToken ct = default) => Task.CompletedTask;
    }
    """;

    private static string BuildReadme(string name) => $$"""
    # {{name}}

    Generated by the WpfHexEditor plugin scaffolder.

    ## Build

    ```
    dotnet build
    ```

    ## Package as .whxplugin

    Run the IDE terminal command `whexa plugin pack` from this folder.

    ## Install locally

    Copy the produced `{{name}}.whxplugin` (a ZIP) into
    `%AppData%\WpfHexEditor\Plugins\` and reload the IDE.
    """;
}
