//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.App.Debug.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DebuggerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebuggerResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.App.Debug.Properties.DebuggerResources", typeof(DebuggerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        internal static string DBG_ActionsLabel {
            get {
                return ResourceManager.GetString("DBG_ActionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à + Add a condition.
        /// </summary>
        internal static string DBG_AddCondition {
            get {
                return ResourceManager.GetString("DBG_AddCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Watch.
        /// </summary>
        internal static string DBG_AddWatch {
            get {
                return ResourceManager.GetString("DBG_AddWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Breakpoint Settings.
        /// </summary>
        internal static string DBG_BreakpointSettings {
            get {
                return ResourceManager.GetString("DBG_BreakpointSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string DBG_CloseButton {
            get {
                return ResourceManager.GetString("DBG_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        internal static string DBG_ColFile {
            get {
                return ResourceManager.GetString("DBG_ColFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string DBG_ColName {
            get {
                return ResourceManager.GetString("DBG_ColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string DBG_ColType {
            get {
                return ResourceManager.GetString("DBG_ColType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value.
        /// </summary>
        internal static string DBG_ColValue {
            get {
                return ResourceManager.GetString("DBG_ColValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Condition.
        /// </summary>
        internal static string DBG_ConditionColumn {
            get {
                return ResourceManager.GetString("DBG_ConditionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Condition.
        /// </summary>
        internal static string DBG_ConditionField {
            get {
                return ResourceManager.GetString("DBG_ConditionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conditions.
        /// </summary>
        internal static string DBG_ConditionsLabel {
            get {
                return ResourceManager.GetString("DBG_ConditionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration:.
        /// </summary>
        internal static string DBG_ConfigLabel {
            get {
                return ResourceManager.GetString("DBG_ConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue code execution.
        /// </summary>
        internal static string DBG_ContinueExecution {
            get {
                return ResourceManager.GetString("DBG_ContinueExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy Location.
        /// </summary>
        internal static string DBG_CopyLocationMenu {
            get {
                return ResourceManager.GetString("DBG_CopyLocationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete All.
        /// </summary>
        internal static string DBG_DeleteAll {
            get {
                return ResourceManager.GetString("DBG_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete all breakpoints.
        /// </summary>
        internal static string DBG_DeleteAllTooltip {
            get {
                return ResourceManager.GetString("DBG_DeleteAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Group.
        /// </summary>
        internal static string DBG_DeleteGroupMenu {
            get {
                return ResourceManager.GetString("DBG_DeleteGroupMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string DBG_DeleteMenu {
            get {
                return ResourceManager.GetString("DBG_DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string DBG_DeleteText {
            get {
                return ResourceManager.GetString("DBG_DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detail: Bottom.
        /// </summary>
        internal static string DBG_DetailBottom {
            get {
                return ResourceManager.GetString("DBG_DetailBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detail: Hidden.
        /// </summary>
        internal static string DBG_DetailHidden {
            get {
                return ResourceManager.GetString("DBG_DetailHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detail: Right.
        /// </summary>
        internal static string DBG_DetailRight {
            get {
                return ResourceManager.GetString("DBG_DetailRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable All.
        /// </summary>
        internal static string DBG_DisableAll {
            get {
                return ResourceManager.GetString("DBG_DisableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable all breakpoints.
        /// </summary>
        internal static string DBG_DisableAllTooltip {
            get {
                return ResourceManager.GetString("DBG_DisableAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Group.
        /// </summary>
        internal static string DBG_DisableGroupMenu {
            get {
                return ResourceManager.GetString("DBG_DisableGroupMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable breakpoint once hit.
        /// </summary>
        internal static string DBG_DisableOnHit {
            get {
                return ResourceManager.GetString("DBG_DisableOnHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit Condition….
        /// </summary>
        internal static string DBG_EditCondition {
            get {
                return ResourceManager.GetString("DBG_EditCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit Condition….
        /// </summary>
        internal static string DBG_EditConditionMenu {
            get {
                return ResourceManager.GetString("DBG_EditConditionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit condition of selected breakpoint.
        /// </summary>
        internal static string DBG_EditConditionTooltip {
            get {
                return ResourceManager.GetString("DBG_EditConditionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit in IDE.
        /// </summary>
        internal static string DBG_EditInIde {
            get {
                return ResourceManager.GetString("DBG_EditInIde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open this .whdbg file in the main CodeEditor for full JSON editing.
        /// </summary>
        internal static string DBG_EditInIdeTooltip {
            get {
                return ResourceManager.GetString("DBG_EditInIdeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit….
        /// </summary>
        internal static string DBG_EditText {
            get {
                return ResourceManager.GetString("DBG_EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable All.
        /// </summary>
        internal static string DBG_EnableAll {
            get {
                return ResourceManager.GetString("DBG_EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable all breakpoints.
        /// </summary>
        internal static string DBG_EnableAllTooltip {
            get {
                return ResourceManager.GetString("DBG_EnableAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled.
        /// </summary>
        internal static string DBG_EnabledField {
            get {
                return ResourceManager.GetString("DBG_EnabledField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable Group.
        /// </summary>
        internal static string DBG_EnableGroupMenu {
            get {
                return ResourceManager.GetString("DBG_EnableGroupMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export All to VS XML….
        /// </summary>
        internal static string DBG_ExportBreakpoints {
            get {
                return ResourceManager.GetString("DBG_ExportBreakpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export all breakpoints to Visual Studio XML file.
        /// </summary>
        internal static string DBG_ExportTooltip {
            get {
                return ResourceManager.GetString("DBG_ExportTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Source.
        /// </summary>
        internal static string DBG_GoToSourceMenu {
            get {
                return ResourceManager.GetString("DBG_GoToSourceMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go To Source.
        /// </summary>
        internal static string DBG_GoToSourceText {
            get {
                return ResourceManager.GetString("DBG_GoToSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled/Disabled.
        /// </summary>
        internal static string DBG_GroupEnabled {
            get {
                return ResourceManager.GetString("DBG_GroupEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        internal static string DBG_GroupFile {
            get {
                return ResourceManager.GetString("DBG_GroupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group:.
        /// </summary>
        internal static string DBG_GroupLabel {
            get {
                return ResourceManager.GetString("DBG_GroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string DBG_GroupNone {
            get {
                return ResourceManager.GetString("DBG_GroupNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project.
        /// </summary>
        internal static string DBG_GroupProject {
            get {
                return ResourceManager.GetString("DBG_GroupProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string DBG_GroupType {
            get {
                return ResourceManager.GetString("DBG_GroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hits.
        /// </summary>
        internal static string DBG_HitsColumn {
            get {
                return ResourceManager.GetString("DBG_HitsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hits: .
        /// </summary>
        internal static string DBG_HitsLabel {
            get {
                return ResourceManager.GetString("DBG_HitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import from VS XML….
        /// </summary>
        internal static string DBG_ImportBreakpoints {
            get {
                return ResourceManager.GetString("DBG_ImportBreakpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import breakpoints from Visual Studio XML file.
        /// </summary>
        internal static string DBG_ImportTooltip {
            get {
                return ResourceManager.GetString("DBG_ImportTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch.
        /// </summary>
        internal static string DBG_LaunchButton {
            get {
                return ResourceManager.GetString("DBG_LaunchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Debug Launch Configurations.
        /// </summary>
        internal static string DBG_LaunchConfigTitle {
            get {
                return ResourceManager.GetString("DBG_LaunchConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click Open to load a .whdbg file, select a configuration, then click Launch. Use Edit in IDE to edit the JSON with full syntax highlighting and schema validation..
        /// </summary>
        internal static string DBG_LaunchHint {
            get {
                return ResourceManager.GetString("DBG_LaunchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch selected configuration (F5).
        /// </summary>
        internal static string DBG_LaunchTooltip {
            get {
                return ResourceManager.GetString("DBG_LaunchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detail panel layout.
        /// </summary>
        internal static string DBG_LayoutTooltip {
            get {
                return ResourceManager.GetString("DBG_LayoutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location.
        /// </summary>
        internal static string DBG_LocationColumn {
            get {
                return ResourceManager.GetString("DBG_LocationColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use $FUNCTION for method name, {expression} for values, $ADDRESS, $CALLER.
        /// </summary>
        internal static string DBG_LogHint {
            get {
                return ResourceManager.GetString("DBG_LogHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log a message to Output window:.
        /// </summary>
        internal static string DBG_LogMessage {
            get {
                return ResourceManager.GetString("DBG_LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à More options.
        /// </summary>
        internal static string DBG_MoreOptionsTooltip {
            get {
                return ResourceManager.GetString("DBG_MoreOptionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No file open — click Open to load a .whdbg configuration..
        /// </summary>
        internal static string DBG_NoFileOpen {
            get {
                return ResourceManager.GetString("DBG_NoFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only enable when following breakpoint is hit:.
        /// </summary>
        internal static string DBG_OnlyWhen {
            get {
                return ResourceManager.GetString("DBG_OnlyWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        internal static string DBG_OpenButton {
            get {
                return ResourceManager.GetString("DBG_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open .whdbg file.
        /// </summary>
        internal static string DBG_OpenWhdbgTooltip {
            get {
                return ResourceManager.GetString("DBG_OpenWhdbgTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each box represents a thread call stack.
        /// </summary>
        internal static string DBG_ParallelStacksHint {
            get {
                return ResourceManager.GetString("DBG_ParallelStacksHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh parallel stacks.
        /// </summary>
        internal static string DBG_ParallelStacksRefreshTooltip {
            get {
                return ResourceManager.GetString("DBG_ParallelStacksRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        internal static string DBG_ResetButton {
            get {
                return ResourceManager.GetString("DBG_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string DBG_SaveButton {
            get {
                return ResourceManager.GetString("DBG_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save launch configuration.
        /// </summary>
        internal static string DBG_SaveTooltip {
            get {
                return ResourceManager.GetString("DBG_SaveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search breakpoints....
        /// </summary>
        internal static string DBG_SearchPlaceholder {
            get {
                return ResourceManager.GetString("DBG_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh thread list.
        /// </summary>
        internal static string DBG_ThreadsRefreshTooltip {
            get {
                return ResourceManager.GetString("DBG_ThreadsRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Enabled.
        /// </summary>
        internal static string DBG_ToggleEnabledMenu {
            get {
                return ResourceManager.GetString("DBG_ToggleEnabledMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string DBG_TypeField {
            get {
                return ResourceManager.GetString("DBG_TypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unverified.
        /// </summary>
        internal static string DBG_UnverifiedBadge {
            get {
                return ResourceManager.GetString("DBG_UnverifiedBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This breakpoint could not be verified at the current location..
        /// </summary>
        internal static string DBG_UnverifiedTooltip {
            get {
                return ResourceManager.GetString("DBG_UnverifiedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verified.
        /// </summary>
        internal static string DBG_VerifiedField {
            get {
                return ResourceManager.GetString("DBG_VerifiedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autos.
        /// </summary>
        internal static string Debugger_AutosPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_AutosPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Breakpoints.
        /// </summary>
        internal static string Debugger_BreakpointsPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_BreakpointsPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call Stack.
        /// </summary>
        internal static string Debugger_CallStackPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_CallStackPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Debug Console.
        /// </summary>
        internal static string Debugger_ConsolePanelTitle {
            get {
                return ResourceManager.GetString("Debugger_ConsolePanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disassembly.
        /// </summary>
        internal static string Debugger_DisassemblyPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_DisassemblyPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exception Settings.
        /// </summary>
        internal static string Debugger_ExceptionsPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_ExceptionsPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Breakpoints to VS XML.
        /// </summary>
        internal static string Debugger_ExportBreakpoints {
            get {
                return ResourceManager.GetString("Debugger_ExportBreakpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Immediate.
        /// </summary>
        internal static string Debugger_ImmediatePanelTitle {
            get {
                return ResourceManager.GetString("Debugger_ImmediatePanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Breakpoints from VS XML.
        /// </summary>
        internal static string Debugger_ImportBreakpoints {
            get {
                return ResourceManager.GetString("Debugger_ImportBreakpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch Config (.whdbg).
        /// </summary>
        internal static string Debugger_LaunchConfigTitle {
            get {
                return ResourceManager.GetString("Debugger_LaunchConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Locals.
        /// </summary>
        internal static string Debugger_LocalsPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_LocalsPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Memory.
        /// </summary>
        internal static string Debugger_MemoryPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_MemoryPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Continue.
        /// </summary>
        internal static string Debugger_Menu_Continue {
            get {
                return ResourceManager.GetString("Debugger_Menu_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Step _Into.
        /// </summary>
        internal static string Debugger_Menu_StepInto {
            get {
                return ResourceManager.GetString("Debugger_Menu_StepInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Step _Over.
        /// </summary>
        internal static string Debugger_Menu_StepOver {
            get {
                return ResourceManager.GetString("Debugger_Menu_StepOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modules.
        /// </summary>
        internal static string Debugger_ModulesPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_ModulesPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No configuration loaded..
        /// </summary>
        internal static string Debugger_NoConfigLoaded {
            get {
                return ResourceManager.GetString("Debugger_NoConfigLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No &apos;configurations&apos; array found in .whdbg file..
        /// </summary>
        internal static string Debugger_NoConfigsArray {
            get {
                return ResourceManager.GetString("Debugger_NoConfigsArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No file loaded. Click Open first..
        /// </summary>
        internal static string Debugger_NoFileLoaded {
            get {
                return ResourceManager.GetString("Debugger_NoFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No matching configuration found..
        /// </summary>
        internal static string Debugger_NoMatchingConfig {
            get {
                return ResourceManager.GetString("Debugger_NoMatchingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No valid breakpoints found in the file..
        /// </summary>
        internal static string Debugger_NoValidBreakpoints {
            get {
                return ResourceManager.GetString("Debugger_NoValidBreakpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parallel Stacks.
        /// </summary>
        internal static string Debugger_ParallelStacksPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_ParallelStacksPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parallel Watch.
        /// </summary>
        internal static string Debugger_ParallelWatchPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_ParallelWatchPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registers.
        /// </summary>
        internal static string Debugger_RegistersPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_RegistersPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IDebuggerService not available..
        /// </summary>
        internal static string Debugger_ServiceNotAvailable {
            get {
                return ResourceManager.GetString("Debugger_ServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tasks.
        /// </summary>
        internal static string Debugger_TasksPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_TasksPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Threads.
        /// </summary>
        internal static string Debugger_ThreadsPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_ThreadsPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Watch.
        /// </summary>
        internal static string Debugger_WatchPanelTitle {
            get {
                return ResourceManager.GetString("Debugger_WatchPanelTitle", resourceCulture);
            }
        }
    }
}
