//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.Sample.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.Sample.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Byte Shift Left:.
        /// </summary>
        public static string HexSettings_Advanced_ByteShift {
            get {
                return ResourceManager.GetString("HexSettings_Advanced_ByteShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Byte Shift Left:.
        /// </summary>
        public static string HexSettings_Advanced_ByteShiftLeft {
            get {
                return ResourceManager.GetString("HexSettings_Advanced_ByteShiftLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ⚙️ Advanced Options.
        /// </summary>
        public static string HexSettings_Advanced_Header {
            get {
                return ResourceManager.GetString("HexSettings_Advanced_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load Saved State.
        /// </summary>
        public static string HexSettings_Advanced_LoadState {
            get {
                return ResourceManager.GetString("HexSettings_Advanced_LoadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Current State.
        /// </summary>
        public static string HexSettings_Advanced_SaveState {
            get {
                return ResourceManager.GetString("HexSettings_Advanced_SaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ⚙️ Advanced Options.
        /// </summary>
        public static string HexSettings_Advanced_Title {
            get {
                return ResourceManager.GetString("HexSettings_Advanced_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔄 Reset All to Defaults.
        /// </summary>
        public static string HexSettings_Button_Reset {
            get {
                return ResourceManager.GetString("HexSettings_Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Byte Array.
        /// </summary>
        public static string HexSettings_Clipboard_ByteArray {
            get {
                return ResourceManager.GetString("HexSettings_Clipboard_ByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C Code.
        /// </summary>
        public static string HexSettings_Clipboard_CCode {
            get {
                return ResourceManager.GetString("HexSettings_Clipboard_CCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C# Code.
        /// </summary>
        public static string HexSettings_Clipboard_CSharpCode {
            get {
                return ResourceManager.GetString("HexSettings_Clipboard_CSharpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Copy Mode:.
        /// </summary>
        public static string HexSettings_Clipboard_DefaultCopyMode {
            get {
                return ResourceManager.GetString("HexSettings_Clipboard_DefaultCopyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📋 Clipboard Options.
        /// </summary>
        public static string HexSettings_Clipboard_Header {
            get {
                return ResourceManager.GetString("HexSettings_Clipboard_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hex String.
        /// </summary>
        public static string HexSettings_Clipboard_HexString {
            get {
                return ResourceManager.GetString("HexSettings_Clipboard_HexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Java Code.
        /// </summary>
        public static string HexSettings_Clipboard_JavaCode {
            get {
                return ResourceManager.GetString("HexSettings_Clipboard_JavaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📋 Clipboard Options.
        /// </summary>
        public static string HexSettings_Clipboard_Title {
            get {
                return ResourceManager.GetString("HexSettings_Clipboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VB Code.
        /// </summary>
        public static string HexSettings_Clipboard_VBCode {
            get {
                return ResourceManager.GetString("HexSettings_Clipboard_VBCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bytes Per Line:.
        /// </summary>
        public static string HexSettings_Display_BytesPerLine {
            get {
                return ResourceManager.GetString("HexSettings_Display_BytesPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Byte Tooltip.
        /// </summary>
        public static string HexSettings_Display_ByteTooltip {
            get {
                return ResourceManager.GetString("HexSettings_Display_ByteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📺 Display Options.
        /// </summary>
        public static string HexSettings_Display_Header {
            get {
                return ResourceManager.GetString("HexSettings_Display_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hide Deleted Bytes.
        /// </summary>
        public static string HexSettings_Display_HideDeleted {
            get {
                return ResourceManager.GetString("HexSettings_Display_HideDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Line Numbers (placeholder).
        /// </summary>
        public static string HexSettings_Display_LineNumbers {
            get {
                return ResourceManager.GetString("HexSettings_Display_LineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This feature is not yet available in V2.
        /// </summary>
        public static string HexSettings_Display_LineNumbers_Tooltip {
            get {
                return ResourceManager.GetString("HexSettings_Display_LineNumbers_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Byte Tooltip.
        /// </summary>
        public static string HexSettings_Display_ShowByteTooltip {
            get {
                return ResourceManager.GetString("HexSettings_Display_ShowByteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Line Numbers (placeholder).
        /// </summary>
        public static string HexSettings_Display_ShowLineNumbers {
            get {
                return ResourceManager.GetString("HexSettings_Display_ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This feature is not yet available in V2.
        /// </summary>
        public static string HexSettings_Display_ShowLineNumbers_ToolTip {
            get {
                return ResourceManager.GetString("HexSettings_Display_ShowLineNumbers_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📺 Display Options.
        /// </summary>
        public static string HexSettings_Display_Title {
            get {
                return ResourceManager.GetString("HexSettings_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom Scale:.
        /// </summary>
        public static string HexSettings_Display_ZoomScale {
            get {
                return ResourceManager.GetString("HexSettings_Display_ZoomScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow File Drop.
        /// </summary>
        public static string HexSettings_DragDrop_AllowFileDrop {
            get {
                return ResourceManager.GetString("HexSettings_DragDrop_AllowFileDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow Text Drop.
        /// </summary>
        public static string HexSettings_DragDrop_AllowTextDrop {
            get {
                return ResourceManager.GetString("HexSettings_DragDrop_AllowTextDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File Dropping Confirmation.
        /// </summary>
        public static string HexSettings_DragDrop_FileConfirmation {
            get {
                return ResourceManager.GetString("HexSettings_DragDrop_FileConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow File Drop.
        /// </summary>
        public static string HexSettings_DragDrop_FileDrop {
            get {
                return ResourceManager.GetString("HexSettings_DragDrop_FileDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File Dropping Confirmation.
        /// </summary>
        public static string HexSettings_DragDrop_FileDropConfirmation {
            get {
                return ResourceManager.GetString("HexSettings_DragDrop_FileDropConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📎 Drag &amp; Drop Options.
        /// </summary>
        public static string HexSettings_DragDrop_Header {
            get {
                return ResourceManager.GetString("HexSettings_DragDrop_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow Text Drop.
        /// </summary>
        public static string HexSettings_DragDrop_TextDrop {
            get {
                return ResourceManager.GetString("HexSettings_DragDrop_TextDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📎 Drag &amp; Drop Options.
        /// </summary>
        public static string HexSettings_DragDrop_Title {
            get {
                return ResourceManager.GetString("HexSettings_DragDrop_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow Delete Byte.
        /// </summary>
        public static string HexSettings_Editing_AllowDeleteByte {
            get {
                return ResourceManager.GetString("HexSettings_Editing_AllowDeleteByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow Extend File.
        /// </summary>
        public static string HexSettings_Editing_AllowExtendFile {
            get {
                return ResourceManager.GetString("HexSettings_Editing_AllowExtendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow Insert Anywhere.
        /// </summary>
        public static string HexSettings_Editing_AllowInsertAnywhere {
            get {
                return ResourceManager.GetString("HexSettings_Editing_AllowInsertAnywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Append Needs Confirmation.
        /// </summary>
        public static string HexSettings_Editing_AppendConfirmation {
            get {
                return ResourceManager.GetString("HexSettings_Editing_AppendConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Append Needs Confirmation.
        /// </summary>
        public static string HexSettings_Editing_AppendNeedsConfirmation {
            get {
                return ResourceManager.GetString("HexSettings_Editing_AppendNeedsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caret Mode:.
        /// </summary>
        public static string HexSettings_Editing_CaretMode {
            get {
                return ResourceManager.GetString("HexSettings_Editing_CaretMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow Delete Byte.
        /// </summary>
        public static string HexSettings_Editing_DeleteByte {
            get {
                return ResourceManager.GetString("HexSettings_Editing_DeleteByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Mode:.
        /// </summary>
        public static string HexSettings_Editing_EditMode {
            get {
                return ResourceManager.GetString("HexSettings_Editing_EditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow Extend File.
        /// </summary>
        public static string HexSettings_Editing_ExtendFile {
            get {
                return ResourceManager.GetString("HexSettings_Editing_ExtendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ✏️ Editing Options.
        /// </summary>
        public static string HexSettings_Editing_Header {
            get {
                return ResourceManager.GetString("HexSettings_Editing_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert.
        /// </summary>
        public static string HexSettings_Editing_Insert {
            get {
                return ResourceManager.GetString("HexSettings_Editing_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow Insert Anywhere.
        /// </summary>
        public static string HexSettings_Editing_InsertAnywhere {
            get {
                return ResourceManager.GetString("HexSettings_Editing_InsertAnywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overwrite.
        /// </summary>
        public static string HexSettings_Editing_Overwrite {
            get {
                return ResourceManager.GetString("HexSettings_Editing_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read Only Mode.
        /// </summary>
        public static string HexSettings_Editing_ReadOnly {
            get {
                return ResourceManager.GetString("HexSettings_Editing_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ✏️ Editing Options.
        /// </summary>
        public static string HexSettings_Editing_Title {
            get {
                return ResourceManager.GetString("HexSettings_Editing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEX EDITOR SETTINGS.
        /// </summary>
        public static string HexSettings_Header {
            get {
                return ResourceManager.GetString("HexSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow Marker Click Navigation.
        /// </summary>
        public static string HexSettings_Highlight_AllowMarkerClick {
            get {
                return ResourceManager.GetString("HexSettings_Highlight_AllowMarkerClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto-Highlight Selection Byte.
        /// </summary>
        public static string HexSettings_Highlight_AutoHighlight {
            get {
                return ResourceManager.GetString("HexSettings_Highlight_AutoHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto-Highlight Color:.
        /// </summary>
        public static string HexSettings_Highlight_AutoHighlightColor {
            get {
                return ResourceManager.GetString("HexSettings_Highlight_AutoHighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto-Select Same Byte (Double-Click).
        /// </summary>
        public static string HexSettings_Highlight_AutoSelect {
            get {
                return ResourceManager.GetString("HexSettings_Highlight_AutoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto-Select Same Byte (Double-Click).
        /// </summary>
        public static string HexSettings_Highlight_AutoSelectDoubleClick {
            get {
                return ResourceManager.GetString("HexSettings_Highlight_AutoSelectDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto-Highlight Color:.
        /// </summary>
        public static string HexSettings_Highlight_Color {
            get {
                return ResourceManager.GetString("HexSettings_Highlight_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🎨 Highlight &amp; Selection.
        /// </summary>
        public static string HexSettings_Highlight_Header {
            get {
                return ResourceManager.GetString("HexSettings_Highlight_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow Marker Click Navigation.
        /// </summary>
        public static string HexSettings_Highlight_MarkerNavigation {
            get {
                return ResourceManager.GetString("HexSettings_Highlight_MarkerNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🎨 Highlight &amp; Selection.
        /// </summary>
        public static string HexSettings_Highlight_Title {
            get {
                return ResourceManager.GetString("HexSettings_Highlight_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔄 Reset All to Defaults.
        /// </summary>
        public static string HexSettings_ResetButton {
            get {
                return ResourceManager.GetString("HexSettings_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable Parallel Search.
        /// </summary>
        public static string HexSettings_Search_EnableParallel {
            get {
                return ResourceManager.GetString("HexSettings_Search_EnableParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔍 Search Options.
        /// </summary>
        public static string HexSettings_Search_Header {
            get {
                return ResourceManager.GetString("HexSettings_Search_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Highlight All Matches.
        /// </summary>
        public static string HexSettings_Search_HighlightMatches {
            get {
                return ResourceManager.GetString("HexSettings_Search_HighlightMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable Parallel Search.
        /// </summary>
        public static string HexSettings_Search_ParallelSearch {
            get {
                return ResourceManager.GetString("HexSettings_Search_ParallelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Result Limit:.
        /// </summary>
        public static string HexSettings_Search_ResultLimit {
            get {
                return ResourceManager.GetString("HexSettings_Search_ResultLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔍 Search Options.
        /// </summary>
        public static string HexSettings_Search_Title {
            get {
                return ResourceManager.GetString("HexSettings_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use Wildcard Search (??).
        /// </summary>
        public static string HexSettings_Search_UseWildcard {
            get {
                return ResourceManager.GetString("HexSettings_Search_UseWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use Wildcard Search (??).
        /// </summary>
        public static string HexSettings_Search_WildcardSearch {
            get {
                return ResourceManager.GetString("HexSettings_Search_WildcardSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow Byte Count.
        /// </summary>
        public static string HexSettings_Statistics_AllowByteCount {
            get {
                return ResourceManager.GetString("HexSettings_Statistics_AllowByteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow Byte Count.
        /// </summary>
        public static string HexSettings_Statistics_ByteCount {
            get {
                return ResourceManager.GetString("HexSettings_Statistics_ByteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📊 Statistics.
        /// </summary>
        public static string HexSettings_Statistics_Header {
            get {
                return ResourceManager.GetString("HexSettings_Statistics_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📊 Statistics.
        /// </summary>
        public static string HexSettings_Statistics_Title {
            get {
                return ResourceManager.GetString("HexSettings_Statistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HEX EDITOR SETTINGS.
        /// </summary>
        public static string HexSettings_Title {
            get {
                return ResourceManager.GetString("HexSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string Menu_File_Close {
            get {
                return ResourceManager.GetString("Menu_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save As....
        /// </summary>
        public static string Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("Menu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Message_ErrorTitle {
            get {
                return ResourceManager.GetString("Message_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to open file: {0}.
        /// </summary>
        public static string Message_FileOpenError {
            get {
                return ResourceManager.GetString("Message_FileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to save file: {0}.
        /// </summary>
        public static string Message_FileSaveError {
            get {
                return ResourceManager.GetString("Message_FileSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language changed to {0}.
        ///
        ///Please restart the application to apply the new language.
        ///
        ///(Stop debugging and press F5 again).
        /// </summary>
        public static string Message_LanguageChanged_Text {
            get {
                return ResourceManager.GetString("Message_LanguageChanged_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language Changed - Restart Required.
        /// </summary>
        public static string Message_LanguageChanged_Title {
            get {
                return ResourceManager.GetString("Message_LanguageChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language is already set to {0}..
        /// </summary>
        public static string Message_LanguageUnchanged_Text {
            get {
                return ResourceManager.GetString("Message_LanguageUnchanged_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language Unchanged.
        /// </summary>
        public static string Message_LanguageUnchanged_Title {
            get {
                return ResourceManager.GetString("Message_LanguageUnchanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a language before clicking OK..
        /// </summary>
        public static string Message_NoLanguageSelected_Text {
            get {
                return ResourceManager.GetString("Message_NoLanguageSelected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Language Selected.
        /// </summary>
        public static string Message_NoLanguageSelected_Title {
            get {
                return ResourceManager.GetString("Message_NoLanguageSelected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Appearance.
        /// </summary>
        public static string Options_AppearanceTab {
            get {
                return ResourceManager.GetString("Options_AppearanceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Options_Button_Cancel {
            get {
                return ResourceManager.GetString("Options_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string Options_Button_OK {
            get {
                return ResourceManager.GetString("Options_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coming soon....
        /// </summary>
        public static string Options_ComingSoon {
            get {
                return ResourceManager.GetString("Options_ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure your hex editor preferences.
        /// </summary>
        public static string Options_Header_Subtitle {
            get {
                return ResourceManager.GetString("Options_Header_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ⚙️ Application Options.
        /// </summary>
        public static string Options_Header_Title {
            get {
                return ResourceManager.GetString("Options_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string Options_Language_ColumnCode {
            get {
                return ResourceManager.GetString("Options_Language_ColumnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Options_Language_ColumnLanguage {
            get {
                return ResourceManager.GetString("Options_Language_ColumnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Native Name.
        /// </summary>
        public static string Options_Language_ColumnNativeName {
            get {
                return ResourceManager.GetString("Options_Language_ColumnNativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Language.
        /// </summary>
        public static string Options_Language_CurrentLabel {
            get {
                return ResourceManager.GetString("Options_Language_CurrentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Language.
        /// </summary>
        public static string Options_Language_CurrentLanguage {
            get {
                return ResourceManager.GetString("Options_Language_CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your preferred display language:.
        /// </summary>
        public static string Options_Language_Instructions {
            get {
                return ResourceManager.GetString("Options_Language_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string Options_Language_ListView_Header_Code {
            get {
                return ResourceManager.GetString("Options_Language_ListView_Header_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Options_Language_ListView_Header_Language {
            get {
                return ResourceManager.GetString("Options_Language_ListView_Header_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Native Name.
        /// </summary>
        public static string Options_Language_ListView_Header_NativeName {
            get {
                return ResourceManager.GetString("Options_Language_ListView_Header_NativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please restart the application after changing the language..
        /// </summary>
        public static string Options_Language_RestartWarning {
            get {
                return ResourceManager.GetString("Options_Language_RestartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please restart the application after changing the language..
        /// </summary>
        public static string Options_Language_Warning {
            get {
                return ResourceManager.GetString("Options_Language_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Options_LanguageTab {
            get {
                return ResourceManager.GetString("Options_LanguageTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance.
        /// </summary>
        public static string Options_PerformanceTab {
            get {
                return ResourceManager.GetString("Options_PerformanceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Appearance.
        /// </summary>
        public static string Options_Tab_Appearance {
            get {
                return ResourceManager.GetString("Options_Tab_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Options_Tab_Language {
            get {
                return ResourceManager.GetString("Options_Tab_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance.
        /// </summary>
        public static string Options_Tab_Performance {
            get {
                return ResourceManager.GetString("Options_Tab_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        public static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redo.
        /// </summary>
        public static string QAT_Redo_Label {
            get {
                return ResourceManager.GetString("QAT_Redo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redo (Ctrl+Y).
        /// </summary>
        public static string QAT_Redo_Tooltip {
            get {
                return ResourceManager.GetString("QAT_Redo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string QAT_Save_Label {
            get {
                return ResourceManager.GetString("QAT_Save_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save (Ctrl+S).
        /// </summary>
        public static string QAT_Save_Tooltip {
            get {
                return ResourceManager.GetString("QAT_Save_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undo.
        /// </summary>
        public static string QAT_Undo_Label {
            get {
                return ResourceManager.GetString("QAT_Undo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undo (Ctrl+Z).
        /// </summary>
        public static string QAT_Undo_Tooltip {
            get {
                return ResourceManager.GetString("QAT_Undo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced.
        /// </summary>
        public static string Ribbon_Data_Advanced_Group {
            get {
                return ResourceManager.GetString("Ribbon_Data_Advanced_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Byte Count.
        /// </summary>
        public static string Ribbon_Data_ByteCount {
            get {
                return ResourceManager.GetString("Ribbon_Data_ByteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Checksum.
        /// </summary>
        public static string Ribbon_Data_Checksum {
            get {
                return ResourceManager.GetString("Ribbon_Data_Checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compare.
        /// </summary>
        public static string Ribbon_Data_Compare_Group {
            get {
                return ResourceManager.GetString("Ribbon_Data_Compare_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compare Files.
        /// </summary>
        public static string Ribbon_Data_CompareFiles {
            get {
                return ResourceManager.GetString("Ribbon_Data_CompareFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entropy.
        /// </summary>
        public static string Ribbon_Data_Entropy {
            get {
                return ResourceManager.GetString("Ribbon_Data_Entropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export.
        /// </summary>
        public static string Ribbon_Data_Export {
            get {
                return ResourceManager.GetString("Ribbon_Data_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export.
        /// </summary>
        public static string Ribbon_Data_Export_Group {
            get {
                return ResourceManager.GetString("Ribbon_Data_Export_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export As.
        /// </summary>
        public static string Ribbon_Data_ExportAs {
            get {
                return ResourceManager.GetString("Ribbon_Data_ExportAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C Code.
        /// </summary>
        public static string Ribbon_Data_ExportAs_CCode {
            get {
                return ResourceManager.GetString("Ribbon_Data_ExportAs_CCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C# Byte Array.
        /// </summary>
        public static string Ribbon_Data_ExportAs_CSharpByteArray {
            get {
                return ResourceManager.GetString("Ribbon_Data_ExportAs_CSharpByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hex String.
        /// </summary>
        public static string Ribbon_Data_ExportAs_HexString {
            get {
                return ResourceManager.GetString("Ribbon_Data_ExportAs_HexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Java Code.
        /// </summary>
        public static string Ribbon_Data_ExportAs_JavaCode {
            get {
                return ResourceManager.GetString("Ribbon_Data_ExportAs_JavaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hash (MD5/SHA).
        /// </summary>
        public static string Ribbon_Data_Hash {
            get {
                return ResourceManager.GetString("Ribbon_Data_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statistics.
        /// </summary>
        public static string Ribbon_Data_Statistics {
            get {
                return ResourceManager.GetString("Ribbon_Data_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statistics.
        /// </summary>
        public static string Ribbon_Data_Statistics_Group {
            get {
                return ResourceManager.GetString("Ribbon_Data_Statistics_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data.
        /// </summary>
        public static string Ribbon_Data_Tab {
            get {
                return ResourceManager.GetString("Ribbon_Data_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bookmarks.
        /// </summary>
        public static string Ribbon_Edit_Bookmarks {
            get {
                return ResourceManager.GetString("Ribbon_Edit_Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Byte.
        /// </summary>
        public static string Ribbon_Edit_DeleteByte {
            get {
                return ResourceManager.GetString("Ribbon_Edit_DeleteByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fill Selection.
        /// </summary>
        public static string Ribbon_Edit_FillSelection {
            get {
                return ResourceManager.GetString("Ribbon_Edit_FillSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find.
        /// </summary>
        public static string Ribbon_Edit_Find {
            get {
                return ResourceManager.GetString("Ribbon_Edit_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find.
        /// </summary>
        public static string Ribbon_Edit_Find_Group {
            get {
                return ResourceManager.GetString("Ribbon_Edit_Find_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go To.
        /// </summary>
        public static string Ribbon_Edit_GoTo {
            get {
                return ResourceManager.GetString("Ribbon_Edit_GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert.
        /// </summary>
        public static string Ribbon_Edit_Insert {
            get {
                return ResourceManager.GetString("Ribbon_Edit_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Byte.
        /// </summary>
        public static string Ribbon_Edit_InsertByte {
            get {
                return ResourceManager.GetString("Ribbon_Edit_InsertByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mode.
        /// </summary>
        public static string Ribbon_Edit_Mode_Group {
            get {
                return ResourceManager.GetString("Ribbon_Edit_Mode_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify.
        /// </summary>
        public static string Ribbon_Edit_Modify_Group {
            get {
                return ResourceManager.GetString("Ribbon_Edit_Modify_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Navigate.
        /// </summary>
        public static string Ribbon_Edit_Navigate_Group {
            get {
                return ResourceManager.GetString("Ribbon_Edit_Navigate_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overwrite.
        /// </summary>
        public static string Ribbon_Edit_Overwrite {
            get {
                return ResourceManager.GetString("Ribbon_Edit_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read Only.
        /// </summary>
        public static string Ribbon_Edit_ReadOnly {
            get {
                return ResourceManager.GetString("Ribbon_Edit_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string Ribbon_Edit_Tab {
            get {
                return ResourceManager.GetString("Ribbon_Edit_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 16 Bytes/Line.
        /// </summary>
        public static string Ribbon_Home_16BytesPerLine {
            get {
                return ResourceManager.GetString("Ribbon_Home_16BytesPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string Ribbon_Home_Clear {
            get {
                return ResourceManager.GetString("Ribbon_Home_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clipboard.
        /// </summary>
        public static string Ribbon_Home_Clipboard_Group {
            get {
                return ResourceManager.GetString("Ribbon_Home_Clipboard_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy.
        /// </summary>
        public static string Ribbon_Home_Copy {
            get {
                return ResourceManager.GetString("Ribbon_Home_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cut.
        /// </summary>
        public static string Ribbon_Home_Cut {
            get {
                return ResourceManager.GetString("Ribbon_Home_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display.
        /// </summary>
        public static string Ribbon_Home_Display_Group {
            get {
                return ResourceManager.GetString("Ribbon_Home_Display_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string Ribbon_Home_Edit_Group {
            get {
                return ResourceManager.GetString("Ribbon_Home_Edit_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste.
        /// </summary>
        public static string Ribbon_Home_Paste {
            get {
                return ResourceManager.GetString("Ribbon_Home_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redo.
        /// </summary>
        public static string Ribbon_Home_Redo {
            get {
                return ResourceManager.GetString("Ribbon_Home_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select All.
        /// </summary>
        public static string Ribbon_Home_SelectAll {
            get {
                return ResourceManager.GetString("Ribbon_Home_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selection.
        /// </summary>
        public static string Ribbon_Home_Selection_Group {
            get {
                return ResourceManager.GetString("Ribbon_Home_Selection_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string Ribbon_Home_Tab {
            get {
                return ResourceManager.GetString("Ribbon_Home_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undo.
        /// </summary>
        public static string Ribbon_Home_Undo {
            get {
                return ResourceManager.GetString("Ribbon_Home_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string Ribbon_Tools_About {
            get {
                return ResourceManager.GetString("Ribbon_Tools_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentation.
        /// </summary>
        public static string Ribbon_Tools_Documentation {
            get {
                return ResourceManager.GetString("Ribbon_Tools_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        public static string Ribbon_Tools_Help_Group {
            get {
                return ResourceManager.GetString("Ribbon_Tools_Help_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Ribbon_Tools_Language {
            get {
                return ResourceManager.GetString("Ribbon_Tools_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Ribbon_Tools_Language_Group {
            get {
                return ResourceManager.GetString("Ribbon_Tools_Language_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change application display language.
        /// </summary>
        public static string Ribbon_Tools_Language_Tooltip {
            get {
                return ResourceManager.GetString("Ribbon_Tools_Language_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        public static string Ribbon_Tools_Options_Group {
            get {
                return ResourceManager.GetString("Ribbon_Tools_Options_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string Ribbon_Tools_Settings {
            get {
                return ResourceManager.GetString("Ribbon_Tools_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tools.
        /// </summary>
        public static string Ribbon_Tools_Tab {
            get {
                return ResourceManager.GetString("Ribbon_Tools_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display Options.
        /// </summary>
        public static string Ribbon_View_DisplayOptions_Group {
            get {
                return ResourceManager.GetString("Ribbon_View_DisplayOptions_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hide Deleted.
        /// </summary>
        public static string Ribbon_View_HideDeleted {
            get {
                return ResourceManager.GetString("Ribbon_View_HideDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Highlight Matches.
        /// </summary>
        public static string Ribbon_View_HighlightMatches {
            get {
                return ResourceManager.GetString("Ribbon_View_HighlightMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panels.
        /// </summary>
        public static string Ribbon_View_Panels_Group {
            get {
                return ResourceManager.GetString("Ribbon_View_Panels_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Theme.
        /// </summary>
        public static string Ribbon_View_SelectTheme {
            get {
                return ResourceManager.GetString("Ribbon_View_SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings Panel.
        /// </summary>
        public static string Ribbon_View_SettingsPanel {
            get {
                return ResourceManager.GetString("Ribbon_View_SettingsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Tooltip.
        /// </summary>
        public static string Ribbon_View_ShowTooltip {
            get {
                return ResourceManager.GetString("Ribbon_View_ShowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View.
        /// </summary>
        public static string Ribbon_View_Tab {
            get {
                return ResourceManager.GetString("Ribbon_View_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dark Glass.
        /// </summary>
        public static string Ribbon_View_Theme_DarkGlass {
            get {
                return ResourceManager.GetString("Ribbon_View_Theme_DarkGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimal.
        /// </summary>
        public static string Ribbon_View_Theme_Minimal {
            get {
                return ResourceManager.GetString("Ribbon_View_Theme_Minimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Office (Light).
        /// </summary>
        public static string Ribbon_View_Theme_Office {
            get {
                return ResourceManager.GetString("Ribbon_View_Theme_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visual Studio.
        /// </summary>
        public static string Ribbon_View_Theme_VisualStudio {
            get {
                return ResourceManager.GetString("Ribbon_View_Theme_VisualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Themes.
        /// </summary>
        public static string Ribbon_View_Themes_Group {
            get {
                return ResourceManager.GetString("Ribbon_View_Themes_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom.
        /// </summary>
        public static string Ribbon_View_Zoom_Group {
            get {
                return ResourceManager.GetString("Ribbon_View_Zoom_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 100%.
        /// </summary>
        public static string Ribbon_View_Zoom100 {
            get {
                return ResourceManager.GetString("Ribbon_View_Zoom100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom In.
        /// </summary>
        public static string Ribbon_View_ZoomIn {
            get {
                return ResourceManager.GetString("Ribbon_View_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom Out.
        /// </summary>
        public static string Ribbon_View_ZoomOut {
            get {
                return ResourceManager.GetString("Ribbon_View_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string Search_Button_Clear {
            get {
                return ResourceManager.GetString("Search_Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find All.
        /// </summary>
        public static string Search_Button_FindAll {
            get {
                return ResourceManager.GetString("Search_Button_FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find All Occurrences.
        /// </summary>
        public static string Search_Button_FindAll_Tooltip {
            get {
                return ResourceManager.GetString("Search_Button_FindAll_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next (F3).
        /// </summary>
        public static string Search_Button_Next {
            get {
                return ResourceManager.GetString("Search_Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous (Shift+F3).
        /// </summary>
        public static string Search_Button_Previous {
            get {
                return ResourceManager.GetString("Search_Button_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string Search_Clear_ToolTip {
            get {
                return ResourceManager.GetString("Search_Clear_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find All.
        /// </summary>
        public static string Search_FindAll {
            get {
                return ResourceManager.GetString("Search_FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find All Occurrences.
        /// </summary>
        public static string Search_FindAll_ToolTip {
            get {
                return ResourceManager.GetString("Search_FindAll_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a matches.
        /// </summary>
        public static string Search_Matches {
            get {
                return ResourceManager.GetString("Search_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hex.
        /// </summary>
        public static string Search_Mode_Hex {
            get {
                return ResourceManager.GetString("Search_Mode_Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regex.
        /// </summary>
        public static string Search_Mode_Regex {
            get {
                return ResourceManager.GetString("Search_Mode_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text.
        /// </summary>
        public static string Search_Mode_Text {
            get {
                return ResourceManager.GetString("Search_Mode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next (F3).
        /// </summary>
        public static string Search_Next_ToolTip {
            get {
                return ResourceManager.GetString("Search_Next_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous (Shift+F3).
        /// </summary>
        public static string Search_Previous_ToolTip {
            get {
                return ResourceManager.GetString("Search_Previous_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a matches.
        /// </summary>
        public static string Search_Results_Matches {
            get {
                return ResourceManager.GetString("Search_Results_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a V2.
        /// </summary>
        public static string Search_Results_V2Badge {
            get {
                return ResourceManager.GetString("Search_Results_V2Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset to Defaults.
        /// </summary>
        public static string Settings_Button_ResetDefaults {
            get {
                return ResourceManager.GetString("Settings_Button_ResetDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Settings.
        /// </summary>
        public static string Settings_Button_Save {
            get {
                return ResourceManager.GetString("Settings_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Settings.
        /// </summary>
        public static string Settings_Button_SaveSettings {
            get {
                return ResourceManager.GetString("Settings_Button_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bytes per line:.
        /// </summary>
        public static string Settings_Display_BytesPerLine {
            get {
                return ResourceManager.GetString("Settings_Display_BytesPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show line numbers.
        /// </summary>
        public static string Settings_Display_ShowLineNumbers {
            get {
                return ResourceManager.GetString("Settings_Display_ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show scroll markers.
        /// </summary>
        public static string Settings_Display_ShowScrollMarkers {
            get {
                return ResourceManager.GetString("Settings_Display_ShowScrollMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show status bar.
        /// </summary>
        public static string Settings_Display_ShowStatusBar {
            get {
                return ResourceManager.GetString("Settings_Display_ShowStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📺 Display Options.
        /// </summary>
        public static string Settings_Display_Title {
            get {
                return ResourceManager.GetString("Settings_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bytes per line:.
        /// </summary>
        public static string Settings_DisplayOptions_BytesPerLine {
            get {
                return ResourceManager.GetString("Settings_DisplayOptions_BytesPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📺 Display Options.
        /// </summary>
        public static string Settings_DisplayOptions_Header {
            get {
                return ResourceManager.GetString("Settings_DisplayOptions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show line numbers.
        /// </summary>
        public static string Settings_DisplayOptions_LineNumbers {
            get {
                return ResourceManager.GetString("Settings_DisplayOptions_LineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show scroll markers.
        /// </summary>
        public static string Settings_DisplayOptions_ScrollMarkers {
            get {
                return ResourceManager.GetString("Settings_DisplayOptions_ScrollMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show status bar.
        /// </summary>
        public static string Settings_DisplayOptions_StatusBar {
            get {
                return ResourceManager.GetString("Settings_DisplayOptions_StatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SETTINGS.
        /// </summary>
        public static string Settings_Header {
            get {
                return ResourceManager.GetString("Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🌐 Language.
        /// </summary>
        public static string Settings_Language_Header {
            get {
                return ResourceManager.GetString("Settings_Language_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🌐 Language.
        /// </summary>
        public static string Settings_Language_Title {
            get {
                return ResourceManager.GetString("Settings_Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a • Boyer-Moore-Horspool algorithm.
        /// </summary>
        public static string Settings_Performance_BoyerMoore {
            get {
                return ResourceManager.GetString("Settings_Performance_BoyerMoore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a • Up to 99% faster than V1.
        /// </summary>
        public static string Settings_Performance_Faster {
            get {
                return ResourceManager.GetString("Settings_Performance_Faster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a • Boyer-Moore-Horspool algorithm.
        /// </summary>
        public static string Settings_Performance_Feature1 {
            get {
                return ResourceManager.GetString("Settings_Performance_Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a • Parallel processing support.
        /// </summary>
        public static string Settings_Performance_Feature2 {
            get {
                return ResourceManager.GetString("Settings_Performance_Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a • Up to 99% faster than V1.
        /// </summary>
        public static string Settings_Performance_Feature3 {
            get {
                return ResourceManager.GetString("Settings_Performance_Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ⚡ Performance.
        /// </summary>
        public static string Settings_Performance_Header {
            get {
                return ResourceManager.GetString("Settings_Performance_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a • Parallel processing support.
        /// </summary>
        public static string Settings_Performance_Parallel {
            get {
                return ResourceManager.GetString("Settings_Performance_Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ⚡ Performance.
        /// </summary>
        public static string Settings_Performance_Title {
            get {
                return ResourceManager.GetString("Settings_Performance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a V2 ENGINE ACTIVE.
        /// </summary>
        public static string Settings_Performance_V2Active {
            get {
                return ResourceManager.GetString("Settings_Performance_V2Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable parallel search (faster for large files).
        /// </summary>
        public static string Settings_Search_EnableParallel {
            get {
                return ResourceManager.GetString("Settings_Search_EnableParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Highlight all matches.
        /// </summary>
        public static string Settings_Search_HighlightMatches {
            get {
                return ResourceManager.GetString("Settings_Search_HighlightMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search result limit:.
        /// </summary>
        public static string Settings_Search_ResultLimit {
            get {
                return ResourceManager.GetString("Settings_Search_ResultLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔍 Search Options.
        /// </summary>
        public static string Settings_Search_Title {
            get {
                return ResourceManager.GetString("Settings_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use wildcard search (?? notation).
        /// </summary>
        public static string Settings_Search_UseWildcard {
            get {
                return ResourceManager.GetString("Settings_Search_UseWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔍 Search Options.
        /// </summary>
        public static string Settings_SearchOptions_Header {
            get {
                return ResourceManager.GetString("Settings_SearchOptions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Highlight all matches.
        /// </summary>
        public static string Settings_SearchOptions_HighlightMatches {
            get {
                return ResourceManager.GetString("Settings_SearchOptions_HighlightMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable parallel search (faster for large files).
        /// </summary>
        public static string Settings_SearchOptions_ParallelSearch {
            get {
                return ResourceManager.GetString("Settings_SearchOptions_ParallelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search result limit:.
        /// </summary>
        public static string Settings_SearchOptions_ResultLimit {
            get {
                return ResourceManager.GetString("Settings_SearchOptions_ResultLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use wildcard search (?? notation).
        /// </summary>
        public static string Settings_SearchOptions_WildcardSearch {
            get {
                return ResourceManager.GetString("Settings_SearchOptions_WildcardSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🎨 Theme.
        /// </summary>
        public static string Settings_Theme_Header {
            get {
                return ResourceManager.GetString("Settings_Theme_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🎨 Theme.
        /// </summary>
        public static string Settings_Theme_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SETTINGS.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Relative Search.
        /// </summary>
        public static string RelativeSearchMenuString {
            get {
                return ResourceManager.GetString("RelativeSearchMenuString", resourceCulture);
            }
        }
    }
}
